### ISSUE TITLE
Work now page improvements

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#1]
In the work app, work now page should not save if there is 0 time.

**Comment by skoria** [comment]
I just input a zero hour non process task and got the following: 
Aug. 1, 2016 	Time Contribution 	FC_MembershipRequests 	Cooperative Work 	0.17 Hr 	test work 	

Strange it rounds it to 0.17??

**Comment by bhaugen** [comment]
> Strange it rounds it to 0.17??

That's not right! I'll try it out and see if I can reproduce it.

Was that on this page? https://ocp.freedomcoop.eu/work/non-process-logging/

(Lynn's talking above about a different page, but no matter...)

**Comment by bhaugen** [comment]
I just tried this in testocp and got zero hours and it did not even show it in history (because the history ignores zero contributions). So I can't reproduce it. @skoria did you do this in testocp or ocp?

**Comment by bhaugen** [comment]
Is it the first one here? https://testocp.freedomcoop.eu/accounting/contributions/34/
Are you sure you did not accidentally put some minutes in there?

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
