### ISSUE TITLE
Add settings to the coop worker dropdown menu

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#102]
The one in the upper right corner by your name when you are logged in.

Or at least, the language selection. 

Also, please somebody set a priority for this. It's easy to do if it is all settings, the same as the coop admin settings menu.

**Comment by bum2** [comment]
added but when user clicke there, the menu changes to the coop admin menu, not working but confusing so much... which is the way to keep the 'work' menu when on 'account/settings' page?

**Comment by bhaugen** [comment]
As I wrote in the chat, we would need to disconnect the settings page from the menus so it could live in either app. I can do it, but am waiting for @XaviP 's language selection experiment to decide if we should pull that one out of the settings app.

**Comment by bum2** [comment]
Issue resolved by Bob, now we have the settings page in the work app and in the user menu. Great!

**Comment by bum2** [comment]
Is missing the change password subpage in work app. Is needed for the user to change his password.

**Comment by bum2** [comment]
change password added by @bhaugen , done!
