### ISSUE TITLE
New page "Your Projects"

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#108]
In the new 'Your projects' page will be good to have a pre-created context agent (the project), and let managers edit the main agent and create sub agents nested to it (departments, commissions, etc), so they can self-manage the sub contexts of his project but not allowed to see or change nothing outside his main project agent. Do we have such a view or page?

The pre-created context agent is work for the admins (one user and two agents), but perhaps we can let the member create his own main agent: the 'project'.

**Comment by bum2** [comment]
Can be the 'Organization' page but filtering many things to avoid confussion and let some privacy...
In every agent will be good to have a privacy option to make all public (tasks, agents, etc) or private (only visible for group members and admins).

**Comment by bhaugen** [comment]
See also all [this confusion about collective agents and their users and managers of collectives here](https://github.com/FreedomCoop/valuenetwork/issues/90#issuecomment-239470620).

I think it would be better to add a much simpler version of creating new agents etc as participants in a project in the work app. One question would be if such participants get their own faircoin accounts or not.

The risk here is that adding too much of the complexity of organizational configuration in the admin app to the work app, and needing to train all of the collective managers in doing all that. So it would be better to redesign it so that it is less flexible and only does a very limited amount including only what they need to do.  As you can see from that other issue, the organizational configuration is confusing people already, and adding collective agents with users will confuse it more, although will also solve the problem of who can manage the collective faircoin account.

**Comment by bum2** [comment]
The actual version of this 'your projects' page in work app, now only list related context agents of the member.
There's an exception about the Freedom Coop group, so instead of showing agent details it shows the membership comments page.
If the member is coordinator of a project (manager) the page shows more details about the project and their members, and when entering the 'members_agent' page they see many info and stats about the project. If they are not managers, they see just a few info about the projects they participate or is member of them.
Still lacking to code some edit capability, the subpages of agent page (contributions, distributions, active-orders, etc) and the exchange feature.

**Comment by XaviP** [comment]
This feature is included in release: https://github.com/FreedomCoop/valuenetwork/releases/tag/v0.9.1
The new release is deployed in prod ocp.
Please, close this issue when tested or describe the new features that still working in.

**Comment by bhaugen** [comment]
I tried the Create new agent button on that new page in testocp.

The first time, I repeated an existing ID. When I clicked Save, it failed silently and I landed here:
https://testocp.freedomcoop.eu/accounting/agents/

The second time, the Save succeeded and I landed here:
https://testocp.freedomcoop.eu/accounting/agent/79/

In other words, both times I clicked Save in the work app, and landed in the coop admin app.

@bum2 do you know how to fix both of those problems?

**Comment by bum2** [comment]
Please don't use a admin user to see this. Only test with a plain member (not able to 'Create new agent'). Is not a problem, is just a work-in-progress page (first simple version to start with something). 
For members, the only 'agent' page available is the new 'members_agent.html' in /work/agent/id' urls. This is also a work-in-progress page with some info only for 'project coordinators' (managers). Is there where is needed all the improvements for editing a managed project (not by admins).

**Comment by bhaugen** [comment]
@bum2 if Lynn and I create a new project app today, do you want to put these new pages you are working on in the new app?  Do you think that is where they should go?

**Comment by bum2** [comment]
in the new app we can put the needed model Project (extension of EconomicAgent), and perhaps we should put there the sub-pages of the 'your project' page (except members_agent.html template, that is already in work app) only viewable by project managers. Maybe is easier to keep all templates in work app and only have the logic in the projects app...¿? if you prefer to change all the pages related the project manager role to the new app, then we can change the menu links, and point to /project/your_projects/ and /project/agent/id , even for only participants? or a diferent url if they are participants (/work/...) or managers (/project/...)? 
I think the easiest is maintain what already is placed in the work folder, and only put in the project folder model functions and views that only project coordinators-managers can see (and there's no a simplifyed version for participants). If the page should be viewed by any participant of a project (also if many things are disabled), then is better the work app... isn't it? what you think is best?

**Comment by bhaugen** [comment]
@fosterlynn is confused about your opinion and now I am, too.

I think it would be difficult and confusing to keep all of the UI in the work app and the logic in a separate project app.

**Comment by bhaugen** [comment]
P.S. I think I like
> model Project (extension of EconomicAgent)

better than adding project-specific fields to the EconomicAgent model.

**Comment by bum2** [comment]
I've added the button and form to create a new Project, using the new model (in the 'your projects' page). When a FCmember creates a project he is auto added as a coordinator and the project as child of Freedom Coop. Perhaps is better a "FC Members Projects" new parent for them all?
Also in the project editor (members_agent.html) is placed a button to Edit Project. If the context agent isn't a project yet, then it is added as such (when edited) with the choosed visibility and join style options.
The user must be member to create projects, but only coordinator to edit it.
I will like to test all this in testocp tomorrow...

**Comment by XaviP** [comment]
I think this issue can be closed. Please, reopen if needed.
