### ISSUE TITLE
Sending form in account/worksettings/ redirects to account/settings/

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#109]
If one is in work app settings and change some profile settings, like language, the form redirects to node app settings (account/settings/)

**Comment by bhaugen** [comment]
Oops, I thought I had fixed that. Must have missed something. Will fix.

**Comment by bhaugen** [comment]
fixed, I think.

**Comment by XaviP** [comment]
Thanks!

**Comment by XaviP** [comment]
Deployed on testocp: same behavior.
To reproduce: go work app settings, change language, press Save button -> redirects to node app.
Reopening.

**Comment by XaviP** [comment]
Sorry! I was testing in production site! Everything is ok, Closing.
