### ISSUE TITLE
How to deploy the OCP FairCoin functions

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#11]
Procedure:
* pull the latest version of the valuenetwork code from this repo
* pip install electrum-fair following these instructions: https://electrum.fair-coin.org/
* create a FairCoin wallet
* in the first valuenetwork directory, do: git clone https://github.com/Punto0/faircoin_nrp.git
* put the correct electrum-fair-nrp.conf file in the first valuenetwork directory
* test by going to your agent page in the OCP node app and clicking the Create Faircoin Address button.

**Comment by bhaugen** [comment]
This is probably for @XaviP and @Punto0

**Comment by bhaugen** [comment]
* pip install electrum-fair did not work on webfactional because the installation tried to install files in prohibited directories ( /usr/ )
* working on a better method, see #13

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
