### ISSUE TITLE
Pattern page not showing all facet selections

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#111]
After facet values are selected, the right side of the screen no longer shows the selections.  They are saved correctly.  Sometimes it shows one of the selections. https://testocp.freedomcoop.eu/accounting/change-pattern/25/3/

**Comment by bhaugen** [comment]
@fosterlynn -  I looked at the pattern on the change-pattern page you cited, and also in admin. The facet values look the same. What's missing? Or, what am I missing?

**Comment by fosterlynn** [comment]
Working now, hmmmm.

**Comment by fosterlynn** [comment]
I'm closing this, seems like it was part of the missing migrations problem, and I have also seen it working fine only a few days ago.

**Comment by bhaugen** [comment]
@fosterlynn could you please try to reproduce this bug again? I want to make sure it is not the same as the missing new agents problem in the todo form.

**Comment by fosterlynn** [comment]
It looks OK to me now.

**Comment by bhaugen** [comment]
Thanks. Reclosing issue.
