### ISSUE TITLE
Planned processes not connected

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#112]
We created a plan from recipe from demand page, it created both processes, but is only displaying one on the order-schedule. https://testocp.freedomcoop.eu/accounting/order-schedule/21/  And the Previous Process also does not display on the process page. https://testocp.freedomcoop.eu/accounting/process/20/  Both processes can be seen on the All Work page, under Decentrale.

Recipe is here: https://testocp.freedomcoop.eu/accounting/xbomfg/37/ (has had addition of glass jars since we created the plan)

**Comment by bhaugen** [comment]
I tried this locally, and it worked. Just tried it again in testocp, worked there, too:
https://testocp.freedomcoop.eu/accounting/order-schedule/22/

We have a had a series of weird bugs...will raise an issue about that.

**Comment by XaviP** [comment]
prod ocp is not updated, do you want me to deploy all changes there?

**Comment by bhaugen** [comment]
I think so. But some of these bugs were on testocp, only one on prod ocp. If you do update prod ocp, let me know in telegram.

**Comment by bhaugen** [comment]
Update prod ocp from master, though, not that new branch.

**Comment by fosterlynn** [comment]
I'm closing this - working now for Bob, and likely part of migrations problems.  I looked at the old work order, and the second process is now gone, so I can't see what it looks like now.  I'm sure it was there when we were doing the training session.  I'm assuming someone deleted it (totally OK, it is a test system, and we were doing a lot of messing around).
