### ISSUE TITLE
Some new agents not appearing on todo assignment selection list

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#113]
In particular, these two new agents do not appear on the "Assign to" selection in and Add Todo form on the All Work page:
[AVA](https://ocp.freedomcoop.eu/accounting/agent/68/)
[bob cannell](https://ocp.freedomcoop.eu/accounting/agent/69/)

**Comment by XaviP** [comment]
Closing as it seems solved. Please, reopen if needed.
