### ISSUE TITLE
Series of heisenbugs

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#116]
For example. three new agents that Mario created on ocp did not show up in the All Work Todo form "Assign to" selection list. Then some hours later, two of them showed up. See chat on Freedom Coop Admin telegram.

And then, https://github.com/FreedomCoop/valuenetwork/issues/112
and https://github.com/FreedomCoop/valuenetwork/issues/111

I don't get it.

**Comment by bhaugen** [comment]
@XaviP the latest heisenbug just disappeared after you updated prod ocp and I suppose restarted the server.

Do you have any caching going on on the server?

**Comment by XaviP** [comment]
No caching on server, but there was a lot of updates in code.


El 17/08/16 a les 11:23, Bob Haugen ha escrit:

**Comment by bhaugen** [comment]
You could try a migration. I don't know where prod ocp was at before your pull (which commit, I mean).

Also, are you using postgres on prod ocp now?

**Comment by XaviP** [comment]
https://github.com/FreedomCoop/valuenetwork/issues/117

**Comment by XaviP** [comment]
Yes, postgres. But having issues with migration as described:
https://github.com/FreedomCoop/valuenetwork/issues/117

**Comment by bhaugen** [comment]
I made a little bit of a breakthrough with one of these heisenbugs, the problem we have seen on both prod ocp and testocp, where people add new agents and users and then want to assign tasks to them, but they don't show up for several hours. 
I was finally able to reproduce the problem in my local development environment, and restarting the serve solved the problem. 
I still don't know why this is happening or how to fix it, but being able to reproduce the problem locally is a big step in the right direction.

**Comment by XaviP** [comment]
Closing this issue as it seems that with migration sync and other enhacements this bugs doesn't appear anymore.
