### ISSUE TITLE
Rethinking our development workflow

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#118]
I think we need to arrive to a stable version, tag it as 0.9.0 beta version or something like that, and stop deploying in prod ocp.
Then, we can develop in master branch until we think it's enough stable again, tag it as new version (0.9.1, 0.9.2,... or whatever), and deploy the new version in prod ocp.
So, the every day development can be deploy in testocp as soon as needed, but to deploy in prod ocp will be only with well tested new versions.
Maybe I'm too optimistic, because the pressure to improve is so big, but I'm afraid to make a big mistake if we continue this way.
What do you think?
Edit: this topic is about how to priorize new features too.

**Comment by bhaugen** [comment]
I mostly agree, as I wrote in telegram, but would like to see that membership share button go over into prod ocp **after** it is well tested.

**Comment by XaviP** [comment]
More concretely, I think when we have membership request and its tasks, contribute button, and creation of agent ready and tested, maybe we can tag it as 0.9.0. and stop deploying in prod ocp until stable again.

**Comment by fosterlynn** [comment]
I'm fine with the above.

**Comment by XaviP** [comment]
We can do it in two ways:
- Tag last stable commit in master branch as 0.9.0, and continue developing in master branch until new tag.
- Open new branch 0.9.0 when stable, and continue developing in master branch until a new 0.9.1 branch is created.
The first is the usual workflow. The second gives the oportunity to correct bugs in stable version branch, without deploying all changes in master.
What do you think?

**Comment by bhaugen** [comment]
I think the 2nd:
> Open new branch 0.9.0 when stable, and continue developing in master branch until a new 0.9.1 branch is created.

@XaviP can you tell us when to open a new branch? Or just do it and announce it, and I'll start working on your branch when it lands.

**Comment by XaviP** [comment]
I'll do it @bhaugen 
I'm doing some cleaning in github branches for this purpose. Deleted @bhaugen branches as he said they can be deleted. Please @fosterlynn @bum2 tell me if the branches you've created can be deleted:
https://github.com/FreedomCoop/valuenetwork/branches/all

**Comment by fosterlynn** [comment]
My branches can be deleted, they are all in master.  Thanks for doing this cleanup @XaviP !

**Comment by XaviP** [comment]
First tagged version: "Early beta stable release"
https://github.com/FreedomCoop/valuenetwork/releases/tag/v0.9.0

Now we can tag issues with expected version "v0.9.1", "v0.9.2" ... in order to stablish priorities.

**Comment by XaviP** [comment]
Cleaning up the issue queue. I've closed about 20 issues that I don't create, but they seem solved. Feel free to reopen if needed. Please, take a look at the issues you've created, maybe we can clean up further.
All this is a plan for prioritizing the development. I think we need to work with a manageable number of issues.

**Comment by bum2** [comment]
Great! some of the issues were not closed because there's still some work to do about them. Some 'pre-launch' issues were transformed in a on-going process of development and changes, linked to the UI on-going development in work app. Examples of this are 'wording', 'submenus' or 'back button'. 
So, as soon as a new feature or page is opened to members, the 'wording' changes continue, and the navigation improvements are developed. Some nav issues refer to admin views, and we have postposed all this admin's GUI development for later time. 
Is perfect to clean the queue and re-add more concrete issues, and let general development 'subjects' more like Labels...

**Comment by XaviP** [comment]
Ok, sorry for closing that issues, I thought they were solved yet.

**Comment by XaviP** [comment]
About priorities, I think we've achieved the user history of a user that wants to be freedomcoop member by the membership request cycle. So, I think the next user history to cover is how the member can explore the projects and its tasks.
I've created a new tag "next release" for order priorities, and I've assigned it to *New page "Your projects"*:
https://github.com/FreedomCoop/valuenetwork/issues/108
I was in doubt to assign it to *"Other" fields* too.
This is just a proposal. Please, reassign the tag if you think another priority must be taken.

**Comment by XaviP** [comment]
New page "Your Projects" included in release [0.9.1](https://github.com/FreedomCoop/valuenetwork/releases/tag/v0.9.1) and deployed in prod ocp.

**Comment by XaviP** [comment]
Closing this issue as we're already working with releases.
