### ISSUE TITLE
Decline and delete for membership requests

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#121]
Decline puts the request onto a new Declined Requests page.

Question: should decline include a reason for declining?

Delete just deletes them.

**Comment by bum2** [comment]
If the candidate comments thread is reachable by admins, then is not needed any 'reason' attached to the declined request (or the 'reasons' are a link to the comments page).

**Comment by bhaugen** [comment]
@bum2 @fosterlynn I just pushed the request_actions branch with the Decline action and a selector for showing different states of MembershipRequests.

It works, but has a CSS problem that I have not been able to fix. You can see it in this screenshot:
![radio_buttons](https://cloud.githubusercontent.com/assets/117439/18142305/9746ec74-6f82-11e6-8683-fdcb0a998182.png)

I am trying to get the radio buttons to line up nicely and horizontally beside the "State" label.

If you try this branch, be aware that you need to do a migration (for the new "state" field on MembershipRequest).

**Comment by bhaugen** [comment]
P.S. you will need to do something like this in shell_plus to set the state field for membership requests that already have agents:
```
reqs = MembershipRequest.objects.filter(agent__isnull=False)
for req in reqs:
    req.state = "accepted"
    req.save()
```
I'm checking into datamigrations to see if I can do this automatically as part of the branch.

**Comment by XaviP** [comment]
This is working in v0.9.4. Closing.
