### ISSUE TITLE
Should we add project admin functions to the work app or add more permissions to the admin app?

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#123]
The admin app already contains everything needed for project management, but at present, is only accessible to users who have django staff permissions. Everything in the admin app is accessible to all freedom coop admins. We might want to limit access more, like in the work app, where a project manager can only access their project and not much else.

The work app does not contain much of anything required for project management.

**Comment by bhaugen** [comment]
One other angle on this question: the admin app is necessarily complex, because it needs to handle any form of organization and lots of other complications. It might be possible to design something a lot simpler just for configuring and managing projects in the work app. I'm not sure what could be cut out, but I think a couple of people have been thinking about how to simplify project configuration.

**Comment by bum2** [comment]
Yes. Project manager functions in the workapp. Now there's a first simple version of the 'your projects' page in workapp, that i've copied from 'Organization' page (and 'agent' page) but only for projects related the member, and much more info if the member is 'manager' or 'coordinator' of a project (still not editable project info, coming soon).
What is lacking is the subpages of 'agent' page in admins app, but versioned (simplifyed) for the work app (members), like 'contributions', 'distributions', 'active orders', 'timeline' (not working), 'association graph' pages...
The workapp version of 'maintain associations' page should be a simple way for 'managers' to configure internal project's associations among the participants (adding them as members or participants, or putting someone more as a manager, etc).
Also here at 'your projects' page, when a manager is viewing the 'members_agent' page of a managed project, sees more info and will see the subpages, but also will be needed a simple tool to create exchanges.
All this features and subpages now are commented, and step by step, hopefully with the help of somebody, we can start to open the managing capabilities for members.
This is one big subject to code on (the 'Your projects' page), and the other big one is the 'plan work' and all what that means about resources, proceses, orders, recipes, etc, offered to managers for managing their project process tasks (the 'Plan project process' page)...

**Comment by bhaugen** [comment]
@fosterlynn and I were talking about this as we ran errands today, and we want to know:
* What will project managers want to do? That is, how much of the coop admin app will they need?
* What won't they use in the coop admin app?

This is about whether it is easier to duplicate all of the functions they will want to use in another app (whether the work app or a new project app), or to tighten up permissions in the coop admin app.

**Comment by XaviP** [comment]
I think, in a first stage, a project manager would want to manage users and tasks for the project:
- Ability to edit the context agent data.
- Ability to include new users/agents as childrens of the context agent:
  - from an existing agent in ocp,
  - creating a new user/agent directly,
  - through a join-request cicle when ready (https://github.com/FreedomCoop/valuenetwork/issues/107)
- Ability to create/edit simple tasks related to the project. This include the tasks related to the context agent that have been created by another agent children of the context agent.
- Ability to create/edit all staf related with complex tasks. Sorry for my lack of terminology speaking about some ocp concepts.
I agree with a new project app with this.

**Comment by bhaugen** [comment]
> - Ability to create/edit simple tasks related to the project. This include the tasks related to the context agent that have been created by another agent children of the context agent.

They can already do this in the work app, can't they? (That's not an argument against creating something new, and it's correct to list it among the things a project manager wants to do. Just checking to make sure project managers can do this now. I thought it worked, anyway.)

> - Ability to create/edit all staf related with complex tasks (recipes, redestributed payments, ...). Sorry for my lack of terminology speaking about some ocp concepts.

Sorry if OCP terminology is confusing. I suppose some of it is. I understood everything you wrote except for "all staf".

**Comment by bhaugen** [comment]
Will project managers want to:
* create new resource types?
     * See also https://github.com/FreedomCoop/valuenetwork/issues/130
* create recipes?
* plan from recipes?
* create work orders?
* create customer orders?
* create exchanges?
* create value equations and distribute income according to value equations?
* manage virtual accounts tied to Euro bank accounts?

Will they need to understand Patterns and some of other configuration complexities of OCP?

**Comment by bhaugen** [comment]
Regarding my previous comment, @fosterlynn and I just discussed this situation on our morning walk and we are starting to agree with the idea of a separate new Project app for this stuff. We would need to figure out a sequence of needs and reproduce the features of the coop admin app as-needed.

**Comment by fosterlynn** [comment]
Or, perhaps also useful to look at from the other direction - what currently in the node admin app would NOT be appropriate to let a project admin have.  Here's a starting list, please give your views.

Give a user admin privileges
Add or change facets and facet-values?
Add or change agent types and agent association types
Add or change units

Mostly these are the base setup items that require coordination across the network.

**Comment by fosterlynn** [comment]
>Regarding my previous comment, @fosterlynn and I just discussed this situation on our morning walk and we are starting to agree with the idea of a separate new Project app for this stuff

Clarification: I am not actually leaning either direction, I see advantages and disadvantages to both.  I think the advantages to creating a new project manager app are mostly in the team and development process, not so much in the final outcome.  Which is of course very valid.

**Comment by fosterlynn** [comment]
Part of this discussion should be what do we want to do with resource types and recipes and resources.  It will be relatively easy (although not quick) to filter any page in the app which is based on existing relationships to context agents. It will require a lot more thought to figure out what to do with resource types and recipes and resources, which have less or no ties to context agent.  Recipes do have a tie in the process types, which reference a context agent, but they don't "live" in one context.

This would need to start with some discussion of how Freedom Coop wants to think about this on the ground with real projects, some of which will be very separate, and some of which will want more integration across the network.  

For example, does FC want to standardize on types of work across the network?  Does FC want to be able to trade resources of the same defined type across projects and nodes?  If so, would a resource type from one project or vendor actually be the same resource type in the system as something that is basically the same but from another project or vendor?  Etc.....

**Comment by XaviP** [comment]
> I understood everything you wrote except for "all staf".

Sorry, staf -> stuff. Yes, this is better explained by yourself in the [next comment](https://github.com/FreedomCoop/valuenetwork/issues/123#issuecomment-242974512).

> I think the advantages to creating a new project manager app are mostly in the team and development process, not so much in the final outcome. Which is of course very valid.

Yes, my point of view for a new app is to be easier to mantain the code and for avoiding merge problems.

> We would need to figure out a sequence of needs and reproduce the features of the coop admin app as-needed.

Maybe for a gradual and participative development, we can begin with the very basic and sure needs and progress later with some complex ones, or the ones detected by project admins users (if this doesn't make more complex the development)

**Comment by fosterlynn** [comment]
>Maybe for a gradual and participative development, we can begin with the very basic and sure needs and progress later with some complex ones, or the ones detected by project admins users (if this doesn't make more complex the development)

This will also give you a chance to design a different navigation and any other UX/UI things that you would like fixed, from a smaller starting place, so not such a big change all at once.  Ping @bum2  :)  Even if in the end, most of the node admin app is also in the project app, which I think it will be.

**Comment by fosterlynn** [comment]
I looked at the your-projects page in testocp, and it has plenty of room, in case we need to add a lot of navigation there for project managers - could do a left nav, for example.  If it won't fit well on the top, which seems challenging.  (I still think they will need most of what is in the node admin app.)  So, conclusion: seems fine to do in the work app.

@XaviP I think you were wanting to do a new app, are you OK with the work app?  At least for now?

**Comment by XaviP** [comment]
This is already clear. Closing. Please, reopen if needed.
