### ISSUE TITLE
Problems installing electrum-fair on ocp.webfactional.com

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#13]
Here are the error messages:
```
[ocp@web527 valuenetwork]$ pip install --user https://electrum.fair-coin.org/download/Electrum-fair-2.3.3.tar.gz
[just posting the end of a very long string of messages]
    copying electrum-fair.desktop -> /usr/share/applications/
    error: /usr/share/applications/electrum-fair.desktop: Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-UJ1dGK-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-PiAJhR-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-UJ1dGK-build/
```
Here's what Webfaction support advised:

... the application tries to create a
file in /usr/local/share/applications/, which is not allowed.

I am not completely sure why the application would try to create a desktop
shortcut there, but there are two options:

- According to the following URL, you should be able to run the application
without installing it:

https://github.com/FairCoinTeam/electrum-fair

That is, you can download it, extract the package, change to the application
directory and run it with

/electrum

You can also run it with:

python2.7 electrum-fair

from the same directory.

- The same URL also provides instructions on how you can install it on Linux
systems:

https://github.com/FairCoinTeam/electrum-fair#install-on-linux-systems

The difference here would be that you will not use sudo, but something like this:

mkdir -p $HOME/Electrum
python2.7 setup.py sdist
python2.7 setup.py install --root $HOME/Electrum

This should install the application in ~/Electrum where it will create the
necessary directories.

**Comment by bhaugen** [comment]
@XaviP says:
You can try to install it with virtual env:
https://github.com/FairCoinTeam/electrum-fair/blob/2.3.3/electrum-fair-env

 The package is for install as a desktop app
 And the proper branch to work with is last stable version: 2.3.3

**Comment by bhaugen** [comment]
More from @XaviP - how to install without virtualenv:
```
git clone -b 2.3.3 --single-branch https://github.com/FairCoinTeam/electrum-fair.git
cd electrum-fair
python setup.py install
sudo apt-get install pyqt4-dev-tools
pyrcc4 icons.qrc -o gui/qt/icons_rc.py
sudo apt-get install protobuf-compiler
protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto
sudo apt-get install python-pycurl gettext
./contrib/make_locale

./electrum-fair
```

**Comment by bhaugen** [comment]
Still more:
you need virtualenv, electrum-fair has many dependencies:
    install_requires=[
        'slowaes>=0.1a1',
        'ecdsa>=0.9',
        'pbkdf2',
        'requests',
        'qrcode',
        'protobuf',
        'tlslite',
        'dnspython',
    ],

**Comment by bhaugen** [comment]
Still more:
We can try a simple version with only running:
git clone -b 2.3.3 --single-branch https://github.com/FairCoinTeam/electrum-fair.git
cd electrum-fair
python setup.py install

And then run electrum-fair as a daemon

**Comment by bhaugen** [comment]
XaviP:
The only thing I see is that you need to create a wallet previous running electrum_fair_nrp
[4:15:20 PM] Bob Haugen:
yes

[4:15:23 PM] XaviP:
./electrum-fair create

And if we install this way, maybe in electrum_fair_nrp init() we need to point where is electrum-fair
 as it's not installed in the system

**Comment by bhaugen** [comment]
@XaviP - you suggested:
> We can try a simple version with only running:
> git clone -b 2.3.3 --single-branch https://github.com/FairCoinTeam/electrum-fair.git
> cd electrum-fair
> python setup.py install

I  had to do
git clone -b 2.3.3 https://github.com/FairCoinTeam/electrum-fair.git
because git did not understand --single-branch.
But the result at the end was the same error message as before: 
```
copying electrum-fair.desktop -> /usr/share/applications/
error: /usr/share/applications/electrum-fair.desktop: Permission denied
```

**Comment by XaviP** [comment]
What about:
```
virtualenv env
git clone -b 2.3.3 https://github.com/FairCoinTeam/electrum-fair.git
source env/bin/activate
cd electrum-fair
python setup.py install
```

**Comment by bhaugen** [comment]
I'll try that tomorrow.

**Comment by bhaugen** [comment]
Solved by putting site-packages in a virtualenv on webfaction.
