### ISSUE TITLE
Process logging for coop self employed?

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#133]
When do we want to include process logging for coop members?  We took it out to simplify in the beginning to simple tasks.  It is still there, just commented out, so not hard to implement from a technical perspective - just a question of when admin people are ready to support it.

(I am thinking about it because I'm making a list for project coordinators, and a lot of it is planning, and planning is for processes.  There is not much point in planning, or recipes, or inventory that is created in a project, if there is no process logging.)

**Comment by bum2** [comment]
Yes we need to include it, what is the view and template used?

**Comment by fosterlynn** [comment]
There used to be a section in the work my_dashboard page but commented out - is gone now, so maybe is in another page, or back in version history.  From there it calls the work process_logging page.  Already made to work in the work app.

I can do this next if you like, tomorrow.  Or I could start the planning.  You may want to think about where the process logging should go now with the newer pages and menus.

**Comment by bum2** [comment]
I thought the process login is what we already have in the 'your tasks' page (it should list simple and process tasks, isn't it?).
I simply split the former dashboard blocks in two pages, to be kind for small devices. Left block is 'your tasks' page and right block is now the 'take a new task' page.

**Comment by fosterlynn** [comment]
>I thought the process login is what we already have in the 'your tasks' page (it should list simple and process tasks, isn't it?).

I don't find the process tasks in testocp.  And that code is gone from my_tasks ('your tasks') template.  I'll find the code and you can decide where to put it, and when. 

>I simply split the former dashboard blocks in two pages, to be kind for small devices.

Thanks, good to be kind to small devices!  

(The process code was already commented out when you split the pages, that decision happened earlier.)

**Comment by fosterlynn** [comment]
>(The process code was already commented out when you split the pages, that decision happened earlier.)

I was wrong, it was taken out, not commented.  I found I think the most recent version of my_dashboard.html before the process logging code was taken out, here: https://github.com/FreedomCoop/valuenetwork/blob/27286ce6a5af8f97f5dfb88442553c8a5f31eb9a/work/templates/work/my_dashboard.html. 

The main section starts at line 182.  There is another section for process related tasks using the person's skills at 317.  (These are originally from the My Work page in the node admin app, so you can more or less see what they look like there.)

Then there is the process_logging.html page, which this my_dashboard code links to.

So, I wonder what would be best?  I could work on it if I know how you want it to fit into the UI.  Would you want it to be a new separate page?  (If this is too confusing, I will just make a new page for it, and you can see how you want to fit it in.)

**Comment by bhaugen** [comment]
@bum2 @XaviP do you understand the differences between process logging, simple tasks (used to be called Todos), and "Log extra tasks" (used to be called non-process logging)?

And why those differences exist? It might be better to think up more clear and descriptive names and better explanations. We've thought about ways to unify them all, too, but haven't come up with anything.

**Comment by fosterlynn** [comment]
@bum2 I am doing a new page for this, and then you can fit it in as you like.

**Comment by fosterlynn** [comment]
@bum2 I made a new page, but it is not completely working, just for you to look at.  It is in the branch process-logging, or here is a picture:
![my-process-tasks](https://cloud.githubusercontent.com/assets/3776081/18136021/832abd10-6f69-11e6-8e16-18e4ae835dda.png)

The buttons do not take you back to the right place yet.  This is because I think you will not want it the way it is.  

Here are all the pieces:
* Simple task logging (done)
* Unassigned simple tasks to take (done)
* Process task logging (new)
* Unassigned process tasks to take (new)

I have the last 2 both on the new page above.

Options I can see:

1. Separate out the 2 new pieces into 2 new pages, so we will have 4 pages.  This might be better for phones, but might be confusing/annoying to have to go 2 places to see your work or to see work you can take.
2. Add process task logging to the simple task logging page and add unassigned process tasks to the unassigned simple tasks page.  Less good for phones, less confusing/annoying.

What do you think is best?

**Comment by bum2** [comment]
I think the best is go for second option. Same page for simple and process logging ('your tasks', above the simple task block), same page for take new tasks, simple and process.
When user has no tasks assigned we can show a placeholder saying 'No assigned tasks. Go to take some tasks or create a new task' or something similar.

**Comment by fosterlynn** [comment]
OK, I will do that in my branch, and then you can review it.  Might not be able to get to it for a day or two.

**Comment by fosterlynn** [comment]
Finished this, pushed my process-logging branch.  @bum2 feel free to work with the css!  :)

**Comment by bum2** [comment]
Thanks Lynn! your branch is merged with fobi branch and now i will put all this in testocp so we can test thoroughly all the new features...

**Comment by fosterlynn** [comment]
Closing.
