### ISSUE TITLE
[Installation] No module named sanitizer (from html5lib.sanitizer import HTMLSanitizer)

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#134]
In a fresh ocp local installation, visiting / with devserver, gives error `ImportError at / -- No module named sanitizer`
```
/valuenetwork/work/forms.py in <module>
                import bleach
/env/local/lib/python2.7/site-packages/bleach/__init__.py in <module>
                from html5lib.sanitizer import HTMLSanitizer
```

**Comment by bhaugen** [comment]
See https://github.com/mozilla/bleach/issues/212
and https://github.com/mozilla/bleach/issues/217
especially https://github.com/mozilla/bleach/issues/212#issuecomment-233986871
I just did the test specified in that comment and it worked. So I'm not sure what happened in your fresh install.

**Comment by XaviP** [comment]
Thanks @bhaugen 
Fixed in https://github.com/FreedomCoop/valuenetwork/commit/282f034246b3a7d98a66a9b6f299deab863b2d47
Closing.
