### ISSUE TITLE
More comments visibility improvements

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#136]
Or as least I think they will be improvements.

1. An all-comments page in the coop admin app with a date range selection.
2. On the organization pages where discussion pages are listed alongside agents, add a comment count.

If nobody disagrees, and I get done with the other issues in this sprint, maybe I'll do that. If I get some enthusiastic approvals, I'll definitely do it.

**Comment by XaviP** [comment]
> If I get some enthusiastic approvals, I'll definitely do it.

goooooooooooooooooooooooood !!! niiiiiiiiiiiiiiiiiiiice !! I liiiiiiiiiiiiiiiiiiiiiiiike it!! :-)

**Comment by bhaugen** [comment]
Ok, @XaviP @bum2 I pushed the comment_extras branch with most of the work on this. Only thing missing is the date range selection on the all comments page.

I also did not style that page, and did not put it on the menus anywhere. I'll leave that to @bum2 

The relative url is /accounting/comments/

Please suggest improvements, or just make the improvements. @bum2 if you start working on this, I'll stop and leave it to you.

I think this branch is fairly safe to merge into master when you are done with it. No migrations, doesn't affect any functional features.

**Comment by bhaugen** [comment]
Added pagination, will merge comment_extras into master and delete it. Don't think it needs date range selection yet. When it does, I'll add it either in master or another branch depending on what else is going on.

**Comment by bhaugen** [comment]
Now available at https://testocp.freedomcoop.eu/accounting/comments/

Where should that page go in the freedom coop admin app?

**Comment by bum2** [comment]
Marvelous folks!!  In admin app we can just add one more link in the sub menu of Organization (the label links).... I think is better to focus on how to integrate the comments features you did in the 'project coordinators' pages, so the whole thing is useful without admin role.

**Comment by bum2** [comment]
Marvelous folks!!  In admin app we can just add one more link in the sub menu of Organization (the label links).... I think is better to focus on how to integrate the comments features you did in the 'project coordinators' pages, so the whole thing is useful without admin role.

**Comment by XaviP** [comment]
This comments improvements are included in release v0.9.4 https://github.com/FreedomCoop/valuenetwork/releases/tag/v0.9.4
Closing this issue.
