### ISSUE TITLE
Project participants etc in new project manager pages

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#138]
We can rethink how this is done. The current Maintain Associations form was designed to be used in two different situations: adding associates to a group, and also adding associations for an individual.

The project manager situation is different in two ways:
* it will only need to add associates to a group, and
* the types of associations are also likely to be limited.

What will there be? Participant and manager? Anything else?

We might even be able to automatically create participant associations when the project manager creates a new agent.

What do you all think? @bum2 ?

**Comment by bum2** [comment]
This Maintain Associations page for project coordinators needs to list users related the project in any state (candidate or active), to manage the 'state' of any relation and the kind of relation (all of them). So the context is fixed being always 'the project'.
Also will be good to let them manage also the upside associations of the project, showing only a subset of agents that are projects with 'public' and 'autojoin' settings, and the association types are only 'participant', 'child' or 'supports'. 
We will keep on modeling this second part of the page in future releases, so the projects with 'moderated' access also shows there and let choose also a 'candidate participant' relation, and that brings a internal ocp form to join request from inside ocp.
And yes, the initial relation of 'candidate participant' must be created automatically when coordinators press the 'Create OCP Account' button... how is it going with that button?

**Comment by bhaugen** [comment]
>  how is it going with that button?

I'm working on it now. Should be done in the next few hours. The button and new objects creations will be done sooner than the notification, so I'll push them first. I'm working in master, hope that is ok @XaviP ?

**Comment by bum2** [comment]
For me is ok to finish this first version of the button in master, test soon and publish to prod asap.

**Comment by bhaugen** [comment]
P.S. because I switched my plans to a more complicated method and I am getting behind on the dishes, this button will not be finished today, but I am making progress, and it should be done tomorrow.

**Comment by XaviP** [comment]
> I'm working in master
Ok, no prob.

**Comment by XaviP** [comment]
Closing as this is in v0.9.4. Please, reopen if needed.
