### ISSUE TITLE
NoticeType matching query does not exist.

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#141]
Admins are recieving many emails:
```
Traceback (most recent call last):

  File "/home/ocp/app/env/lib/python2.7/site-packages/notification/engine.py", line 59, in send_all
    if notification.send_now([user], label, extra_context, sender):

  File "/home/ocp/app/env/lib/python2.7/site-packages/notification/models.py", line 150, in send_now
    notice_type = NoticeType.objects.get(label=label)

  File "/home/ocp/app/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/home/ocp/app/env/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name

DoesNotExist: NoticeType matching query does not exist.
```
- I try to migrate again to make the NoticeTypes again, but it doesn't solve it.
- I just sttoped the notifications in cron.
- I see in 
https://testocp.freedomcoop.eu/admin/notification/noticequeuebatch/
that there are two notifications pending (probably which are giving the errors): they are trying to send with "work_join_request" NoticeType, which is not activated.

**Comment by XaviP** [comment]
Bug is here:
https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L2216

**Comment by XaviP** [comment]
Solved here:
https://github.com/FreedomCoop/valuenetwork/commit/2b2adc507dde22f88cbd4a66c3f33b0a3d47aa76
Now notifications running again.

**Comment by XaviP** [comment]
Oh, we need first to erase the pending notifications with the error.
@bhaugen Do I have to erase this queue batch ??
https://testocp.freedomcoop.eu/admin/notification/noticequeuebatch/

**Comment by bhaugen** [comment]
> @bhaugen Do I have to erase this queue batch ??

If you want to turn the cronjob on, they will continue to cause errors. @bum2 do you think these are test messages? @XaviP given that this is testocp, I would just delete them.

And do you understand the problem? I think the code Xavi commented out was probably a cut-and-paste without knowing that a new notification requires a lot of setup.

**Comment by XaviP** [comment]
Deleted all notice queue batch. Notifications in cron running again.

**Comment by bum2** [comment]
Sorry, you are true. I simply put the code to notificate coordinators, but is missing the rest of configuration. Where we should define this notification to make it work?
We haven't seen this bug because it was failing before due the wrong association try when a new join-request is saved.
Another related thing is the general 'comments' page for admins: it is showing any comment in any request process, so the project's feedbacks are there also. Will be good to filter only comments related membership process, or adapt the whole membership process in the generic system we have now for projects and coordinators...

**Comment by bhaugen** [comment]
> Where we should define this notification to make it work?

I explained the required setup a little [here](https://github.com/FreedomCoop/valuenetwork/issues/140#issuecomment-245254482)

I'll find the notification doc and add a link over there, too.

**Comment by XaviP** [comment]
afaik, notifications and subscription system are ready for admins (node app) but I think it's not ready for project managers or members not-admins (work app)
I think we have to priorize work: we have to deploy all this first (well tested)

**Comment by XaviP** [comment]
Solved, notifications running, closing.
