### ISSUE TITLE
Waiting for the 0.6.10 django-fobi version

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#144]
I leave this issue here as a reminder, as I closed the issues which talk about this.
IMPORTANT: Do not run *makemigrations* in testopc nor prod ocp until solved this bug in fobi.

**Comment by bhaugen** [comment]
Is this something we can help Fobi with again?

**Comment by XaviP** [comment]
This is the issue opened in django-fobi repo:
https://github.com/barseghyanartur/django-fobi/issues/37

**Comment by bhaugen** [comment]
Ah, I did not understand that it had gotten that complicated...

**Comment by XaviP** [comment]
django-fobi 0.6.10 is released: https://github.com/barseghyanartur/django-fobi/releases/tag/0.6.10
To upgrade django-fobi to 0.6.10:
```
pip uninstall django-fobi
pip install django-fobi==0.6.10
python manage.py migrate
```
Tested in local, no more migrations running makemigrations after upgrade :-)

**Comment by XaviP** [comment]
Upgraded testocp and prodocp to django-fobi 0.6.10 without problems.
Please, consider to upgrade it your dev enviroments if you want to use an updated db from testocp.
This issue is ready to close. I leave it a couple of days to wait until all dev enviroments successfully upgraded.

**Comment by bhaugen** [comment]
Upgraded mine.

**Comment by fosterlynn** [comment]
Upgraded locally.
