### ISSUE TITLE
Bug at recovering form data on reload in joinaproject

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#148]
There's a bug in the js trick to fill-up the custom form fields when reload or error (in public project forms): if you type a line-break in the field text the js crashes. Is needed more parsing to convert line-breaks to safe js string before sending var 'post' to the template from view.py def joinaproject_request to the joinaproject_request.html template

**Comment by bhaugen** [comment]
How to reproduce this locally?

**Comment by bum2** [comment]
do just that (place a text with line-breaks in a custom field of a public join-request form) and check how the JS fails when trying to fill again the screen field data with the POST values, when reload or any error in the form or captcha. Because the js breaks, the order of the form fields is bad again also (with the captcha in the middle of the form, and the presentation custom text below it) beacuse that fields are ordered via jquery.

**Comment by bhaugen** [comment]
Reproduced. Thinking about it...

**Comment by bhaugen** [comment]
@bum2 how much of the javascript at the top of the "work/joinaproject_request.html" template came from fobi and how much did you add? I'd like to isolate anything that might be a fobi bug.

**Comment by bhaugen** [comment]
> where did decodeHTMLEntities come from? I can't find it in fobi. It might be the source of the bug.

I commented out both of the str.replace statements in that function and the syntax error still happened.

**Comment by bhaugen** [comment]
I haven't made any headway in solving the problem, although I did a lot of tinkering. 

@bum2 did you find code examples for the fobi form handling in work/views/joinaproject_request and the work/joinaproject_request.html template? Anywhere in the fobi repo? I didn't find much, but maybe I was looking in all the wrong places...

**Comment by bhaugen** [comment]
Ok, I might have fixed it. Pushed a simple change from escape to escapejs that seems to have worked. @bum2 please test locally when you get a chance.

**Comment by bum2** [comment]
The fix works great @bhaugen , thanks!
