### ISSUE TITLE
Join request in a project by an existing user/agent

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#149]
When an already user/agent accesses to the public fobi form of a project, the form asks for all user data. Maybe we can conditionally show the user/agent information instead of the new user fields if the user is logged in, and when submitted not create a new user but use the logged in one. I don't  know if this is compatible with the current request-candidate-member flow.

**Comment by bum2** [comment]
Yes, this is the 'internal' version of the form, for logged-in users, still pending to do. Also we need a internal ocp list of public projects, so they can simply join in if they are 'autojoin' or open the form to apply if they are 'moderated'. I think is to work on the 'maintain associtions' sub page for project coordinators...

**Comment by XaviP** [comment]
> this is the 'internal' version of the form, for logged-in users, still pending to do.

What I was trying to explain is that the same page/form can be used by annonymous users and by logged-in users, if a conditional is added here:
https://github.com/FreedomCoop/valuenetwork/blob/master/work/templates/work/joinaproject_request.html#L107
If user is logged-in, don't print the join_form but use the logged-in user data.
And when submitted the form, just add the logged-in user data into join_request created. If so, when user is accepted, don't create user/agent but use the one is created yet.

I don't know if this simplify the development or make it more complex. Just an idea. Ignore me if not needed.

**Comment by XaviP** [comment]
I see this feature in testocp, so I cose this issue.
