### ISSUE TITLE
bad site URL in outgoing emails

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#15]
@XaviP says 
> BTW, when I try to recover my passwrd or finishing a task, the link in the email points to  http://nrp.webfactional.com, not to the http://vps245823.ovh.net/ocp site.

**Comment by XaviP** [comment]
Hi Bob, the reset passwd is sending an email with a link like this:
http://vps245823.ovh.net/ocp//ocp/account/password/reset/a-4cl-b78d90fb049...

**Comment by bhaugen** [comment]
Well, at least it has the correct domain name instead of nrp.webfactional. I'll take a look at the code later today. We also got a problem with the django admin link: http://vps245823.ovh.net/admin/ - it's missing the ocp, while the password reset duplicates it. I think the problem is the ocp at the end of the base urls, which are expecting / (that is, nothing after the base url). Might need to think a bit about how to handle that in a general way (so it would also work if deployed with just a base url).

Am I making sense?

**Comment by XaviP** [comment]
Yes! It would be good if you achieve that ocp can be configured with any
url, with only domain or with domain and extension.

Thanks Bob!

El 08/06/16 a les 12:43, Bob Haugen ha escrit:

**Comment by bhaugen** [comment]
I'm looking at the code and have no idea why ocp is duplicated in that password reset url. That is, I don't see how this code could do it:
```
        protocol = getattr(settings, "DEFAULT_HTTP_PROTOCOL", "http")
        current_site = get_current_site(self.request)
        for user in User.objects.filter(email__iexact=email):
            uid = int_to_base36(user.id)
            token = self.make_token(user)
            password_reset_url = u"%s://%s%s" % (
                protocol,
                unicode(current_site.domain),
                reverse("account_password_reset_token", kwargs=dict(uidb36=uid, token=token))
            )
```

current_site.domain is vps245823.ovh.net/ocp/
But you got http://vps245823.ovh.net/ocp//ocp/account/password/reset/a-4cl-b78d90fb049
I don't see where the extra //ocp is coming from. Might need to run some traces...which I don't have time for today.

**Comment by XaviP** [comment]
Ok, let's make easy. I'm looking for a domain for this test instance.

**Comment by XaviP** [comment]
New domain: http://testocp.freedomcoop.eu
Changed name in http://testocp.freedomcoop.eu/admin/sites/site/1/
But the recovering passwd email links still with old vps24... I think there's another place to change it, isn't it?

**Comment by bhaugen** [comment]
>  I think there's another place to change it, isn't it?

I don't think so. Might try restarting the server and then trying again. Could be cached someplace.

We did not create the account app, which is where that comes from, but the code says current_site. which comes from admin.sites.

**Comment by XaviP** [comment]
Yes, you're right, restarting works. Thanks!

**Comment by bhaugen** [comment]
Should we close this issue? Or, more to do? Maybe more doc?

**Comment by XaviP** [comment]
Documented, you can close it.
