### ISSUE TITLE
Is there any reason to keep djangorestframework==2.4.8 ?

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#154]
- Last version of djangorestframework is 3.4.6
https://pypi.python.org/pypi/djangorestframework

- I don't see 'rest_framework' in INSTALLED_APPS

- A search like `grep -r "rest_framework" ./` gives:
```
./valuenetwork/api/views.py:from rest_framework import viewsets, permissions
./valuenetwork/api/urls.py:from rest_framework import routers
./valuenetwork/api/urls.py:    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
./valuenetwork/api/serializers.py:from rest_framework import serializers
./valuenetwork/settings.py:    'rest_framework',
./valuenetwork/settings.py:    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',),
```

Can I safely remove *==2.4.8* from requirements.txt ??
Which check can I do to see if version 3.4.6 can be installed ??

**Comment by bhaugen** [comment]
> Can I safely remove ==2.4.8 from requirements.txt ??
> Which check can I do to see if version 3.4.6 can be installed ??

I don't know. It will take retesting and possibly upgrading all the existing apis, which I would prefer to delay until we are using the apis. Which we aren't yet.

**Comment by XaviP** [comment]
Ok thanks, yes this is not a priority.
