### ISSUE TITLE
Form to join a project

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#158]
Hi I have a problem when managing the forms to join projects:
https://testocp.freedomcoop.eu/work/agent/82/join-requests/

AttributeError at /work/agent/82/join-requests/

'NoneType' object has no attribute '_default_manager'

Request Method: 	GET
Request URL: 	https://testocp.freedomcoop.eu/work/agent/82/join-requests/
Django Version: 	1.8.14
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute '_default_manager'

Exception Location: 	/home/ocp/app/valuenetwork/work/views.py in join_requests, line 2531
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/home/ocp/app/valuenetwork',
 '/home/ocp/app/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/ocp/app/valuenetwork/']

Server time: 	Lun, 19 Sep 2016 10:57:04 +0000

Environment:

Request Method: GET
Request URL: https://testocp.freedomcoop.eu/work/agent/82/join-requests/

Django Version: 1.8.14
Python Version: 2.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_comments',
 'pinax_theme_bootstrap_account',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'django_extensions',
 'easy_thumbnails',
 'notification',
 'corsheaders',
 'rest_framework',
 'captcha',
 'fobi',
 'fobi.contrib.themes.bootstrap3',
 'fobi.contrib.themes.foundation5',
 'fobi.contrib.themes.simple',
 'fobi.contrib.plugins.form_elements.fields.boolean',
 'fobi.contrib.plugins.form_elements.fields.checkbox_select_multiple',
 'fobi.contrib.plugins.form_elements.fields.date',
 'fobi.contrib.plugins.form_elements.fields.date_drop_down',
 'fobi.contrib.plugins.form_elements.fields.datetime',
 'fobi.contrib.plugins.form_elements.fields.decimal',
 'fobi.contrib.plugins.form_elements.fields.email',
 'fobi.contrib.plugins.form_elements.fields.file',
 'fobi.contrib.plugins.form_elements.fields.float',
 'fobi.contrib.plugins.form_elements.fields.hidden',
 'fobi.contrib.plugins.form_elements.fields.input',
 'fobi.contrib.plugins.form_elements.fields.integer',
 'fobi.contrib.plugins.form_elements.fields.ip_address',
 'fobi.contrib.plugins.form_elements.fields.null_boolean',
 'fobi.contrib.plugins.form_elements.fields.password',
 'fobi.contrib.plugins.form_elements.fields.radio',
 'fobi.contrib.plugins.form_elements.fields.select',
 'fobi.contrib.plugins.form_elements.fields.select_model_object',
 'fobi.contrib.plugins.form_elements.fields.select_multiple',
 'fobi.contrib.plugins.form_elements.fields.select_multiple_model_objects',
 'fobi.contrib.plugins.form_elements.fields.slug',
 'fobi.contrib.plugins.form_elements.fields.text',
 'fobi.contrib.plugins.form_elements.fields.textarea',
 'fobi.contrib.plugins.form_elements.fields.time',
 'fobi.contrib.plugins.form_elements.fields.url',
 'fobi.contrib.plugins.form_elements.test.dummy',
 'fobi.contrib.plugins.form_elements.content.content_image',
 'fobi.contrib.plugins.form_elements.content.content_text',
 'fobi.contrib.plugins.form_elements.content.content_video',
 'fobi.contrib.plugins.form_handlers.db_store',
 'fobi.contrib.plugins.form_handlers.http_repost',
 'fobi.contrib.plugins.form_handlers.mail',
 'work.fobi_form_callbacks',
 'valuenetwork.valueaccounting',
 'valuenetwork.equipment',
 'valuenetwork.board',
 'valuenetwork.api',
 'account',
 'work']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'valuenetwork.login_required_middleware.LoginRequiredMiddleware',
 'account.middleware.LocaleMiddleware']

**Comment by bum2** [comment]
I think this error is resolved in last update of testocp (if it appears again, please complain). It is caused when a custom fobi form has not the DB Store handler (added in fobi editor) and a join-request is made.
So, it's mandatory to add always the DB Store handler before publishing the form, and also is mandatory that no fields (of the fobi custom form) are 'required'. Only some of the OCP account fields are required, and all the custom fields must be non-required nowadays (it fails if so, with this same error). 
Even if it happens or if is something wrong with a request 'fobi_data', the system doesn't crash with this error anymore, only a red 'ERROR' string is seen in the comments page of a join-request, and the coordinators join-requests table doesn't show the custom fields.
