### ISSUE TITLE
Browser blocks content in ssl enabled site

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#16]
We are plannig to give access only with https (ssl) protocol, for safety of information and logins.
When activating the ssl, the browser blocks contents because they are called with not ssl prot. For example, accessing to: (it's a self-signed cert, so security exception is needed in the browser)
https://testocp.freedomcoop.eu/accounting/projects
The browser is blocking these content:
```
http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css
http://code.jquery.com/ui/1.9.2/jquery-ui.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js
http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css
http://code.jquery.com/ui/1.9.2/jquery-ui.js
http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js
```
I think that to change in templates all the absolute url protocols is needed.

**Comment by XaviP** [comment]
Hey, I found an easy way to do it.
To find the occurrencies:
```
grep -r 'http://' valuenetwork/valuenetwork/templates/
grep -r 'http://' valuenetwork/work/templates/
```
To change the ocurrencies:
```
grep -rl 'http://' valuenetwork/valuenetwork/templates/ | xargs sed -i s@'http://'@'https://'@g
grep -rl 'http://' valuenetwork/work/templates/ | xargs sed -i s@'http://'@'https://'@g
```
Now it's working ok in https://testocp.freedomcoop.eu/accounting/projects
Please, check if you think this is correct and, if you're busy, I can make a pull request.

**Comment by bhaugen** [comment]
>  I can make a pull request.

Please do. Thank you, this is great!  And easier than I expected.
