### ISSUE TITLE
OCP invoice design

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#173]
[Pad](https://titanpad.com/freedomcoop-invoice-numbers)

Mario's original thoughts (from the pad):

Needs for the Invoice-Numbers:
- Accepted Self-employed members should be able to create an invoice-number by themselves for services they provide to a customer (“selling”)
- The unique number follows a certain structure: Year/Quarter/Invoice-Number in Quarter/Membership-Number (16/4/099/155)
- This number could be confirmed to use before having the possibility to take another number (to avoid gaps in the consecutive Invoice-Numbers)
- A (maybe downloadable) blueprint of an invoice should be provided as well, to have a standard and to avoid potential mistakes.
- The final invoice created by the member should be uploaded or send to the OCP/ GestioCI system linked to membership profile
- Further needs: store the bills from the self-employed members, linked to membership profile (discussion needed about the acceptance of those bills)

**Comment by fosterlynn** [comment]
Earlier discussion on GestioCI and OCP https://titanpad.com/DDjX2Ji5RC

**Comment by bhaugen** [comment]
Tentative invoice number proposal and questions:

Quoting Mario's notes:
> The unique number follows a certain structure: Year/Quarter/Invoice-Number in Quarter/Membership-Number (16/4/099/155)

* We can create a new page in OCP showing all the invoice numbers previously created by a user, with a form to create a new invoice number.
   * Should the year and quarter be filled in automatically from the system date, or should the user be able to enter them?
   * The form could have a selection box for the provider on the invoice with options for each of the agents that the user is associated with. In other words, the invoice could be for any of those agents, but no others. (Or should it be restricted to the user's own agent and groups that the user coordinates?) The Membership-Number section of the Invoice Number is the numeric id of that agent.
    * The sequence number will be filled in when the new invoice number is saved, by adding 1 to the previous sequence numbers in that quarter.
    * In Mario's notes, the sequence number is padded with a leading 0 so it has 3 digits. Is this required? And is it enough?
    * Should the member number be similarly padded so it is always the same number of digits? If so, how many digits should we allow?

**Comment by bhaugen** [comment]
Also, assuming that the quarter should be computed automatically from the system date or a date entered or selected by the user, should the quarter by computed by month, so that each quarter has the same number of months?

If by month, here is a simple python formula for computing the quarter from the month number:
```
>>> for month in range(1,13):
...     print (month-1)//3 + 1
... 
1
1
1
2
2
2
3
3
3
4
4
4
```

Does that seem correct?

**Comment by bhaugen** [comment]
Also, how much other information should OCP keep along with each invoice number?

I am assuming 
* the system date when the invoice number was created, 
* maybe an invoice date if we allow the user to enter or select it and it is different from the system date,
* the user who created it, and 
* the OCP member that it was created for. 

Anything else?

**Comment by bhaugen** [comment]
Decisions (from telegram):

* Year and quarter will be automatically filled in from the system date.
    * Quarters will be based on system date month, with 3 months in each quarter.
* Permissions for creating invoice numbers:
    * If a user is an member of freedomcoop, they will be able to create invoice numbers for themselves.
    * If they are a participant in a collective that is a collective member of freedomcoop, but they are not a member themselves, they will be able to create invoice numbers for the collective, but not for themselves.
    * In case they are both a member of freedomcoop themselves, and also associated with a collective that is a member of freedomcoop, they will be able to create invoice numbers either for themselves or for a collective that is a member.
* Those permissions also mean that a collective will want to see all of its invoice numbers, regardless of which user created them.
* Freedom coop admins must be able to create invoice numbers for any date, not just the system date.
    * They should also be able to see all invoice numbers from all members.

Let me know if I missed anything.

**Comment by bhaugen** [comment]
First draft pushed to master. Not connected to menus yet. When it gets connected, it will probably need more work.
If it gets deployed on testocp, it will be at
https://testocp.freedomcoop.eu/work/invoice-number/

**Comment by bhaugen** [comment]
For those who can read code, here's the method that determines which members you can invoice for:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L954

Seem correct? (Or if you can't understand the code, test it when it gets deployed to testocp. Or ask questions.)

**Comment by Holofractographic** [comment]
Hi! Im testing it but gives me this error: 

Page not found (404)
Request Method: 	GET
Request URL: 	https://testocp.freedomcoop.eu/work/invoice-number/

Using the URLconf defined in valuenetwork.urls, Django tried these URL patterns, in this order:

    ^$ [name='home']
    ^accounting/
    ^admin/
    ^account/
    ^notification/
    ^equipment/
    ^board/
    ^work/ ^my-dashboard/$ [name='my_dashboard']
    ^work/ ^non-process-logging/$ [name='non_process_logging']
    ^work/ ^work-timer/(?P<process_id>\d+)/(?P<commitment_id>\d+)/$ [name='work_timer']
    ^work/ ^process-logging/(?P<process_id>\d+)/$ [name='process_logging']
    ^work/ ^work-process-finished/(?P<process_id>\d+)/$ [name='work_process_finished']
    ^work/ ^my-history/$ [name='my_history']
    ^work/ ^work-home/$ [name='work_home']
    ^work/ ^save-timed-work-now/(?P<event_id>\d+)/$ [name='save_timed_work_now']
    ^work/ ^change-history-event/(?P<event_id>\d+)/$ [name='change_history_event']
    ^work/ ^map/$ [name='map']
    ^work/ ^project-work/$ [name='project_work']
    ^work/ ^profile/$ [name='profile']
    ^work/ ^change-personal-info/(?P<agent_id>\d+)/$ [name='change_personal_info']
    ^work/ ^upload-picture/(?P<agent_id>\d+)/$ [name='upload_picture']
    ^work/ ^update-skills/(?P<agent_id>\d+)/$ [name='update_skills']
    ^work/ ^add-worker-to-location/(?P<location_id>\d+)/(?P<agent_id>\d+)/$ [name='add_worker_to_location']
    ^work/ ^add-location-to-worker/(?P<agent_id>\d+)/$ [name='add_location_to_worker']
    ^work/ ^manage-faircoin-account/(?P<resource_id>\d+)/$ [name='manage_faircoin_account']
    ^work/ ^transfer-faircoins/(?P<resource_id>\d+)/$ [name='transfer_faircoins']
    ^work/ ^faircoin-history/(?P<resource_id>\d+)/$ [name='faircoin_history']
    ^work/ ^change-faircoin-account/(?P<resource_id>\d+)/$ [name='change_faircoin_account']
    ^work/ ^membership-discussion/(?P<membership_request_id>\d+)/$ [name='membership_discussion']
    ^work/ ^validate-faircoin-address-for-worker/$ [name='validate_faircoin_address_for_worker']
    ^work/ ^work-add-todo/$ [name='work_add_todo']
    ^work/ ^work-todo-done/(?P<todo_id>\d+)/$ [name='work_todo_done']
    ^work/ ^work-todo-time/$ [name='work_todo_time']
    ^work/ ^work-todo-description/$ [name='work_todo_description']
    ^work/ ^work-todo-decline/(?P<todo_id>\d+)/$ [name='work_todo_decline']
    ^work/ ^work-todo-mine/(?P<todo_id>\d+)/$ [name='work_todo_mine']
    ^work/ ^work-todo-change/(?P<todo_id>\d+)/$ [name='work_todo_change']
    ^work/ ^work-todo-delete/(?P<todo_id>\d+)/$ [name='work_todo_delete']
    ^work/ ^work-commit-to-task/(?P<commitment_id>\d+)/$ [name='work_commit_to_task']
    ^work/ ^work-delete-event/(?P<event_id>\d+)/$ [name='work_delete_event']
    ^work/ ^your-projects/$ [name='your_projects']
    ^work/ ^agent/(?P<agent_id>\d+)/$ [name='members_agent']
    ^work/ ^agent/(?P<agent_id>\d+)/join-requests/$ [name='join_requests']
    ^work/ ^my-tasks/$ [name='my_tasks']
    ^work/ ^take-new-tasks/$ [name='take_new_tasks']
    ^work/ ^home/$ [name='home']
    ^work/ ^create-your-project/$ [name='create_your_project']
    ^work/ ^change-your-project/(?P<agent_id>\d+)/$ [name='change_your_project']
    ^work/ ^project-feedback/(?P<agent_id>\d+)/(?P<join_request_id>\d+)/$ [name='project_feedback']
    ^work/ ^joinaproject/(?P<agent_id>\d+)/(?P<join_request_id>\d+)/$ [name='joinaproject']
    ^work/ ^agent/(?P<agent_id>\d+)/project_joinform/$ [name='project_joinform']
    ^work/ ^join-project/(?P<project_id>\d+)/$ [name='join_project']
    ^work/ ^connect-agent-to-join-request/(?P<agent_id>\d+)/(?P<join_request_id>\d+)/$ [name='connect_agent_to_join_request']
    ^work/ ^accept-request/(?P<join_request_id>\d+)/$ [name='accept_request']
    ^work/ ^decline-request/(?P<join_request_id>\d+)/$ [name='decline_request']
    ^work/ ^undecline-request/(?P<join_request_id>\d+)/$ [name='undecline_request']
    ^work/ ^delete-request/(?P<join_request_id>\d+)/$ [name='delete_request']
    ^work/ ^create-ocp-acount/(?P<join_request_id>\d+)/$ [name='create_account_for_join_request']
    ^work/ ^comments/$ [name='comments']
    ^work/ ^share-payment/(?P<agent_id>\d+)/$ [name='share_payment']
    ^work/ ^validate-nick/$ [name='validate_nick']
    ^work/ ^validate-username/$ [name='validate_username']
    ^api/
    ^comments/
    ^membership/$ [name='membership_request']
    ^membershipthanks/$ [name='membership_thanks']
    ^captcha/
    ^i18n/
    ^robots.txt$
    ^joinaproject/(?P<form_slug>.+)/$ [name='joinaproject_request']
    ^joinaproject-thanks/$ [name='joinaproject_thanks']
    ^fobi/
    ^fobi/
    ^fobi/plugins/form-handlers/db-store/
    ^site\_media\/media\/(?P<path>.*)$
    ^site\_media\/static\/(?P<path>.*)$

The current URL, work/invoice-number/, didn't match any of these.

Im logged as admin

**Comment by bhaugen** [comment]
@Holofractographic sorry,  I don't think it's been deployed to testocp yet.

**Comment by Holofractographic** [comment]
Ahh ok sorry too fast!!

**Comment by bhaugen** [comment]
Might be that nobody is doing server admin these days...

**Comment by fosterlynn** [comment]
Closing, a new Freedom COop invoicing app is being done in Odoo.
