### ISSUE TITLE
Error when de-assigning use-cases from the 'process-patterns' admin page.

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#188]
in https://testocp.freedomcoop.eu/admin/valueaccounting/processpattern/ when editing a pattern and trying to delete the relation with a 'use-case', choosing the empty option in the dropdown (------), it fails when saving, giving the error:

> 'NoneType' object has no attribute 'name'
> Exception Location: 	/home/ocp/app/valuenetwork/valuenetwork/valueaccounting/models.py in use_case_list, line 3031

**Comment by bum2** [comment]
if correctly checked the delete checkbox and save, it works clean with no error...

**Comment by fosterlynn** [comment]
In general, patterns should only be edited in the app itself, there are a lot of data connections that admin can't take care of.  So this may be a bug, but if so, I don't see it worth fixing.

To change the use case for an existing pattern: add the pattern to the new use case (right side of screen, choose an existing pattern); then you can delete it from the original, or not (left side of screen).

**Comment by fosterlynn** [comment]
OK to close?
