### ISSUE TITLE
OCP FairCoin features

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#19]
## All FairCoin objects are wrapped in OCP objects

* A FairCoin address is wrapped in an OCP EconomicResource
    * All of these FairCoin addresses belong to the same FairCoin wallet on the OCP server.
* EconomicAgents (such as Freedom Coop workers) may own these FairCoin address resources.
    * When a user is created for an EconomicAgent by a FreedomCoop administrator, a FairCoin address request is created which will be processed by the cron job explained below.
    * FreedomCoop administrators can also request FairCoin addresses for other agents like projects which do not have login user ids.
* FairCoin transactions are wrapped in OCP EconomicEvents.
    * A Freedom Coop agent with a FairCoin address can create OCP EconomicEvents to send FairCoins to any other FairCoin address.
    * These events will be processed by the cron job below to create and broadcast FairCoin transactions.
* Each FairCoin address resource will have a history of all of the events that have happened to it through OCP. Each event will show its current FairCoin transaction status, and if the transaction has been broadcast, will also present a link to the transaction on the Chain.
* When a value equation distributes FairCoins, if any agent who will receive some of the coins does not have a FairCoin address, an address request will be created, and the cron job will process the address requests before creating FairCoin transactions.
    
## FairCoin addresses and transactions do not get created directly by Django.

* Only the wrapper EconomicResources and EconomicEvents get created with the necessary FairCoin information.
* A cron job creates the FairCoin addresses and broadcasts the FairCoin transactions to the network.
* Every time the wrapper EconomicEvent is used for anything, it checks the transaction state.

**Comment by bhaugen** [comment]
@XaviP - please check this out for understanding and accuracy. If you think anything is unclear or missing, let's fix it. Once it is clear and understandable, it can be a source for some Freedom Coop administrator documentation.

Also, we need to test all of this on your current server and also on whatever ends up as the production server for Freedom Coop. Let me know what you want me to do for this testing.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
