### ISSUE TITLE
Bug in faircoin address code? Need to rebuild wallet.

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#193]
In telegram, @santiddt says,
> but it seems that an ocp script has been created too much address, more than 10.000. I can setup a fai2ban rule in the test site to cacht the error, but the wallet should be rebuilt and regenerate only the address needed

**Comment by santiky** [comment]
Hi,
we need to look in the log files in the production server. Perhaps is a loop in the ocp code retransmiting several transactions.

**Comment by bhaugen** [comment]
I think this is the only place where faircoin addresses and transactions are handled in OCP now:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/process_faircoin_requests.py
which calls
https://github.com/FreedomCoop/valuenetwork/blob/master/faircoin_nrp/electrum_fair_nrp.py

**Comment by bhaugen** [comment]
Here are the valid faircoin addresses in prod ocp:
https://ocp.freedomcoop.eu/accounting/resource-type/26/
There are 85 of them.

Here in testocp:
https://testocp.freedomcoop.eu/accounting/resource-type/26/
48 of those.

**Comment by bhaugen** [comment]
@santiky I can't remember, is it possible to delete faircoin addresses from the wallet without causing major side-effects? If so, it should be possible to do a script to run on the server that deletes the faircoin addresses that are not used by anybody in the system.

**Comment by bhaugen** [comment]
@santiky says in telegram,
> the wallet has generated 10.000 addresses, it seems like the ocp is calling new_faircoin_address for the user "Piluka" but does not catch the answer. Each time a new address is generated

**Comment by bhaugen** [comment]
More:
> 2016-11-29 21:23:02 - CRITICAL - an exception occurred in creating a FairCoin address: (-32603, u'Server error:   File "/home/ocp/webapp/valuenetwork/faircoin_nrp/daemon/daemon.py", line 181, in new_fair_address | UnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\xed\' in position 1: ordinal not in range(128)')

**Comment by bhaugen** [comment]
> it seem is falling in the line 181             wallet.set_label(new_address, entity + ': ' + str(entity_id))

**Comment by santiky** [comment]
can i have a file with the valid address? I have a file with all address and i can filter out and delete the unvalid.

**Comment by bhaugen** [comment]
I could try changing the code that sends the faircoin address request. It is now
```
address = efn.new_fair_address(
            entity_id = agent.nick, 
            entity = agent.agent_type.name,
            )
```
I could try something like 
```
address = efn.new_fair_address(
            entity_id = agent.nick.encode('ascii','ignore'), 
            entity = agent.agent_type.name,
            )
```
 I hesitate because when I changed the unicode u'P\xedlikum' to somethign that would work in ascii, I thought it would solve the problem and Pilar would get a faircoin address.
But it just solved the ascii exception, did not result in a faircoin address.

**Comment by bhaugen** [comment]
> can i have a file with the valid address?

I'll see if I can create one and respond here.

**Comment by santiky** [comment]
don't worry, already done exporting from the database

**Comment by bhaugen** [comment]
Ok, good, thanks

**Comment by bhaugen** [comment]
By the way, field in valueaccount_economicresource is called digital_currency_address - but you probably figured that out already.
