### ISSUE TITLE
Faircoin requests keep trying forever after failing

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#194]
They should either fail once or at least limit their retries.

Failing once will be easier than limited retries, which will require a database change. But failing once will also need some kind of notification to be friendly, and then maybe some admin action if the failure was some temporary condition and a retry will be ok.

I'm labeling this as a bug, but it will also need some discussion.

This is related to https://github.com/FreedomCoop/valuenetwork/issues/193

**Comment by bhaugen** [comment]
So far, this has come up in faircoin address requests. 

The new_fair_address function should be changed to either succeed completely and send a valid address back to OCP, or fail completely (that is, not leave a bogus new address in the wallet).

Also, if the faircoin address comes back as the string "ERROR", which it can do, that response should be trapped and faircoin admins should be notified.

See also https://github.com/FreedomCoop/valuenetwork/issues/197

**Comment by bum2** [comment]
I saw the address of Pílikum is 'ERROR'... i've deleted the resource (and agent-resource-role record) in prod-ocp and request a new address... now she has a valid fairaddress.
Hopfully it don't happen again: I've added a check for this error string in def create_address_for_agent at valueaccounting/process_faircoin_requests.py and now returns None...

**Comment by bum2** [comment]
reopen if needed
