### ISSUE TITLE
How to test faircoin functions locally

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#199]
Spinning off [this comment](https://github.com/FreedomCoop/valuenetwork/issues/197#issuecomment-267311586) by @bum2 
> Another related thing pending to solve is: When we the devs copy the db in testocp to our local environments, and we also run our own electrum-fair local wallets, then the fairaddresses recorded in the db are not addresses of our local wallet (they're addresses of the testocp wallet)... I think is good at least to add a check when entering the account page to see if the recorded address pertains or not to the connected local wallet, and warn clearly about that. Perhaps just this now, and maybe a button to delete or recreate the fair address in a future... it only affects us the devs, but can lead to errors, isn't it?

Setting up to test faircoin functions in a local dev environment is a problem. I'll look at this when I get my own dev environment set up to test this weekend, and post more observations and possibly ideas in this issue.

**Comment by bhaugen** [comment]
Here's what I have found so far:
* @XaviP 's doc [/install_ocp_debian_apache_ssl](https://github.com/FreedomCoop/valuenetwork/blob/master/docs/install_ocp_debian_apache_ssl.rst) is very helpful. Especially the parts about copying the daemon sample files and setting up the daemon.
* This after doing all the stuff in [install.txt](https://github.com/FreedomCoop/valuenetwork/blob/master/docs/install.txt).
    * We should add the instructions for installing electrum-fair and setting up the daemon.
    * However, to import electrum_fair in python in your virtualenv, you need to rename or delete
/lib/python2.7/no-global-site-packages.txt
        * this is because electrum-fair is a global, and no-global-site-packages does not use globals.

But here's my current problem: my local wallet was created with some early test data. After that, I started to test with databases copied from testocp, so I could reproduce bugs found there. But the faircoin addresses in testocp do not match those in my local wallet. 

I just spent an hour looking and couldn't even find an old database that matches my local wallet.

So my choices seem to be:
* create a new local wallet and create a new test database that matches it, or
* create a new test database and duplicate the faircoin addresses from the current local wallet, or
* get a copy of the wallet from testocp so I can continue to reproduce bugs.

Would that last option be a bad idea? Would it be possible? What would the effect of testing locally with the same wallet as testocp? What would the side-effects be?

@santiky - got any advice?

**Comment by bum2** [comment]
I think is not good to have the same wallet in two places (local and testocp) or if its possible at all. 
We can try to run the local envs using the online testocp wallet, but also not seems a good solution.
I have the same issue about testocp fair addresses into local env (not matching local wallet), and the solution I think is best is to do a script or a update function that changes all the fair addresses in a ocp instance and sets a local wallet address to every account owner, becoming then a real local working environment.
One way to do it is also one by one: when a fairaddress is requested to ocp it can check if the address pertains the related wallet or not, and if not recreate the address from the real linked wallet, giving and storing a new address for the agent. That checking maybe is not fast or creates innecessary overhead querying the wallet, so, a 'check all fair-addresses' function is better, running once at startup or at migrate time...

**Comment by bhaugen** [comment]
I'll start by changing enough fair addresses in my local db by copy-pasta, just enough for what I want to test, at first. Might try a script. But I am a bit confused on some of the addresses in my local wallet. They don't make sense to me. Don't know how they got created. So I might just watch some new addresses get created for awhile and see if I can understand better. That would be, before I do any mass changes.
