### ISSUE TITLE
How FairCoins will fit into NRP/OCP

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#2]
## EconomicAgent and EconomicResource

You might want to look at the [core model](https://github.com/valnet/valuenetwork/wiki/Core) for background to this discussion.

People and groups are EconomicAgents. EconomicAgents can own EconomicResources. A FairCoin address is an EconomicResource, which may hold some FairCoins. 

This will require adding an optional faircoin_address field to the EconomicResource class. This will be an FCAddressField based on the [BCAddressField](https://bitcointalk.org/index.php?topic=1026.msg12557#msg12557).

When an EconomicAgent is first created, we will create a FairCoin address EconomicResource owned by that agent. We will call the electrum_fair_nrp.new_fair_address() method to create the address in the appropriate wallet.

_(We understand at this stage of the design discussions that all FairCoin addresses for all Freedom Coop workers will live in the same wallet. **Question**: will that be true for all agents? For example, projects and nodes?)_

The EconomicAgent class will have a new method that will return its FairCoin address.

The agent and FC worker pages will have a link to a new page showing their FairCoin address with the address's balance (calling electrum_fair_nrp.get_address_balance(address) ) and transaction history (calling electrum_fair_nrp.address_history_info(address) ), and a form to send some coins to another address.

We have already decided that the change address for transactions will be the same address.

## EconomicEvent

A transfer of EconomicResources from one EconomicAgent to another is an EconomicEvent. Events will transfer FairCoins when income is distributed to Fair Coop workers or other Fair Coop agents, and when Fair Coop workers or other agents transfer coins from their FC address to other FC addresses.

EconomicEvents will have an optional faircoin_transaction field that will be filled if the event is transferring FairCoins. In that case, we will call the  electrum_fair_nrp.make_transaction_from_address(address) method. This method will need to be changed to return the transaction id, to fill that new field, which can be used as needed to retrieve the transaction.

**Comment by fosterlynn** [comment]
Suggest: Instead of FCAddressField, we make a more generic address field, something like CurrencyAddressField or CurrencyAddress.  Then if we need to support other currencies, we can see if this is sufficient, or if we need another field to say what currency it is.  Might be able to use the Unit field for that.

**Comment by XaviP** [comment]
Hey, just a fast reading and some notes:
- I think we'll only manage faircoin wallet, so I don't know if there's sense of planning in another cryptocurrecies.
- Good news: The FCAddressField can be simplified as you can call electrum_fair_nrp.is_valid(), instead of get_bcaddress_version(), in the original code. So, the code from 'import math' is no more needed.
Thanks for the document!

**Comment by XaviP** [comment]
Hi, the pull request with the change in file name has been approved, so now it's called electrum_fair_nrp.py

**Comment by XaviP** [comment]
- Renamed faircoin-nrp directory to faircoin_nrp
- Created __init__.py file.
- make_transaction_from_address() returns transaction id (tx_hash)

**Comment by bhaugen** [comment]
@XaviP - thanks for including the tx_hash return.

**Comment by bhaugen** [comment]
Here's how I am (experimentally) integrating: encapsulated all the interactions with faircoin_nrp in a new valuenetwork.valueaccounting.faircoin_utils.py, which looks like this, so far (see questions below):
```
import faircoin_nrp.electrum_fair_nrp as efn

#todo faircoin: how to handle failures?

def init_electrum_fair():
    try:
        if not efn.network:
            efn.init()
        else:
            if not efn.network.is_connected():
                efn.init()
    except:
        #handle failure better here
        msg = "Can not init Electrum Network. Exiting."
        assert False, msg
        
def create_address_for_agent(agent):
    init_electrum_fair()
    wallet = efn.wallet
    address = None
    address = efn.new_fair_address(
        entity_id = agent.nick, 
        entity = agent.agent_type.name,
        )
    return address
    
def send_faircoins(address_origin, address_end, amount):
    init_electrum_fair()
    tx = efn.make_transaction_from_address(address_origin, address_end, amount)
    return tx
```
**Questions:**

I know that is incomplete, but:

* Does that roughtly ok? Got suggestions for improvement?
* How would you handle failures?
    * Failure of init()?
    * Failure of create_address_for_agent()?
    * Failure of send_faircoins()?
    * Failure of transaction confirmation?

**Comment by XaviP** [comment]
I think other option could be call init() on start the django project because can take some time to start, and if the wallet has not been been installed, django can simply die, not start. I've been looking where can be the best place in a django project, but people doesn't agree which is the best place: settings.py, __init__.py, urls.py ...
http://stackoverflow.com/questions/1797046/correct-place-to-put-extra-startup-code-in-django

About handle failures, maybe it can help thinking as starting an email server and sending emails, or something like that. How do you handle failures of any external service?

Depends on the service can be handled different:
- if create_address_for_agent() fails, it cannot be created an user or whatever it's been created. Send alert to admin.
- about send_faircoins(), I think it's needed a control about if the transaction has been broadcast. State of PENDING.

Hope it helps.

**Comment by bhaugen** [comment]
The django project is basically always running. It's started when Apache starts and calls mod_wsgi to start NRP. I put the start in faircoin_utils because it will get started the first time somebody wants to use it and then keep running (as far as I can tell from experiments). So it will only happen once, except when it dies.

If that does not work well, I would favor __init__.py.

**Comment by bhaugen** [comment]
Re notifications of failures: we do that now. Django sends 500's and 404's automatically. We might want a special notice for electrum-fair failures, but that will be easy, too. Will need to figure out what email address to send them to for freedom coop, that's all.

**Comment by bhaugen** [comment]
@XaviP what max_length for the faircoin address database field?

And how about for the tx_hash?

I'll add both of those and a fair_coin_tx_state field soon. Let us know if you can think of others to add, or at least think about.

**Comment by XaviP** [comment]
You can add fair_coin_tx_state with several states for use in the possible future (thinking about a confirmed state if it's needed later) NEW, PENDENT, BROADCASTED, CONFIRMED or something like that.
I think the faircoin address is always between 26-35 chars. Always begins with f
I'm not sure if the tx_hash is fixed. I'll search some info.

**Comment by XaviP** [comment]
I think a tx_hash is always 64 chars long.

**Comment by bhaugen** [comment]
What I found for Bitcoin is address = 34 chars, tx_hash = 32.

But I could make both 64 just for good measure. Won't hurt.

**Comment by XaviP** [comment]
Bitcoin max long 65:
https://en.bitcoin.it/wiki/Address

In the faircoin block explorer tx hash are 64 long
https://chain.fair-coin.org/tx/bc67dbe479ffbed1dca61f4ec1a47b1c2d438de27b0def53c7b4b300afe303f5

But we can make some tests, or just give some long more.

**Comment by bhaugen** [comment]
I'll go 96. Headroom!

**Comment by XaviP** [comment]
https://github.com/Punto0/faircoin_nrp/pull/13

**Comment by bhaugen** [comment]
@XaviP 
> You can add fair_coin_tx_state with several states for use in the possible future (thinking about a confirmed state if it's needed later) NEW, PENDENT, BROADCASTED, CONFIRMED

What's the diff between NEW and PENDENT? When does it become BROADCASTED?

**Comment by XaviP** [comment]
Sorry, I mean PENDING not pendent XD
And yes, probably no difference with NEW. It depends on how you plan the steps of states on a tx.
Broadcasted can be when you recive the tx_hash from make_transaction_from_address(). This means that the tx has been broadcasted to the faircoin network, but not yet confirmed.
Confirmed maybe can be used in the future.

**Comment by bhaugen** [comment]
Got it. Might get rid of new once I get this stuff tested.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
