### ISSUE TITLE
Error in validate_faircoin_address_for_worker

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#202]
Error message:
```
Internal Server Error: /work/validate-faircoin-address-for-worker/
Traceback (most recent call last):
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/ocp/webapp/valuenetwork/work/views.py", line 1150, in validate_faircoin_address_for_worker
    toagent = data["to_agent"]
  File "/home/ocp/webapp/env/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'to_agent'"
```
The problem is here:
```
def validate_faircoin_address_for_worker(request):
    #import pdb; pdb.set_trace()
    from valuenetwork.valueaccounting.faircoin_utils import is_valid
    data = request.GET
    address = data["to_address"]
    answer = is_valid(address)
    if not answer:
        toagent = data["to_agent"] # this method has no GET parameter called "to_agent".
```

Introduced by this commit:
https://github.com/FreedomCoop/valuenetwork/commit/cb53ad0896b7b5fe20858ca8a64b1f74616365a0

**Comment by bhaugen** [comment]
@bum2 I looked through the whole logic of sending faircoins from the work/manage-faircoin-account/ page. Mostly looked ok, but I couldn't test it all the way through yet.
I did see one possible hole: in valueaccounting.models.related_all_contexts_queryset you are not filtering out agents with no faircoin address.
And one possible improvement, as we discussed, to trim leading and trailing blanks, both in validate_faircoin_address_for_worker and in SendFairCoinsForm.clean. You can do that with the python strip() function, like:
```
to_address = to_address.strip()
```

**Comment by bum2** [comment]
You are true about the possible hole, it just returns nothing (no sending, no error) when that happens. Now i've added more filtering to not even show the related agents without fairaddress, and also added the strip method in that two places...

The super weird thing that is puzzling my mind is: I was doing test faircoin sendings from Bumbum user at prod ocp, and when sending fairs from Catalonia node to Bumbum the fairs go to 'Bilbao node' (¿?¿?), both by address or by agent... I've seen that the fairaddress of the Bilbao node is exactly the same as mine, so it gets the other agent as a destinaton (creating wrong transfers and events)... For me, it's still is a mystery why it can be or how to produce such a situation... i've repaired asap this prodution issue, deleting and requesting again a fairaddress for Bilbao node... also showing the address at https://ocp.freedomcoop.eu/accounting/resource-type/26/ list to check for duplicates (none now)... i'm digging more deep in the faircoin wallet code to understand how a duplicate address can be produced or assigned to 2 agents...

**Comment by bum2** [comment]
I've added a check to see if a fairaddress has been assigned to a EconomicResource before assigning to another resource or user. The new address creation will now fail and a critical message is logged in the logger. Its at https://github.com/FreedomCoop/valuenetwork/commit/1f777ca751046f18ad58a4ae41b702e4eeac81be
The fix is difficult to test and so now in prod-ocp, hopfully preventing this weird case if it happens again...

**Comment by bhaugen** [comment]
Thanks for diggin into this stuff, @bum2 !

**Comment by bum2** [comment]
Reopen if happens again...
