### ISSUE TITLE
No images showing from site_media

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#204]
The uploaded photos on profiles or projects are not showing up in prod-ocp (but shows in testocp). 
The configuration in local_settings.py and the folder permissions seem ok... I have also added more directory permissions for the 'site_media' folder at the apache2.conf file but still not resolved.

I'm not sure what's really the problem, but is a very important bug to solve asap... perhaps @XaviP can help us in this one? he will know other possible reasons...

**Comment by bhaugen** [comment]
Examole: this shows up fine in testocp:
https://testocp.freedomcoop.eu/site_media/media/photos/what_is_it.JPG.128x128_q85.jpg

This one in ocp is a 404:
https://ocp.freedomcoop.eu/site_media/media/photos/what_is_it.JPG.128x128_q85.jpg

**Comment by XaviP** [comment]
Hi, solved by adding this to virtual host conf:
```
Alias /site_media/media/ /home/ocp/webapp/valuenetwork/valuenetwork/site_media/media/
```
What I don't understand is how is working in testocp :-)

**Comment by bhaugen** [comment]
> What I don't understand is how is working in testocp :-)

Do you remember doing that django collectstatic command on either server?

**Comment by XaviP** [comment]
Not doing django collectstatic since first installation. Manually copying any static file in static dir when a git clone includes any static file. But now I don't know who is doing it, or what is doing.

**Comment by bum2** [comment]
Thanks a lot brother @XaviP ! ... yes I'm doing the manual copy of static files on every deployment...
