### ISSUE TITLE
Faircoins not showing up in balance at prod!

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#210]
This is from few days ago, because it was working good: When you send fairs from an external wallet to an ocp account, the balance don't show them, even if they are totally confirmed in the chain.

there are some 'critical' traces at `faircoins.log` (not shown for privacy) and also at `emit_notices.log` every minute is this:

> —----------------------------------------------------------------------
> acquiring lock...
> lock already in place. quitting.
> releasing lock...
> Traceback (most recent call last):
>   File "manage.py", line 9, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
>     output = self.handle(*args, **options)
>   File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/notification/management/commands/emit_notices.py", line 14, in handle
>     send_all(*args)
>   File "/home/ocp/webapp/env/local/lib/python2.7/site-packages/notification/engine.py", line 92, in send_all
>     lock.release()
> AttributeError: 'NoneType' object has no attribute 'release'

so a missing "lock" object (NoneType) is trying to 'release' ...

The crontabs are very different in testocp and prod ... any help around with this?

**Comment by XaviP** [comment]
> The crontabs are very different in testocp and prod ...

There are crontabs in user _ocp_ and in user _root_ too. In prodocp everything is ready to start the daemon when the system is rebooted, not in testocp.

**Comment by bhaugen** [comment]
I checked in shell_plus in prod ocp.

The balance you see in OCP is the same as I get from ```faircoin_nrp.electrum_fair_nrp.get_address_balance(address)```.

And it is different from the balance on the chain for the same address.

This seems to be the code that does it, in electrum-fair.lib.wallet.py:
```
    # return the balance of a bitcoin address: confirmed and matured, unconfirmed, unmatured
    def get_addr_balance(self, address):
        received, sent = self.get_addr_io(address)
        c = u = x = 0
        for txo, (tx_height, v, is_cb) in received.items():
            if is_cb and tx_height + COINBASE_MATURITY > self.get_local_height():
                x += v
            elif tx_height > 0:
                c += v
            else:
                u += v
            if txo in sent:
                if sent[txo] > 0:
                    c -= v
                else:
                    u -= v
        return c, u, x
```

**Comment by bhaugen** [comment]
Since it looks like Santi fixed the balance problem, is this issue ready to be closed?
