### ISSUE TITLE
Add description to faircoin transactions in OCP

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#212]
Faircoin transactions in OCP are EconomicEvents, which already has a description field. The easiest way to do this is to put that description field in the user interface where needed, which I think would be on the form to create a transaction, and on the faircoin address event history.

**Comment by bhaugen** [comment]
Also, make it possible to edit the descriptions in older transactions.

**Comment by bum2** [comment]
thanks @bhaugen ! if you can take the issue (to do in master branch), marvelous, but if you can't take it, tell me and I will do it asap...

**Comment by bhaugen** [comment]
I won't be able to get to it until Wednesday earliest. I think could be finished by weekend. If you can do it faster, take it. Otherwise I'll assign it to myself on Wednesday.

**Comment by bum2** [comment]
ok thanks again! i'll give it a try and see what happens...

**Comment by bum2** [comment]
done, and seems like working in prod... now we have the jeditable jquery to make inline editions where we need...
