### ISSUE TITLE
Looks like context_agent is not passed to exchanges_all and so not to exchange_logging

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#225]
When I go from https://testocp.freedomcoop.eu/work/agent/96/
to https://testocp.freedomcoop.eu/work/agent/96/exchanges/
and then to https://testocp.freedomcoop.eu/work/agent/96/exchange-logging-work/0/130/
the exchange_logging does not know the context_agent because it was not passed along to exchanges_all.

I am not sure this is a problem, just an observation as of this stage of testing.

**Comment by bum2** [comment]
the context agent is part of the url data, so is defined when calling the view and everything behaves as related that main context agent or project... you can even place the id of your user-agent and see your 'profile' through the same project window... what i want to do one day is to merge the profile page with this agent page, so it shows all entities details through the same page (members_agent.html). That means porting the skills part to this 'project' page, so there can be defined skills of the project too (perhaps only related real user members).

**Comment by bhaugen** [comment]
But the context_agent field is not being passed from this view:
https://github.com/FreedomCoop/valuenetwork/blob/exchanges/work/views.py#L2148

It would need to be in the context variables here: (which it's not)
https://github.com/FreedomCoop/valuenetwork/blob/exchanges/work/views.py#L2958

That's why it does not appear in the url, here:
https://github.com/FreedomCoop/valuenetwork/blob/exchanges/work/templates/work/exchanges_all.html#L708
```
<a href="{% url "exchange_logging_work" context_agent_id=x.context_agent.id 
```
So it is 0 in this URL:
https://testocp.freedomcoop.eu/work/agent/96/exchange-logging-work/0/130/

**Comment by bum2** [comment]
the context_agent is passed to the view from the beginning, passed to every form, and also to the template, but the parameter is called 'project' (=agent)... is the first number in the url... i think will be good to rename all that to 'context_agent' so it gives not confusions.... sorry for that, i can't remember the reasons, but i'll add to the todo list this renaming issue...

**Comment by bhaugen** [comment]
The template above is clearly expecting context_agent. Whether you change the template or the parameter  in this case is up to you. But it might be better to be consistent.

**Comment by bum2** [comment]
renamed 'project' to 'context_agent' in exchange_all template...  reopen the issue if needed
