### ISSUE TITLE
Cooperativist Society & Artist Cooperative needs

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#245]
Some needs identified by these users:
- Tasks with file attachment.
- Task adopted by several people. They decide how the distribution will be.
- Distribute by percentage of hours.
- A skill entered by an user of the project can be used as a type of task.

**Comment by fosterlynn** [comment]
Great @XaviP .

Seems to me that the last 3 are already covered in process logging and distributions.  But we should probably work it through in an actual example.

**Comment by fosterlynn** [comment]
>Seems to me that the last 3 are already covered in process logging and distributions. But we should probably work it through in an actual example.

Process logging is probably commented out in the current version of the work app though because exchanges is merged in.  And distributions have not yet made it to the work app.

**Comment by XaviP** [comment]
The code in production ocp is not already updated with the merge of exchanges, because some problems. So, I hope in second part of the workshop (thursday morning) it will be ready. In the meantime, it can be checked in testocp, if desired.

**Comment by bhaugen** [comment]
The easiest way to attach files now is if you can put them somewhere with an URL and just add the web address to the task description. It should be clickable. If not, it's a bug, and easily fixable.

Attaching files by upload is also doable, but would take some work and a new field. But not a lot of work.

**Comment by fosterlynn** [comment]
>The code in production ocp is not updated yet with the merge of exchanges, because some problems. So, I hope in second part of the workshop (thursday morning) it will be ready. In the meantime, it can be checked in testocp, if desired.

No I meant the opposite @XaviP .  You will only find the process logging in the work app *before* exchanges is merged in.  The exchanges branch commented all of that out because it is not ready when overlaid with the General App.  So if you want to do that function, you need the non-GA version.

Do you want to try it together before Thursday morning session?  I'd be happy to help you walk through it if you like.

**Comment by XaviP** [comment]
Thanks @fosterlynn, but my main concern until Thursday is to repair ocp production site. It's a mess of half migrations and db incoherencies. I will keep informed by telegram.

**Comment by fosterlynn** [comment]
Thanks @XaviP and best of luck!!

If you get the exchanges branch into the production site before Thursday, then you could always train or experiment on the admin app for process logging, since it will disappear from the work app at that point.

**Comment by fosterlynn** [comment]
Closing, doesn't seem relevant now.
