### ISSUE TITLE
Workflows in case of faircoin wallet issue

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#249]
- Check the logs:
```
sudo /etc/init.d/daemon_service status
electrum-fair daemon status
vim ~/.electrum-fair/daemon.log #daemon wallet log
vim [installation dir]/valuenetwork/faircoins.log #ocp faircoin log
vim [installation dir]/valuenetwork/faircoin_nrp/daemon/daemon.log #daemon_service log
```
- In case you need to check number of addresses in the wallet:
```
electrum-fair listaddresses | wc -l
```
- In case you need to check if db addresses are in the wallet and which deterministic order they have:
```
electrum-fair listaddresses > wallet_addresses.txt
echo "select digital_currency_address from valueaccounting_economicresource;" | psql ocpdb > db_addresses.txt
```
and compare both lists. Possible howto:
```
vim wallet_addresses.txt
```
Add to the top:
```
# -*- coding: utf-8 -*-
import sys

sys.stderr.write("Checking addresses\n")
wallet_addresses =
```
Add to the bottom:
```
total_addresses = 0
total_not_in_db_addresses = 0
height_addresses = []

for line in open('db_addresses.txt'):
    total_addresses += 1 
    line = str(line).strip()
    if line not in wallet_addresses:
        sys.stderr.write(line + "\n")
        total_not_in_db_addresses += 1
    else:
        height_addresses.append(wallet_addresses.index(line))  

sys.stderr.write("\n-------------\nTotal addresses: " + str(total_addresses) + "\nNOT in wallet: " + str(total_not_in_db_addresses) + "\n-------------\n" + str(height_addresses) + "\n\n")
```
Rename file from .txt to .py, and run the script: `python wallet_addresses.py`
This will give db addresses not in wallet, and the deterministic order in wallet of the db addresses.

- In case you need to rebuild the wallet:
0. Put a candle to your favorite sysadmin god ;-)
1. Stop the service
2. Rename the wallet for backup (it's in ~/electrum-fair/wallets/)
3. Start the service (this creates an empty wallet)
4. There's a script called `gen_address.sh` which generates 500 addresses Change the number to your needs.

- If you need to know the addresses in the db:
```
$ echo "select digital_currency_address from valueaccounting_economicresource;" | psql [db name] | sed '/^\s*$/d'
```
or
```
$ python manage.py shell_plus
>>> fas = EconomicResource.objects.filter(digital_currency_address__isnull=False)
>>> addresses = fas.values_list('digital_currency_address', flat=True)
```

**Comment by santiky** [comment]
step 2 is more conservative renaming the file instead deleting it.
step 5 it's not working (i do not know why wallet.add_address is doing nothing...). There are another script called gen_address.sh wich generates 500 addresses, it can be needed run several times depending on the number of addresses registered. This makes unneeded step 4.

**Comment by XaviP** [comment]
Edited the first comment of this issue to match the real workflow.

**Comment by santiky** [comment]
We should make a new wallet and import the private keys for the addresses in database.
Freezing the adresses it's not working.
Creating new address will generate more than 10.000 address (there are some address in db upper this limit).
Add address is doing nothing.

**Comment by bhaugen** [comment]
@santiky that seems pretty bad. Any idea why this set of problems is happening? What are we doing wrong?

**Comment by XaviP** [comment]
> We should make a new wallet and import the private keys for the addresses in database.

This way the seed will have no use anymore, we will have to backup the entire wallet often because it won't be possible to restore the wallet from seed, right?

**Comment by XaviP** [comment]
This content is moved to wiki:
https://github.com/FreedomCoop/valuenetwork/wiki/Sysadmin-workflows
and in a new issue with the remaining TODO's:
https://github.com/FreedomCoop/valuenetwork/issues/270
