### ISSUE TITLE
upgrading from 1.6 to 1.7

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#25]
See [Upgrading django from 1.4 to 1.6](https://github.com/FreedomCoop/valuenetwork/issues/22) for previous upgrades.
Some docs:
https://docs.djangoproject.com/en/1.7/releases/1.7/
https://www.seedinvest.com/labs/backend/upgrading-from-django-1-4-to-django-1-7

- requirements.txt: changed to django 1.7 and removed south
- settings: removed south from INSTALLED_APPS
- changed *get_query_set* to *get_queryset* in valuenetwork/valueaccounting/models.py:
```
grep -r 'get_query_set' ./
grep -rl 'get_query_set' ./ | xargs sed -i s@'get_query_set'@'get_queryset'@g
```
- changed *from south.signals* to *from django.db.models.signals*:
```
grep -r "from south.signals" ./
grep -lr "from south.signals import post_migrate" ./ | xargs sed -i s@'from south.signals import post_migrate'@'from django.db.models.signals import post_migrate'@g
```
- From django docs:

> As part of the System check framework, fields, models, and model managers all implement a check() method that is registered with the check framework. If you have an existing method called check() on one of these objects, you will need to rename it.

So search with *grep -r 'check(' ./ | grep .py* the ocurrences of check function (2), and change the name to *check_in_signupcode*

- In valueaccounting/models.py, removed the app argument in methods: *create_agent_types*, *create_agent_association_types*, *create_use_cases*, *create_event_types* and *create_usecase_eventtypes*, in order to avoid errors in post_migrate.connect() This is a hack, the correct solution is a lot more complicated, but we wanted to see what the next problem would be. See https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south

- Removed *metron* and *analytics* from requirements.txt, from INSTALLED_APPS in settings.py, and from valuenetwork/templates/site_base.html.

- Search for *firstof* in templates (ocurrencies in 2 files) and add in the begining of the file:
```
{% load firstof from future %}
```

- Passing tests, but some warnings about deprecated staff:
```
../env/local/lib/python2.7/site-packages/django/test/_doctest.py:59: RemovedInDjango18Warning: The django.test._doctest module is deprecated; use the doctest module from the Python standard library instead.

../env/local/lib/python2.7/site-packages/django/test/simple.py:27: RemovedInDjango18Warning: The django.test.simple module and DjangoTestSuiteRunner are deprecated; use django.test.runner.DiscoverRunner instead.

valuenetwork/valueaccounting/forms.py:418: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ResourceTypeListForm needs updating *class ResourceTypeListForm(forms.ModelForm):*
```
 
- With dev server, check json.

- Changed to django 1.7.11 in requirements.txt, and tested.

**Comment by bhaugen** [comment]
> TypeError: create_agent_types() takes exactly 1 argument (0 given)

post_migrate.connect(create_agent_types) is a South signal. Apparently gone in 1.7. Will take some research to figure out what to do, which I can't do right now. Got other commitments.

**Comment by bhaugen** [comment]
P.S. for now, you should be safe in commenting out all of the post_migrate signal handlers in valueaccounting/models.py.

**Comment by bhaugen** [comment]
I checked the django 1.7 doc. Still has the post_migrate signal, but it looks like you need to handle it differently: https://docs.djangoproject.com/en/1.7/ref/signals/#post-migrate

**Comment by bhaugen** [comment]
I hacked a fix to this problem:
> TypeError: create_agent_types() takes exactly 1 argument (0 given)

I just removed the app argument from the method. The correct solution is a lot more complicated, but I wanted to see what the next problem would be. It is:
```
TemplateSyntaxError: 'metron_tags' is not a valid tag library: ImportError raised loading metron.templatetags.metron_tags: cannot import name simplejson
```
metron is one of the apps in requirements.txt, not under our control. I don't think we need it, so I removed it.

That allowed all the tests to pass. I committed my changes, but, I don't seem to be able to push to your fork. How do you want to handle this?

**Comment by bhaugen** [comment]
More problems surfaced when doing runserver:
```
You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.
```
Running migrate raised this error:
```
django.db.utils.OperationalError: table "easy_thumbnails_thumbnaildimensions" already exists
```
From the browser, many of the pages work fine, but I'm getting some json errors, for example:
```
http://127.0.0.1:8000/accounting/json-timeline/2016_06_20/2016_09_18/0/
Django Version:	1.7
Exception Type:	TypeError
Exception Value:	
__init__() got an unexpected keyword argument 'mimetype'

/home/bob/.virtualenvs/fc17/valuenetwork/valuenetwork/valueaccounting/views.py in json_timeline
    if context_agent:
        processes = processes.filter(context_agent=context_agent)
    orders = [p.independent_demand() for p in processes if p.independent_demand()]
    orders = list(set(orders))
    create_events(orders, processes, events)
    data = simplejson.dumps(events, ensure_ascii=False)
    #import pdb; pdb.set_trace()
    return HttpResponse(data, mimetype="text/json-comment-filtered") 
```
Running out of time today. Will study the json situation problems when I get more time.

**Comment by XaviP** [comment]
Uau! Good job! Now you are collaborator in my fork, if you want to push changes:
https://github.com/XaviP/valuenetwork

**Comment by bhaugen** [comment]
Pushed first set of changes. Tests should now run, and the main set of pages should work from the browser. You'll still get errors here and here from json.

**Comment by XaviP** [comment]
Updated first comment with your improvements, and with some warnings (not blocking) I found running tests.

**Comment by bhaugen** [comment]
I removed all mentions of metron and analytics everywhere. Or so I think, anyway. The critical one was in setting.py INSTALLED_APPS. I commented it out there first to see if we needed it at all. Will delete it in the next commit.

**Comment by XaviP** [comment]
- No more *firstof in templates* warning by calling firstof from future.
- Adapting install docs to django 1.7

Pushed changes.

**Comment by bhaugen** [comment]
I had replaced all instances of mimetype with content_type in
https://github.com/XaviP/valuenetwork/commit/c47377fe1a31c2edeb3d18f55e00f5d05231639f
and fixed the post_migrate.connect problems and got rid of metron in 
https://github.com/XaviP/valuenetwork/commit/204e69a4402fe592635d8225b55cfbbb2230d462
