### ISSUE TITLE
Faircoin network fee should come from balance, not reduce transaction output

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#253]
From telegram:
Maro:
Hi I send faircoin from ocp Wallet to buy viome products in fairmarket but it doesnt gone well because a fee that has been charged is always like this?
 I have to make another purchase and cant do it from ocp because of that

[7:28:37 AM] Maro:
When arrive at home but is made from the exchange office of Madrid node
 There show the full amount 1600 fair but arrives 1599 so I cant complete the order in fairmarket
 How can we avoid this fee or to be charged to the exchange office and not to the sender?

[8:34:58 AM] Bob Haugen:
A network fee is automatically subtracted from OCP faircoin transactions.
 It's in the OCP code, can be changed.

[8:35:51 AM] e3467 faircoop:
it should be covered from the balance, and not from the transaction itself

**Comment by bhaugen** [comment]
Code chain for this starts here:
https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L400
https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L466
```
                # network_fee is subtracted from quantity
                # so quantity is correct for the giving event
                # but receiving event will get quantity - network_fee
```
Then 
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/process_faircoin_requests.py#L101

Looks like the network fee should be added to the "give" event quantity rather than subtracted from the "receive" event quantity.

@XaviP does that seem correct to you?

**Comment by tcoliveira** [comment]
Sorry about the interruption. 

This
https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L486
Should be in the " receive" event

**Comment by MichalisKas** [comment]
I can't help with code, but just a comment since we encountered this fault (?) with other wallets also. I agree that the amount should not be deducted from transaction amount but from the sender's balance. Although there should be special attention on the case where the sender's transaction empties its wallet. Perhaps, just in that case, there should be no fee?

**Comment by bhaugen** [comment]
I have several questions about this issue:
* Should the sender always pay the fee? That is, the fee should be subtracted from the sender's balance?
* Where in the code is the fee processed? 
* Where should the code change be made?

Here's some relevant code excerpts:

In process_faircoin_requests.broadcast_tx() the network fee is added to the transaction amount before it is sent to the daemon:
```
amount = float(event.quantity) * 1.e6 # In satoshis
[...]
electrum_fair_nrp.make_transaction_from_address(address_origin, address_end, int(amount))
```
electrum_fair_nrp is the bridge to the daemon. Here's the next part of the code chain there:
```
# make a transfer from an adress of the wallet 
def make_transaction_from_address(address_origin, address_end, amount):
    format_dict = [address_origin, address_end, amount]
    response = send_command('make_transaction_from_address', format_dict)
    return response
```        
make_transaction_from_address happens in the daemon, here: 
https://github.com/FreedomCoop/valuenetwork/blob/25e2a25cd02aff8bcf6e56c9b2417c0e8072716a/faircoin_nrp/daemon/daemon.py.sample#L112

There, the network fee is subtracted from the amount.
```
amount_total = int(amount) - int(net_fee) #In Satoshis
[...]
wallet.make_unsigned_transaction(coins, output, change_addr=address_origin)
```
From there we go to the electrum-fair.wallet. I'm posting the whole code for this method because I can't follow the logic, hoping that somebody can:
```
    def make_unsigned_transaction(self, coins, outputs, fixed_fee=None, change_addr=None):
        # check outputs
        for type, data, value in outputs:
            if type == 'address':
                assert is_address(data), "Address " + data + " is invalid!"

        amount = sum(map(lambda x:x[2], outputs))
        total = fee = 0
        inputs = []
        tx = Transaction.from_io(inputs, outputs)
        # add old inputs first
        for item in coins:
            v = item.get('value')
            total += v
            self.add_input_info(item)
            tx.add_input(item)
            # no need to estimate fee until we have reached desired amount
            if total < amount:
                continue
            fee = fixed_fee if fixed_fee is not None else self.estimated_fee(tx)
            if total >= amount + fee:
                break
        else:
            raise NotEnoughFunds()
        # remove unneeded inputs
        for item in sorted(tx.inputs, key=itemgetter('value')):
            v = item.get('value')
            if total - v >= amount + fee:
                tx.inputs.remove(item)
                total -= v
                fee = fixed_fee if fixed_fee is not None else self.estimated_fee(tx)
            else:
                break
        print_error("using %d inputs"%len(tx.inputs))

        # change address
        if not change_addr:
            # send change to one of the accounts involved in the tx
            address = inputs[0].get('address')
            account, _ = self.get_address_index(address)
            if self.use_change and self.accounts[account].has_change():
                # New change addresses are created only after a few confirmations.
                # Choose an unused change address if any, otherwise take one at random
                change_addrs = self.accounts[account].get_addresses(1)[-self.gap_limit_for_change:]
                for change_addr in change_addrs:
                    if self.get_num_tx(change_addr) == 0:
                        break
                else:
                    change_addr = random.choice(change_addrs)
            else:
                change_addr = address

        # if change is above dust threshold, add a change output.
        change_amount = total - ( amount + fee )
        if fixed_fee is not None and change_amount > 0:
            tx.outputs.append(('address', change_addr, change_amount))
        elif change_amount > DUST_THRESHOLD:
            tx.outputs.append(('address', change_addr, change_amount))
            # recompute fee including change output
            fee = self.estimated_fee(tx)
            # remove change output
            tx.outputs.pop()
            # if change is still above dust threshold, re-add change output.
            change_amount = total - ( amount + fee )
            if change_amount > DUST_THRESHOLD:
                tx.outputs.append(('address', change_addr, change_amount))
                print_error('change', change_amount)
            else:
                print_error('not keeping dust', change_amount)
        else:
            print_error('not keeping dust', change_amount)

        # Sort the inputs and outputs deterministically
        tx.BIP_LI01_sort()

        run_hook('make_unsigned_transaction', tx)
        return tx
```

**Comment by bhaugen** [comment]
Also, if the fee should come from the sender's balance, and we can figure out how to make that happen in the code, should the page which sends the transaction have one of those multi-line totals? Like:

| Item | Amount |
|----------------------|-----------|
| Amount to send: | 600.00 |
| Network fee:      |       .01 |
| total                   |   600.01 |
