### ISSUE TITLE
[dj1.9 upgrade] urls.py importing views which try to access db. 

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#259]
Since this commit in django_19 branch: https://github.com/FreedomCoop/valuenetwork/commit/3e08ed62548de9715a42143c0b0b61a466c8467f it's not possible to make a fresh installation and a new db running migrate. The problem seems to do with the need of import views from valuenetwork.valueaccounting app and from work app that executes code that tries to access the DB when imported.
So, this change:
```
RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10
```
is making views imports from urls.py that are trying to access db. This is a sample error:
```
(...)
  File "/home/xavi/Documents/freedomcoop/dev_django19/valuenetwork/valuenetwork/urls.py", line 13, in <module>
    import work.views
  File "/home/xavi/Documents/freedomcoop/dev_django19/valuenetwork/work/views.py", line 28, in <module>
    from valuenetwork.valueaccounting.forms import *
  File "/home/xavi/Documents/freedomcoop/dev_django19/valuenetwork/valuenetwork/valueaccounting/forms.py", line 156, in <module>
    class AgentSelectionForm(forms.Form):
  File "/home/xavi/Documents/freedomcoop/dev_django19/valuenetwork/valuenetwork/valueaccounting/forms.py", line 158, in AgentSelectionForm
    queryset=EconomicAgent.objects.individuals_without_user(),
  File "/home/xavi/Documents/freedomcoop/dev_django19/valuenetwork/valuenetwork/valueaccounting/models.py", line 399, in individuals_without_user
    for agent in all_agents:
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/xavi/Documents/freedomcoop/dev_django19/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: valueaccounting_economicagent
```

This problem is only creating a fresh installation, without db.
With testocp db or any other older one, migrate runs ok.

**Comment by bhaugen** [comment]
This appears to be the fix:
http://stackoverflow.com/questions/34096424/django-support-for-string-view-arguments-to-url-is-deprecated-and-will-be-rem

>  For Django 1.10, you now have to import the app's view.py, and then pass the second argument of url() without quotes. Here is my code now in urls.py:
```
from django.conf.urls import url
from django.contrib import admin
import main.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main.views.home)
]
```
> I did not change anything in the app or view.py files.

**Comment by bhaugen** [comment]
Looks to me like in [work.urls](https://github.com/FreedomCoop/valuenetwork/blob/master/work/urls.py) we would do:
```
import work.views
```
and then delete all of the quotation marks around every string that starts with ``` 'work.views ```.

There's one of those in https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/urls.py , too.

And then in [valueaccounting.urls](https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/urls.py) the pattern would be:
```
import valuenetwork.valueaccounting.views
```
and then do the quotation mark removal.

Not sure about all the details, would need to be tested.

**Comment by XaviP** [comment]
> and then delete all of the quotation marks

Yes, all about importing views and removing quotations is done. Look:
https://github.com/FreedomCoop/valuenetwork/blob/django_19/valuenetwork/urls.py
https://github.com/FreedomCoop/valuenetwork/blob/django_19/valuenetwork/valueaccounting/urls.py
https://github.com/FreedomCoop/valuenetwork/blob/django_19/work/urls.py

The problem is when all these changes are done, the views import tries to access the db. So, if you don't have a db yet, it gives errors about missing tables in db.

**Comment by bhaugen** [comment]
Ok, that's a different problem. Looks like it is in forms. See this comment:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/forms.py#L155

And this django users thread:
https://groups.google.com/forum/#!topicsearchin/django-users/author$3Ame/django-users/d5xn4gSnw6Y

Those queryset methods need to be moved in to form __init__(), like this one:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/forms.py#L226

When they are in the class definition, they get executed at import time.

**Comment by bhaugen** [comment]
The methods could also be rewritten to return lazy querysets that don't hit the db until runtime, like Michal Petruchka suggested:

> You could fix this by doing something along the lines of:: 
```
    def with_user(self): 
        return EconomicAgent.objects.filter(users__isnull=False).distinct() 
```
> The important difference is that this version of ``with_user`` does 
not evaluate anything eagerly, but rather sets up the necessary 
filters to get the correct result set at the time of evaluation of 
that queryset.

**Comment by XaviP** [comment]
> Those queryset methods need to be moved in to form init() When they are in the class definition, they get executed at import time.

> The methods could also be rewritten to return lazy querysets that don't hit the db until runtime

Thanks @bhaugen !! I was completly lost in this bug.
Do you know if there are many of this queryset to move or change?
Can you help in this (django_19 branch)?

**Comment by XaviP** [comment]
I think issue https://github.com/FreedomCoop/valuenetwork/issues/241 can be related to this too.

**Comment by bhaugen** [comment]
I think the easiest thing to do first is to rewrite these methods that now hit the database to send lazy querysets:
Several in a row here:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L384

And:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L1742



That might be all that is needed. I'm going thru the rest now. Back in a minute or two.

**Comment by bhaugen** [comment]
That's all I see by eyeballing. 

> Can you help in this (django_19 branch)?

I can do it tomorrow. Need to set up a new dev environment to work on it. Got some other commitments this afternoon, and I didn't get much sleep.

**Comment by bhaugen** [comment]
I'll get it done tomorrow morning (US CST)

**Comment by bhaugen** [comment]
done, I think.

**Comment by XaviP** [comment]
Solved. Thanks @bhaugen https://github.com/FreedomCoop/valuenetwork/commit/70da9d78130e75e9f6e9c80a15e5b5c319bf72bf https://github.com/FreedomCoop/valuenetwork/commit/f8fd56371f7b11c3815e54ba783c5601c4e1161c
