### ISSUE TITLE
Make a new wallet importing the private keys for the addresses in database

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#270]
- @santiky said:

> We should make a new wallet and import the private keys for the addresses in database.

- More info in [electrum docs](http://docs.electrum.org/en/latest/faq.html#can-i-import-private-keys-from-other-bitcoin-clients):

> If you want to import private keys and not sweep them you need to create a special wallet that does not have a seed. For this, create a new wallet, select “restore”, and instead of typing your seed, type a list of private keys.

**Comment by santiky** [comment]
It can be done programatically too but perhaps better to wait for the faircoin2 migration and do all at once.

**Comment by XaviP** [comment]
Done!
