### ISSUE TITLE
pinax-notifications is not using the right templates for email notifications

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#272]
In last upgrade to dj 1.9, we've changed the notification package to [pinax-notifications](https://pinax-notifications.readthedocs.io/en/latest/). There's a problem now with the templates used for sending emails. Pinax-notifications is using these templates:
https://github.com/FreedomCoop/valuenetwork/tree/master/valuenetwork/templates/pinax/notifications
The old templates are ignored:
https://github.com/FreedomCoop/valuenetwork/tree/master/work/templates/notification
Maybe it's only a path issue, but not possible for me to test it now.

**Comment by bhaugen** [comment]
I can probably check it out today, after I get this project task history report done.

**Comment by XaviP** [comment]
Thanks @bhaugen, I cannot do it right now. I think it's only move:
- `work/templates/notification/` to `work/templates/pinax/notifications/`
- `valuenetwork/valueaccounting/templates/notification` to `valuenetwork/valueaccounting/templates/pinax/notifications/`

Note the plural change in notification/s.

**Comment by bhaugen** [comment]
ok, got it.

**Comment by XaviP** [comment]
Done: https://github.com/FreedomCoop/valuenetwork/commit/c6ffde760199b61327fba69a5fbec68936476387
