### ISSUE TITLE
render() instead of render_to_response() in views.py

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#276]
In django docs:

> render_to_response()
> This function preceded the introduction of render() and works similarly except that it doesn’t make the request available in the response. It’s not recommended and is likely to be deprecated in the future.

In django 1.10 - 1.11 the arguments in render_to_response() need to be changed:
`The context_instance argument of render_to_response is deprecated.`
https://docs.djangoproject.com/en/1.10/topics/http/shortcuts/#render-to-response

I think the best option is to change directly all render_to_response() to render(), as pointed [here](http://stackoverflow.com/questions/38739422/django-error-render-to-response-got-an-unexpected-keyword-argument-context-i#38739423).

There's a way to do a bulk change:
- Substitute all `render_to_response(` with `render(request, `
- Delete all `, context_instance=RequestContext(request)`

I've done some tests and it seems to work, but there are more than 100 ocurrences.

**Comment by bhaugen** [comment]
I'll study this tomorrow. Need to understand what happens to the contexts.

**Comment by XaviP** [comment]
I've pushed the bulk change in branch views_with_render:
https://github.com/FreedomCoop/valuenetwork/tree/views_with_render

I've only commited changes in valueaccounting and work views.py ( https://github.com/FreedomCoop/valuenetwork/commit/f4dd50f39dd1c9503e39420a176a82a1f10fb38e ) but the other occurrences are commented or doesn't affect (not active apps)

**Comment by bhaugen** [comment]
Looks ok to me. Will need to do enuf testing to make sure the pattern works.

**Comment by XaviP** [comment]
I've deployed views_with_render branch in testocp, to easy testing.
There's an upgrade of django-fobi==0.10.4 deployed too, already tested by @bum2

**Comment by XaviP** [comment]
Merged in master. Closing.
