### ISSUE TITLE
Faircoin EconomicEvents need to record created_by user

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#288]
EconomicEvent has a field, created_by, that is meant to be filled in with the user who created the event. It is now not being filled in for Faircoin EconomicEvents.

This caused a problem recently when we had some Faircoin events and could not tell if they were created inside OCP or were created to mirror external blockchain transactions that were not created inside OCP. 

@XaviP set up a new digital_currency_tx_state, "external", to mark those that were created from external transactions. But it would also have been good to know who created the internal ones.

The created_by fields should be filled in work.views.transfer_faircoins and valueaccounting.service.ExchangeService.send_faircoins. valueaccounting.send_faircoins needs to send the created_by user to ExchangeService.send_faircoins.

work.views.transfer_faircoins should also use the ExchangeService to send faircoins so we keep all of that logic in one place. That change could be made at this same time, but making that change at the same time might cause more complications about testing Faircoin transactions locally.

**Comment by XaviP** [comment]
On services.py the request.user param is not available, but it seems ok to me that def include_blockchain_tx_as_event doesn't save the current user, as this is not a voluntary action, and the transaction has None as from_agent, so it's easy to deduce how it has been created.
Still to think what to do in ExchangeService.send_faircoins (no request.user available)

**Comment by bhaugen** [comment]
I'd need to look at the code, but anything that is triggered from the UI can get the request.user passed in, one way or another.
