### ISSUE TITLE
We need a policy and procedure for FairCoin errors

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#289]
By policy, I mean what should be done if an address or transaction request runs into an error in FairChain? (is that the correct name for the stuff that happens beyond the daemon?)

By procedure, I mean the exact system and user methods for dealing with the error.

We've had errors in both address requests and transaction sending. They probably need different methods.

This is also related to https://github.com/FreedomCoop/valuenetwork/issues/288 and https://github.com/FreedomCoop/valuenetwork/issues/287 and probably some other open issues.

**Comment by bhaugen** [comment]
@XaviP asks, also, how can we avoid transaction errors?

**Comment by XaviP** [comment]
What we have now:  a protection against no connection to daemon.
- When the daemon is not working, function digital_currency_balance will return "Not accessible now":
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L4367
- and function spending_limit will return limit = Decimal("0.0")
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L4425
- and views gives these values to the template:
https://github.com/FreedomCoop/valuenetwork/blob/master/work/views.py#L293
- and the template has condicionals with these values (this is a commit done yesterday):
1. https://github.com/FreedomCoop/valuenetwork/blob/master/work/templates/work/faircoin_account.html#L136
2. https://github.com/FreedomCoop/valuenetwork/blob/master/work/templates/work/faircoin_account.html#L278

This is working pretty good when there's no connection to the daemon, but we need to protect too from no network connection. Maybe it can be enough to put here:
https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/faircoin_utils.py#L3
something like:
```
def init_electrum_fair():
    try:
        assert(efn.daemon_is_up())
    except:
        msg = "Cannot connect to daemon. Exiting."
        assert False, msg
    try:
        assert(efn.is_connected())
    except:
        msg = "Cannot init Electrum Network. Exiting."
        assert False, msg
```
I don't really know if this can be avoid the hung when the user tries to access.

This is only an approach to the network failure. I think we need to go further to protect against transaction errors.

**Comment by XaviP** [comment]
The faircoin_utils.py function init_electrum_fair() was not protecting anything. So I've tried to make a real protection in a new branch:
https://github.com/FreedomCoop/valuenetwork/commit/503e93ae52e3be5d4cb46010f97a742b13bed58a
Now any function in faircoin_utils.py returns None if any problems in daemon or in network connection. Now we have to make a review of where this functions are used.

**Comment by XaviP** [comment]
Reviewed all faircoin_utils everywhere in code. Pushed and deployed in testocp. Needs manual test.
I don't close this issue, still todo:
- Mark a transaction as ERROR when several attempts to broadcast fail.
- How to communicate the transaction error to the user.
- Determine what's happening to these transactions that fails (too many inputs?? too much amount?? ...) and code this limit in ocp, to avoid the user to send a error transaction.
- Anything more?

**Comment by bhaugen** [comment]
Let's check with Santi and Thomas whether Faircoin2 will have more of an API and better error messages for OCP.

**Comment by XaviP** [comment]
New tx state: Error https://github.com/FreedomCoop/valuenetwork/commit/ed89cabcbb27f4ce8dce0ac497b17d4c7fa94cb6

**Comment by XaviP** [comment]
Now we can see tx state in EconomicEvent admin list. I have changed old "external" states of error tx to state Error. Take a look at the list: we have many "new" and "broadcast" tx. The wallet is not working ok.

**Comment by XaviP** [comment]
Solved problems with a transaction. I think we need a command to confirm all broadcasted transactions without waiting for the user to visit the faircoin account, in order to aliviate the wallet load.

**Comment by XaviP** [comment]
> Determine what's happening to these transactions that fails (too many inputs?? too much amount?? ...) and code this limit in ocp, to avoid the user to send a error transaction.

The error transactions were failing because of not enough fee when more than 6-7 inputs used.
We need to recode the fee calculation, adapting to faircoin2 at the same time. Opening a new issue.
