### ISSUE TITLE
A couple possible problems after merging django17 to master

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#29]
These appeared when testing django17, too, but they don't appear to matter.

When doing runserver:
```
You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.
```

When running ./manage.py  migrate:
```
django.db.utils.OperationalError: table "easy_thumbnails_thumbnaildimensions" already exists
```

So there's some oddness in easy_thumbnails migrations, but easy_thumbnails still seems to work ok.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
