### ISSUE TITLE
Upgrade django-fobi with django 1.10

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#294]
- There's a bug with fobi and dj1.10:
```
'SavedFormDataEntry' object has no attribute '_default_manager'
```
- It seems that is a recurrent error in other packages upgrading to dj1.10, see:
https://github.com/celery/django-celery/pull/432

- I think we have to upgrade django-fobi. Now it's fixed on 0.10.4, but newer version has been adapted to dj1.11:
https://github.com/barseghyanartur/django-fobi/releases

@bum2 can you help on this? I don't know even how to test it.

**Comment by bum2** [comment]
Solved in https://github.com/FreedomCoop/valuenetwork/commit/260d595f8aba569ae89fcf658be290cfd0af8036 ... the SavedFormDataEntry model manager was reached via an instance of that model in JoinRequest instances, and that is wrong but the old fobi version didn't complain. Now the manager is reached directly (SavedFormDataEntry.manager) which is the correct way.

**Comment by XaviP** [comment]
Thanks @bum2 !! Closing.
