### ISSUE TITLE
Status report for first Freedom Coop pilot

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#3]
# Server
* We are still running on http://nrp.webfactional.com/
    * That server does not have any faircoin software or wallet installed yet.
    * We're using sqlite for the database, which is good for testing, but will start to cause "database locked" errors when we get too many people using it at the same time. Which will probably not happen in the pilot. See https://www.sqlite.org/whentouse.html

> SQLite works great as the database engine for most low to medium traffic websites (which is to say, most websites). The amount of web traffic that SQLite can handle depends on how heavily the website uses its database. Generally speaking, any site that gets fewer than 100K hits/day should work fine with SQLite. 

* Valentina is working on setting up a new server

# OCP software
* I am working on getting faircoin transactions up and running.
    * As of today (2016-05-03) I have a partial blocker in determining reliably whether a faircoin transaction has been accepted by the network or not. See https://github.com/Punto0/faircoin_nrp/issues/16
    * Other than that issue, sending faircoins from an agent's faircoin address to any other address usually works now.
    * I need to implement the following other faircoin use cases that I know of:
        * Accepting faircoins from outside OCP for distribution to coop workers.
        * Distributing faircoins to coop workers.
* Lynn is working on organization configuration and landing pages for different roles, coop workers and coop adminstrators.

**Comment by bhaugen** [comment]
Update: implemented distributing faircoins coop workers in test mode
* sending fake faircoins, but all the logic is in place, and I have a regression test

**Comment by bhaugen** [comment]
Another update: I think I have at least rough versions of all of the faircoin functions *except* how the income arrives to be distributed. (Got the distribution coded and tested for when it comes in.)

Main remaining problem is getting the faircoin transactions to be accepted reliably by the network. Still working on that.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
