### ISSUE TITLE
Bug in non-process logging

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#31]
Here's the trace.  Conditions: went into non-process logging, entered a contribution, nothing odd about it.

AttributeError at /work/non-process-logging/

'TextInput' object has no attribute '_has_changed'

Request Method: 	POST
Request URL: 	https://testocp.freedomcoop.eu/work/non-process-logging/
Django Version: 	1.7.11
Exception Type: 	AttributeError
Exception Value: 	

'TextInput' object has no attribute '_has_changed'

Exception Location: 	/home/ocp/app/valuenetwork/valuenetwork/valueaccounting/widgets.py in _has_changed, line 111
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path: 	

['/home/ocp/app/valuenetwork',
 '/home/ocp/app/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/ocp/app/valuenetwork/']

Server time: 	Sat, 2 Jul 2016 22:21:13 +0000
Traceback Switch to copy-and-paste view

    /home/ocp/app/env/lib/python2.7/site-packages/django/core/handlers/base.py in get_response

                            response = wrapped_callback(request, *callback_args, **callback_kwargs)

         ...
    ▶ Local vars
    /home/ocp/app/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py in _wrapped_view

                        return view_func(request, *args, **kwargs)

         ...
    ▶ Local vars
    /home/ocp/app/valuenetwork/work/views.py in non_process_logging

                if time_formset.is_valid():

         ...
    ▶ Local vars
    /home/ocp/app/env/lib/python2.7/site-packages/django/forms/formsets.py in is_valid

**Comment by bhaugen** [comment]
I think this is fixed. Closing the issue.
