### ISSUE TITLE
Multicurrency app requires log system.

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#311]
To implement a log system in multicurrency app is needed.

**Comment by bhaugen** [comment]
What needs to be logged? Is this like the python logs used in https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/process_faircoin_requests.py or something different, like some kind of database records?

**Comment by XaviP** [comment]
We need to log at least the errors communicating to chip-chap api, when any problem in their side, as now they pass only with a controled user error message, but admins don't notice about that.
I was thinking in a log system like process_faircoin_requests.py, that seems enough to me.
Btw, the process_faircoin_requests.py has a problem with log level definition, always showing the critical errors, but I didn't find the way to set it to debug level.

**Comment by bhaugen** [comment]
> Btw, the process_faircoin_requests.py has a problem with log level definition, always showing the critical errors, but I didn't find the way to set it to debug level.

It's set here:
https://github.com/FreedomCoop/valuenetwork/blob/master/work/management/commands/send_faircoin_requests.py

Could probably be externalized as a command parameter.

**Comment by XaviP** [comment]
The level change doesn't work, tested.
Not sure, but it seems has to do with several instances of the same log running at the same time (faircoin_nrp.py uses the same logger). See the disable_existing_loggers parameter:
https://docs.python.org/2/library/logging.config.html#logging.config.fileConfig

**Comment by XaviP** [comment]
A basic logging system is already implemented. If improvements are needed, please open new issue.
