### ISSUE TITLE
Upgrading from django 1.7 to 1.8

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#32]
It seems that django 1.8 is the last LTS version, so trying to make a last upgrade. You can find code in:
https://github.com/XaviP/valuenetwork/tree/django18

- Changed django 1.8 in requirements.txt

- Changed name "sub-agents" by a valid python name, with:
```
grep -rl "sub-agents" ./ | xargs sed -i s@'sub-agents'@'sub_agents'@g
```
- Changed  account/models.py line 286, like this: (without parenthesis in now)
```
created = models.DateTimeField(default=timezone.now)
```
- Changed in valuenetwork/valueaccounting/tests/value_equation_test_objects.py line 566: (supplier2)
```
supplier2.save()
```
- ERROR: test_faircoin_distribution (valuenetwork.valueaccounting.tests.test_value_equations.ValueEquationTest)
```
ValueError: Cannot assign "<Claim: Claim vacontributor2 has against context for 400.00 from 2016-07-06>": "Claim" instance isn't saved in the database.
```
Solved updating django 1.8.13 in requirements.txt, as this is an issue of django 1.8 solved in 1.8.5

**Comment by bhaugen** [comment]
Code is most likely still using datetime.date.today() or something like that, which is apparently superceded by django.utils.timezone.now in 1.8. I'll need to catch up (get 1.7 migrations cleaned up) before I can research and fix this one. django.utils.timezone.now probably gets you a datetime, and the fields probably only allow a date. But then the django datefield might have changed, too.

**Comment by bhaugen** [comment]
@XaviP - here's what I found about that date warning. This is the code being warned about:
```
class EmailConfirmation(models.Model):
    
    email_address = models.ForeignKey(EmailAddress)
    created = models.DateTimeField(default=timezone.now())
```
This http://stackoverflow.com/questions/29549611/fixed-default-value-provided-after-upgrading-to-django-1-8 says this should work:
```
    created = models.DateTimeField(default=timezone.now)
```
I fixed that and pushed. I did not find any other instances like that.

**Comment by bhaugen** [comment]
```ValueError: Cannot assign "<EconomicAgent: supplier2>": "EconomicAgent" instance isn't saved in the database.```

Fixed, I think.

**Comment by bhaugen** [comment]
``` ValueError: Cannot assign "<Claim: Claim vacontributor2 has against context for 400.00 from 2016-07-06>": "Claim" instance isn't saved in the database.```

Got any more to the error message? Module, method, line, etc?

**Comment by XaviP** [comment]
```
created fake faircoin address
E..
======================================================================
ERROR: test_distribution (valuenetwork.valueaccounting.tests.test_value_equations.ValueEquationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/tests/test_value_equations.py", line 341, in test_distribution
    agent_totals, details = ve.run_value_equation(amount_to_distribute=amount_to_distribute, serialized_filters=serialized_filters)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 9778, in run_value_equation
    ces, contributions = bucket.run_bucket_value_equation(amount_to_distribute=bucket_amount, context_agent=self.context_agent, serialized_filter=serialized_filter)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 11195, in run_bucket_value_equation
    claims = self.claims_from_events(contribution_events)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 11375, in claims_from_events
    claim = event.get_unsaved_contribution_claim(event.vebr)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 10611, in get_unsaved_contribution_claim
    event_effect="+",
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 668, in __set__
    (value, self.field.rel.to._meta.object_name)
ValueError: Cannot assign "<Claim: Claim vacontributor2 has against context for 400.00 from 2016-07-06>": "Claim" instance isn't saved in the database.

======================================================================
ERROR: test_faircoin_distribution (valuenetwork.valueaccounting.tests.test_value_equations.ValueEquationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/tests/test_value_equations.py", line 419, in test_faircoin_distribution
    serialized_filters=serialized_filters)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 9566, in run_value_equation_and_save
    serialized_filters=serialized_filters)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 9778, in run_value_equation
    ces, contributions = bucket.run_bucket_value_equation(amount_to_distribute=bucket_amount, context_agent=self.context_agent, serialized_filter=serialized_filter)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 11195, in run_bucket_value_equation
    claims = self.claims_from_events(contribution_events)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 11375, in claims_from_events
    claim = event.get_unsaved_contribution_claim(event.vebr)
  File "/home/xavi/Documents/freedomcoop/dev/valuenetwork/valuenetwork/valueaccounting/models.py", line 10611, in get_unsaved_contribution_claim
    event_effect="+",
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 468, in __init__
    setattr(self, field.name, rel_obj)
  File "/home/xavi/Documents/freedomcoop/dev/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 668, in __set__
    (value, self.field.rel.to._meta.object_name)
ValueError: Cannot assign "<Claim: Claim vacontributor2 has against context for 400.00 from 2016-07-06>": "Claim" instance isn't saved in the database.

----------------------------------------------------------------------
Ran 35 tests in 30.988s

FAILED (errors=2)
Destroying test database for alias 'default'...
```

**Comment by bhaugen** [comment]
@XaviP - thanks for the added clues. Looks like Django has gotten a lot stricter about foreign key references. We did all that in lazy fashion so people could run their value equations in sandbox mode without saving anything, and it all worked, including the parts they are now complaining about. Then we would save it all at the end if they wanted it saved.

Changing this to be non-lazy (saving everything as you go) could be major surgery. We'll need to discuss and see if it's worth the work. (And how much work it would be.) If it's a lot, I would vote for sticking with 1.7 for now. @fosterlynn ?

**Comment by XaviP** [comment]
For me 1.7 is ok.
But if you want to leave only last error pending, the only correction that is left now in master branch is the first one:
- Changed name "sub-agents" by a valid python name, with
```
grep -rl "sub-agents" ./ | xargs sed -i s@'sub-agents'@'sub_agents'@g
```
If you consider it appropiate, and no problems associated to it, commit this change and forget it forever :-)

**Comment by bhaugen** [comment]
> commit this change 

Done. I got a few more bugs that I know about to fix yet. Will get on them later today.

**Comment by bhaugen** [comment]
@XaviP which sub-version of 1.8 are you using? See
https://docs.djangoproject.com/en/1.9/releases/1.8/#assigning-unsaved-objects-to-relations-raises-an-error
That change was reverted in 1.8.4, or so they say:
https://docs.djangoproject.com/en/1.9/releases/1.8.4/
https://code.djangoproject.com/ticket/25160

Otherwise I intended to raise that same ticket.

**Comment by fosterlynn** [comment]
Well, the sandbox feature for the value equation is actually a very useful feature.  At least if you use value equations, which FC I think will want to do.  The sandbox gives you a way to experiment and compare different proposals for value equations.  Also we run that method on the distribution page so people can double check their entries, since distributions have no undo function.  It is possible that FC will have a fairly stable value equation for the refugee work, so would not need the sandbox so much.  On the other hand, the direction Ale is going with the osce people would be more fluid and variable.

Let's see, how would we do it?  Could we create temp tables like the test scripts? (Ouch.)  Or create a parallel set of objects that aren't models?  Or remove it and create an undo function and detail reporting on the distributions?  I might like the non-model objects option, seems fairly clean.  Although an undo would also be nice to have.

But I do think it will be some level of surgery to that part of the code, which is fairly complex.  On the plus side, I don't think it will really impact the rest of the app.

So I agree with sticking with 1.7 for now.  If we stay with this code base, we'll need to bite that bullet sometime soon though.

**Comment by XaviP** [comment]
Hey, good news!! You're right, @bhaugen 
The errors arises only in 1.8 version (the first one) but with 1.8.13 disappear. It seems that the ticked you linked has been solved and commited in some of the middle versions :-)

**Comment by bhaugen** [comment]
Good! I agree with Lynn, it is a useful feature that they should not have killed.

**Comment by XaviP** [comment]
Running django 1.8.13 in our test site. No problems apparently, testing stage.
So, if we are ok with this update, the only thing to do is commit the change in requirements.txt with django 1.8.13 in master branch.
