### ISSUE TITLE
How to manage migration data from valueaccounting app to faircoin app

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#323]
The branch faircoin_models_onlyfields (currently in testocp, working ok) moves the faircoin data from EconomicResource and EconomicEvent models to new one2one models in faircoin app. See the data migration file:
https://github.com/FreedomCoop/valuenetwork/blob/faircoin_models_onlyfields/faircoin/migrations/0002_auto_20170708_1615.py
The problem I see is when the migration is done, like in testocp now, and the original fields in EconomicResource and EconomicEvent deleted, what should ocp do with that migration data file? I mean, when the migration is done in test and production, should I empty that migration data file to avoid errors in migrations later??

**Comment by bhaugen** [comment]
I don't think you should delete the data migration. I would need to check into this more deeply to be sure, but it should use the state of the models it was based on if it is rerun in a migration sequence, not the current state of the models. 

Have you deleted those fields yet? If you run the tests, which will re-run all the migrations, you should be able to find out if the migration sequence still works. 

But you might want to squash the migrations after those fields are deleted:
https://docs.djangoproject.com/en/1.11/topics/migrations/#squashing-migrations

Here's more about deleted fields:
https://docs.djangoproject.com/en/1.11/topics/migrations/#considerations-when-removing-model-fields

I have never squashed migrations with the built-in django ones, but I did it using South, which the built-in migrations were based on, and it worked fine.

**Comment by XaviP** [comment]
> Have you deleted those fields yet?

No, I need to make the data migration first in test and production systems, and then remove the fields in valueaccounting models. But when the fields will be removed, the data migration file will rise error as there will be no more that fields in valueaccountig app. That's the problem I see.
Tests doesn't help here, as they run creating a new empty db.

**Comment by bhaugen** [comment]
That's the problem I ran into when I first tried data migrations in South, but I was doing it wrong. They had a way to use the models from the time of the data migration rather than the current model. I don't have much time to study it today, but will see what I can find out.

**Comment by bhaugen** [comment]
P.S. I'm rethinking. I also once deleted some data migrations from a sequence, and that did not cause any problems. So I think your original idea of deleting the data migration is ok, too.

**Comment by XaviP** [comment]
> I think your original idea of deleting the data migration is ok

I mean to empty the file, but not delete the file, as the number of migration is stored in db. I'll make some testing.

**Comment by XaviP** [comment]
Solved by checking if the fields exist in EconomicResource and EconomicEvent models. Closing.
