### ISSUE TITLE
Define scope and requirements for gitlab interoperability

### ISSUE THREAD

**Issue by skoria** [FreedomCoop/valuenetwork#340]
Various groups in faircoop will use different task management systems according to their need and in the long term will need to interoperate with ocp for distribution of payments: currently these systems are the ocp work app, gitlab (git.fairkom.net), and wekan. This task is to do with defining how long it would take and what would be involved in adapting ocp and gitlab so that they can minimally interoperate.

# Task types in OCP
(from bob)

Bob Haugen, [01.09.17 20:12]
Here's my report on some of the testing work management features in testocp. Where would like me to post this for future reference?

First I will describe what I tested.

* OCP provides several ways to log work:
    * Just log work you did with no previous plan (*called "Extra Tasks" in the Work app.
    * Plan a task for yourself to do. (Called "Simple Tasks" in the Work app.)
    * Plan a task for someone else to do. (They can decline.)
    * Plan an unassigned task, for somebody else to take.
    * Plan a process with one or more work tasks connected to it. (This is how more than one person can work on the same thing.)
* The Kamasi app will unify the Simple and Process tasks so a process is always created automatically, and more than one person can work on it, but you won't need to be very aware of all that until somebody else wants to join.

Test results:
* "Extra Tasks" do not work correctly.
* "Simple Tasks" do not work correctly either.
* "Process Tasks" seem to work okay, but should be tested more if we want to use them.

# Possibilities for gitlab export

Gitlab exports to CSV: https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/1126 - in fact the groups recently set up in the faircoop github installation (git.fairkom.net) all have this option as well as RSS feeds. This would require some work on the API in OCP. The simplest way of having a link between gitlab based projects and the same projects in ocp would be to match labels, measurement/types of work and areas so that on completion or on a periodical basis they would be imported for value distribution.

**Comment by capiscuas** [comment]
What about using the comment field of the tasks to paste the link to reference and sync the issue/task/process from any other issue tracker? 
That way OCP is aware of what type of issue tracker we are talking about and in the future can read how much hours has been spent in each task, whether the task is closed. etc... The sync could be done also from the other side with an API of OCP.

**Comment by fosterlynn** [comment]
>Various groups in faircoop will use different task management systems according to their need and in the long term will need to interoperate with ocp for distribution of payments: currently these systems are the ocp work app, gitlab (git.fairkom.net), and wekan

I completely agree this will be important, and it doesn't make any sense for useful specialized apps such as gitlab to be duplicated in ocp.

A couple small notes: ocp work app doesn't need to interoperate, all the ocp derivatives use the same database already.  We are going to do some kind of kanban-like interface in the Kamasi OCP UI, so we can compare that to wekan at some point and see if that interface is needed.

OCP api status: We are creating a new graphql api for Kamasi from the OCP backend.  This is an early experiment in using the [ValueFlows](http://valueflo.ws/) vocabulary.  There is some old code for a REST api, that may or may not still work, and probably doesn't cover everything.  There is some limited experimental old code for an rdf based api (json-ld at the moment), also using even earlier ValueFlows.

>What about using the comment field of the tasks to paste the link to reference and sync the issue/task/process from any other issue tracker?

So there would be limited double entry, until we get something better?  We could use the url field instead of the comments, too.  May need to add it to the UI, but it is there in the database.

>The sync could be done also from the other side with an API of OCP.

There are some efforts by a couple groups in France (separately) to create translators of vocabularies to facilitate interoperability where agreeing on the vocabulary is difficult (api's already exist, etc.).  At least one, and probably both, want to do ValueFlows.  But we don't know if or when that will come to fruition.  Or we can write something of course.

**Comment by bhaugen** [comment]
A couple of things: the OCP devs are all heavily loaded with work, so it's better if somebody who wants to bridge from another app take the lead, and use an OCP API that exists. If the required API does not yet, it is probably on the roadmap, and will be created, and might be able to be expedited, depending on all the relative priorities.

**Comment by capiscuas** [comment]
after researching... i see that Gitlab has 2 ways for integrating other apps:

Webhooks: 
https://git.fairkom.net/help/user/project/integrations/webhooks

and Project services
where seems to be like little scripts connecting to the API's (using API keys) of other famous services like Slack, Bugzilla, Redmine... and many more...

**Comment by bhaugen** [comment]
What would be really interesting (and I have asked about this in telegram) is if gitlab, wekan, et al, were evolving some standards for doing this kind of integration, so it's not just point-to-point anymore, but is going in the direction that @fosterlynn is trying to lead people to in http://valueflo.ws/

(Like the Web, vocabularies and protocols, if you can obey those, you can connect.)

**Comment by rasos** [comment]
Gitlab also offers a rich set of API calls https://docs.gitlab.com/ce/api/README.html - for example adding time spent for an issue https://docs.gitlab.com/ce/api/issues.html#add-spent-time-for-an-issue which you also can add with the /spent slash command in gitlab. Unfortunately, you can not yet query time spent per issue per author, but there exist several feature requests and I am confident that we will see that soon in gitlab https://gitlab.com/gitlab-org/gitlab-ce/issues/34548

**Comment by skoria** [comment]
I think during September we need to gather ocp task and value requirements for this and start doing things needed to have kanban/kamasi usable by october even if minimally as a first roll out. By then we should have kanban functionality and value equations, but other tools might stay in gitlab for any groups that want it. 

I am starting to imagine some kind of django extension or standalone script that would connect with gitlab and put the data into ocp via the two apis on either side - it could have an admin account, connect from a server and pull the data in in a cronjob. This could be to send more confidential or basic data - like sucking in user profile data to add a member to a group.

If some people are using gitlab primarily (or wekan, but I think if we can get it working for one the other might follow) we link a gitlab account to ocp via fairlogin so for example you edit task progress and add wiki entries in gitlab then sync it by pressing something like "sync to ocp", and this would for example log you in to ocp via fairlogin, get permission from ocp to extract or move the requested data, and then start an import of that data to gitlab.

Likewise if they are on OCP, they could bring information into tasks by populating various fields with data gathered in gitlab. For example a person could import the latest info on a task and update it's progress. This could help with figuring out at what stage something is at and if you can help. So you'd need to be able to gather group and personal data for any groups you were part of in gitlab. If you have edit or view permission you should be able to sync ocp group data with it's corresponding group data or links to things in gitlab or wekan... 

I saw mention of some standard for tasks and issues in the gitlab link so maybe there's a way of making sure we follow or contribute to standards.

**Comment by bhaugen** [comment]
One of the views of the world that @fosterlynn and @ivanminutillo  are thinking about for Kamasi is a personal agent app, which will show you all of your related activities in all your related apps, or at least those that can become part of an open app ecosystem: for example, OCP, Gitlab, Wekan, FairChat, etc. It could be connected to FairLogin as a dashboard.

**Comment by capiscuas** [comment]
Hi @skoria , did you already did some research for how to extract the logged hours from a gitlab task?
https://github.com/kriskbx/gitlab-time-tracker

that opensource project is able to do it, maybe we can collaborate to findout what API methods it is using and convert them in a simple python script for the moment?

**Comment by fosterlynn** [comment]
@capiscuas @skoria If you can make a list of the work data you can get from gitlab, I can do a mapping to the OCP api and see where we can get to.

**Comment by capiscuas** [comment]
Here is the main REST API methods for gitlab:
https://docs.gitlab.com/ce/api/issues.html
https://docs.gitlab.com/ce/api/groups.html
interesting ones to sync with OCP could be:

https://docs.gitlab.com/ce/api/issues.html#set-a-time-estimate-for-an-issue
https://docs.gitlab.com/ce/api/issues.html#add-spent-time-for-an-issue
https://docs.gitlab.com/ce/api/issues.html#reset-the-time-estimate-for-an-issue
https://docs.gitlab.com/ce/api/issues.html#get-time-tracking-stats

https://docs.gitlab.com/ce/api/issues.html#new-issue
https://docs.gitlab.com/ce/api/issues.html#single-issue
https://docs.gitlab.com/ce/api/issues.html#edit-issue
https://docs.gitlab.com/ce/api/issues.html#list-project-issues
https://docs.gitlab.com/ce/api/issues.html#single-issue (here u can get the assignees and the labels  applied to an issue)

for note/comments on issues:
https://docs.gitlab.com/ce/api/notes.html

**Comment by fosterlynn** [comment]
@capiscuas thanks :+1:  

No time today, will give it a shot tomorrow.

**Comment by fosterlynn** [comment]
Here is a draft mapping, with some notes.  https://ethercalc.org/967g1b8ner3d

Main outstanding question: Is there some way to tell who did the work on an issue?  Looks like multiple people can be assigned, and there is one running total on the issue for time spent?

**Comment by capiscuas** [comment]
Hi, I answered in the ethercalc. 
regarding ur question: Yes. the assignees is an array of User objects

**Comment by fosterlynn** [comment]
>Not sure how the total_time_spent is divided or is acumulated together. my advice is that big tasks that require few people to work on... be subdived

That seems like a good option.  Other options: ocp distributes to the project and people manually split the money according to their own formulas; people manage their work through issues in gitlab and just go log their time into ocp.  But I like yours best.  Although, it is up to the team of course.

**Comment by fosterlynn** [comment]
This is resolved by kispagi.
