### ISSUE TITLE
Problems found testing task management in the Work app

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#341]
See also https://github.com/FreedomCoop/valuenetwork/issues/340

## "Extra" tasks: https://testocp.freedomcoop.eu/work/non-process-logging/

When the page first loaded, the Type of work selector showed a list where the first option was Audtio visual work.

I selected https://testocp.freedomcoop.eu/work/agent/96/ FeatureTest for the Context and the Type of work  options changed to a list where the first option was Call center - english arabic. I selected Testing, and entered some hours and a description. I clicked "Save and add more", but it did not save the event (I checked in DJango Admin), but it changed the Type of work selections back to the original list, even for the event I just entered. If I clicked the "Save" button, it did exactly the same as when I clicked "Save and add more". If I clicked the "Save" button again, it finally saved the event, but with the wrong type of work.

## "SImple" tasks: https://testocp.freedomcoop.eu/work/my-tasks/

These worked once, and failed later. When they failed, the autosaves on the "Did" field and hours did not work. The little "saving" and "saved" notices appeared, but they weren't really saved. And when I clicked "Done", the task disappeared from My Tasks, but the work event did not appear in my history nor the project history. It did seem to be saved with the correct number of hours, but not the "Did" description.

**Comment by bhaugen** [comment]
Another problem came up when I assigned a simple task to Lynn. She got the email notification (which is good), but it had the wrong link in the email. https://testocp.freedomcoop.eu/accounting/start/

In other words, the link went to the accounting app, but should have done to the work app my-tasks page.

**Comment by fosterlynn** [comment]
Closing because we don't really want to fix those options, stick to process logging.
