### ISSUE TITLE
Email links

### ISSUE THREAD

**Issue by Al-Demon** [FreedomCoop/valuenetwork#354]
I received an email from a new task because I have the required skills and I think the links to check this task are not correct.... 

The URL that I received  ocp.freedomcoop.eu/accounting and I think this is an error because I can't open this folder by permissions and I can't go directly on the task

We need to check the URLs

Please notice this... and contact for more details if I can...  The email its at bottom of this comment

Thanks

__ _ _

You have received the following notice from FreedomCoop Membership:

sporos requests help that fits your skills:

Work required: Commons Research, Estimated duration: 1 Hour
Due: Sept. 6, 2017

for Process: Write an article about coffee campaign  starting 2017-09-02 ending 2017-09-06

This message has most likely been sent to other individuals. 

You can see the process here:
https://ocp.freedomcoop.eu/accounting/process/19/

To change how you receive notifications, please go to  http://ocp.freedomcoop.eu/notification/settings/

**Comment by bhaugen** [comment]
fixed by https://github.com/FreedomCoop/valuenetwork/pull/391/commits
