### ISSUE TITLE
Make appear notifications settings in the work app

### ISSUE THREAD

**Issue by enricduran** [FreedomCoop/valuenetwork#360]
Any user should be able easily to find the notifications settings and edit it.
Right now notifications settings is accessible from work app, but is not in any menu to access it

https://ocp.freedomcoop.eu/notification/settings/

should be from https://ocp.freedomcoop.eu/account/worksettings/ for example

**Comment by fosterlynn** [comment]
Or in the new UI app.

**Comment by fosterlynn** [comment]
Closing because this is being done now in the new UI.
