### ISSUE TITLE
api-extensions branch problem

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#372]
I created this problem when I did not understand Xavi's rules for the testing branch in test-ocp.  So for some time, I was merging testing into api-extensions to facilitate testocp deployment, but that was wrong.  So there are some non-api commits in api-extensions that are not in master.  I need to figure out how to get them out, assuming they need to be out, before putting api-extensions into production.

**Comment by fosterlynn** [comment]
This is the list.

commit 6ec6f4a4afe95b2e9d472268b82579a2e482f463
Merge: 1fc3c77 68cf2eb
Author: XaviP <pezbaloo@riseup.net>
Date:   Sun Jul 23 00:59:13 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit 1fc3c7760d3dad8e751c29d53503198620ffd89c
Merge: 5aca4a6 7b9bdaa
Author: XaviP <pezbaloo@riseup.net>
Date:   Sat Jul 22 10:08:21 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit 5aca4a6d9f4eb123fa1889f48157c9da66888a00
Merge: d0319be a4d8f8e
Author: XaviP <pezbaloo@riseup.net>
Date:   Sat Jul 22 09:55:46 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit d0319be213a29d5011e726febe5b6ab063a6f366
Merge: 1658a53 945ba10
Author: XaviP <pezbaloo@riseup.net>
Date:   Sat Jul 22 01:58:51 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit 1658a53632b680e8ec475d1772648de301271717
Merge: 697a9dc ee2e4cb
Author: XaviP <pezbaloo@riseup.net>
Date:   Fri Jul 21 22:12:26 2017 +0200

    Merge branch 'new_fee_calculation' into testing


commit 697a9dc958778668a501a50898bf335338063837
Merge: c49c372 93452ed
Author: XaviP <pezbaloo@riseup.net>
Date:   Fri Jul 21 11:56:36 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit c49c37280c1fa9dddb1bcca56ea4c895f141d275
Merge: 86c2183 747816a
Author: XaviP <pezbaloo@riseup.net>
Date:   Thu Jul 20 18:45:49 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit 86c2183d68d7ece8a6800794d4f7b6c317f71291
Merge: d64261c f268289
Author: XaviP <pezbaloo@riseup.net>
Date:   Thu Jul 20 13:01:00 2017 +0200

commit d64261c30b295c4f9573b4e93310df40cbfafee2
Merge: c474fc4 3780b97
Author: XaviP <pezbaloo@riseup.net>
Date:   Thu Jul 20 01:01:09 2017 +0200

    Merge branch 'new_fee_calculation' into testing

commit c474fc46dcb866ce37030cd27e7642810aeced3c
Merge: 6539df8 6201573
Author: XaviP <pezbaloo@riseup.net>
Date:   Mon Jul 17 20:50:55 2017 +0200

    Merge branch 'delete_faircoin_fields' into testing

commit 574f90d1929c782e79fc3ee7828afc322f8d3dbe
Merge: 991317d 3f15fa1
Author: XaviP <pezbaloo@riseup.net>
Date:   Wed Jul 12 12:30:06 2017 +0200

    Merge branch 'faircoin_models_onlyfields' into testing

commit 991317dd3085555c548b80f54c6979414b8428c1
Merge: 4c7b9c9 632b192
Author: XaviP <pezbaloo@riseup.net>
Date:   Wed Jul 12 02:34:14 2017 +0200

    Merge branch 'faircoin_models_onlyfields' into testing

commit 4c7b9c9a45d74c566bc049f04d4298c895610630
Merge: 6c83b55 a3f50a3
Author: XaviP <pezbaloo@riseup.net>
Date:   Tue Jul 11 15:34:20 2017 +0200

    Merge branch 'faircoin_models_onlyfields' into testing

commit 6c83b550ea58458defa49a249a70317840866ab9
Merge: fd66f0e 1e0ed0f
Author: XaviP <pezbaloo@riseup.net>
Date:   Tue Jul 11 14:04:11 2017 +0200

    Merge branch 'faircoin_models_onlyfields' into testing

commit fd66f0ec7dc66c82750ffa6c87f6c667723de755
Merge: b452e8f b55ff3d
Author: XaviP <pezbaloo@riseup.net>
Date:   Tue Jul 11 12:06:13 2017 +0200

    Merge branch 'faircoin_models_onlyfields' into testing

commit b452e8f65b3d31c0fe94303cb348bb49dba6331a
Merge: 093ae10 7c1474e
Author: XaviP <pezbaloo@riseup.net>
Date:   Tue Jul 11 09:44:35 2017 +0200

    Merge branch 'faircoin_models_onlyfields' into testing


commit f692fbb5627a3f9264fbf98036c81f71420320b2
Author: Guillermo C <hola@escanda.io>
Date:   Thu Apr 6 10:37:09 2017 +0200

    added password check and more tests

commit ea799cacc8a56883a64493b0e59137bb2230838d
Author: Guillermo C <hola@escanda.io>
Date:   Wed Apr 5 12:52:17 2017 +0200

    convert input into simple mutation and minor fixes

commit c7a1513ac6e53f15966a03c9bce40171c892022d
Author: Guillermo C <hola@escanda.io>
Date:   Sat Apr 1 17:05:49 2017 +0200

    first steps in jwt authentication

**Comment by fosterlynn** [comment]
After a bunch of reading, I think I want to use "git revert" to fix this.  It will create opposite commits to the ones I want to remove that were never put into master.  This will keep it cleaner for downstream forks.(LearnDeep has forked this and already merged api-extensions branch.  They don't care about faircoin, which is what most of these commits are about, so they are doing no harm now.)

The alternative is "git rebase", which can remove the extra commits.  But it can cause problems for the downstream fork, and also cause problems if we wanted to pull something from the downstream fork later.

Another plus for "git revert" is that it can reverse the extra commits for the testing branch too, so that testocp can match production.

All of this is assuming that the extra commits are something that never will be wanted in master.  I would really like to verify this with @XaviP !  :pray: 

@bum2 what do you think?

**Comment by XaviP** [comment]
Hi, @fosterlynn:
All development that I did is already in master branch, all my branches are deleted if merged into master (there's only one branch called wallet_app that is still there like a draft of the common interface for different gateways, but has nothing merged into master and it will never has to be merged)
If there are doubts about the integrity of testing branch, you can always delete it and create a new one from the current master, if the suspicious commits doesn't play with db migrations.

**Comment by fosterlynn** [comment]
@XaviP thanks very much! :heart:

**Comment by fosterlynn** [comment]
I have dug a bit deeper now, noticing that most of the differences in commits are merges.  Did a spot check on the code changes in the merge commits, and they are in fact in master already.  Also did a test merge of api-extensions into master, and did a diff that lists different files.  There are none of the files that are involved with XaviP's code.

```
$ git diff master master-test-2 --name-only
docker/valuenetwork/run-all-services.sh
requirements.txt
tox.ini
valuenetwork/api/models.py
valuenetwork/api/schema.py
valuenetwork/api/schemas/Agent.py
valuenetwork/api/schemas/AgentBaseQueries.py
valuenetwork/api/schemas/AgentRelationship.py
valuenetwork/api/schemas/AgentRelationshipRole.py
valuenetwork/api/schemas/Auth.py
valuenetwork/api/schemas/Commitment.py
valuenetwork/api/schemas/EconomicEvent.py
valuenetwork/api/schemas/EconomicResource.py
valuenetwork/api/schemas/Exchange.py
valuenetwork/api/schemas/Fulfillment.py
valuenetwork/api/schemas/Organization.py
valuenetwork/api/schemas/Person.py
valuenetwork/api/schemas/Place.py
valuenetwork/api/schemas/Plan.py
valuenetwork/api/schemas/Process.py
valuenetwork/api/schemas/ProcessClassification.py
valuenetwork/api/schemas/QuantityValue.py
valuenetwork/api/schemas/ResourceClassification.py
valuenetwork/api/schemas/Transfer.py
valuenetwork/api/schemas/Unit.py
valuenetwork/api/schemas/__init__.py
valuenetwork/api/schemas/apps.py
valuenetwork/api/schemas/helpers.py
valuenetwork/api/tests.py
valuenetwork/api/types/Agent.py
valuenetwork/api/types/AgentRelationship.py
valuenetwork/api/types/Commitment.py
valuenetwork/api/types/EconomicEvent.py
valuenetwork/api/types/EconomicResource.py
valuenetwork/api/types/Exchange.py
valuenetwork/api/types/Place.py
valuenetwork/api/types/Plan.py
valuenetwork/api/types/Process.py
valuenetwork/api/types/QuantityValue.py
valuenetwork/api/types/__init__.py
valuenetwork/api/types/apps.py
valuenetwork/api/urls.py
valuenetwork/login_required_middleware.py
valuenetwork/settings.py
valuenetwork/valueaccounting/models.py
valuenetwork/valueaccounting/tests/test_explosions.py
valuenetwork/valueaccounting/views.py
```

Conclusion:  It is OK to merge api-extensions into master as it is now.  Will do a PR.

**Comment by fosterlynn** [comment]
Closing, will re-open if there is any problem in production.
