### ISSUE TITLE
Suggest improvements for the fake kanban

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#384]
Some links to examples:
* [CIrcular Economy Area](https://ocp.freedomcoop.eu/work/fake-kanban/459/)
* [Common Management Area](https://ocp.freedomcoop.eu/work/fake-kanban/474/)
* [Welcome Area](https://ocp.freedomcoop.eu/work/fake-kanban/455/)

If you want more examples in this space, let me know. Or get the id of the project and replace the last nunber in the URL with that id.

**Comment by MichalisKas** [comment]
I see it as a big improvement is terms of visualizing the work flow. Would like to suggest the following:

1) Two more boards
- "BackLog", unplanned work, where groups may prioritize their tasks. Although we need to see how that differentiates from "Planned". Maybe tasks that are not set exactly in terms of time?
- "Validated" since it is essential step before a task goes in the value distribution process.

2) Wouldn't it be more useful if we could have separate tasks showing on the boards, rather than whole processes? For example, one process may be too long, while separate tasks inside that could be in several stages.

3) Automatize (as far as we can) the move of the tasks from one board to another. For example, as soon as someone logs some work on a task it should move to "Doing".

4) Define necessary tags. For example, "doing" is not needed as a tag since the task would be in the corresponding board, but perhaps a tag as "assigned" would make more sense in order to know if someone has assigned it or it's just people putting in work hours.

5) I prefer the links to direct to the /process-logging/ page rather than the /order-plan/ one which doesn't provide much info now.

**Comment by fosterlynn** [comment]
>Wouldn't it be more useful if we could have separate tasks showing on the boards, rather than whole processes? For example, one process may be too long, while separate tasks inside that could be in several stages.

This sounds like what Ivan is working on first in Kamasi, at the level of one plan.  I think both are needed.

>Automatize (as far as we can) the move of the tasks from one board to another. For example, as soon as someone logs some work on a task it should move to "Doing".

That is how this works.  Although you probably have to refresh your page.  :)

**Comment by bhaugen** [comment]
@MichalisKas  thanks a lot for the feedback. Some more responses inline below. Lynn read this and thinks it is very complicated. Let me know if it is way too much to grasp and I'll try a shorter and simpler version.

> 1) Two more boards
> - "BackLog", unplanned work, where groups may prioritize their tasks. Although we need to see how that differentiates from "Planned". Maybe tasks that are not set exactly in terms of time?

We'd need to figure out what BackLog means in terms of OCP objects. For example, the work commitments in a process might be unassigned: nobody has committed to do them. So we could differentiate Planned and Committed based on data.

Or it could be something new, that does not exist yet. We have discussed the concept of Intent, which could be a request, offer, or proposal to do something. If we do that, then the BackLog could be proposals that are not yet planned.

> - "Validated" since it is essential step before a task goes in the value distribution process.

As soon as we figure out how validations work in OCP and I have a couple of examples, I will add that column.

> 2) Wouldn't it be more useful if we could have separate tasks showing on the boards, rather than whole processes? For example, one process may be too long, while separate tasks inside that could be in several stages.

What do you mean by Task? Got some examples?

It is a very wiggly word, people mean all kinds of things. We had "Simple Tasks" in OCP, which were also called ToDos, which were just a plan to do something without a process. They started to have bugs in some software updates and we wanted to have only one way to log work in Kamasi, so we're moving to have everything in a Process. 

The structure of a Process goes like this:
* A Process
    * may have many Input requirements. Some of those might be work requirements. That could be one meaning of the word "Task".
        * And each work requirement could have many actual work events logged against it. Each of those might be a "Task" (or not).
    * Plus, a Process can have many unplanned work events logged against it. Are those also "Tasks"?

All of that info is on the process logging page, linked to the process on the kanban board. How much of it would you like to see on the board itself?

> 4) Define necessary tags. For example, "doing" is not needed as a tag since the task would be in the corresponding board, but perhaps a tag as "assigned" would make more sense in order to know if someone has assigned it or it's just people putting in work hours.

I added the "doing" note in the "Doing" column because not all of the processes in a plan would not necessarily have been started. A plan goes into the Doing column when any of its processes has been started.

We don't have any text labels or tags in OCP yet. We do understand that people want them, and are waiting for more clarity on where they go and what they will be used for before doing anything. As you can see from the Process structure above, it's not as simple as Gitlab or Wekan. We're trying to develop a whole economic system, which requires more structure and logic and interconnections.

> 5) I prefer the links to direct to the /process-logging/ page rather than the /order-plan/ one which doesn't provide much info now.

The links to the processes within the plans go there now. I thought about also using the process link for the plan link,, too, when the plan has only one process, which is usually the case now. And then maybe just show the process, ditch the plan from the display altogether unless it has more than one process. Would that make sense? Or would it be confusing? Could also add icons to show which is a plan and which is a process...?

**Comment by MichalisKas** [comment]
1. "BackLog" in my opinion should be more close to "Intent", as you say, and a space where we can prioritize tasks e.g. by dragging them up and down the board. Anyway, I agree that this is a subject to be clarified in OCW first.
Also the "Commited" board wouldn't make much sense for me, since we allow work to be added (means "Doing") regardless if people have assigned to it or not. Please correct me if I'm wrong.

2. I am not sure if these misunderstandings come from my luck of good english or ocp terminology ;-)
Anyway, I mean Task as a work event, planned or unplanned probably. For example, our monthly facilitation process may have 10+ tasks related to it. Some of them would be in "Doing", others in "Done" and so on.

> I added the "doing" note in the "Doing" column because not all of the processes in a plan would not necessarily have been started. A plan goes into the Doing column when any of its processes has been started.
That confused me... since I see Planned Processes in the boards now. But anyway my point is to be able to include the smaller parts in there, such as work events or separate tasks.

> We don't have any text labels or tags in OCP yet.
So, that green Doing text that appears now is not a label?
I agree we should work on labels though.

> I thought about also using the process link for the plan link,, too, when the plan has only one process, which is usually the case now. And then maybe just show the process, ditch the plan from the display altogether unless it has more than one process.
Better this way I think.

**Comment by bhaugen** [comment]
> 1. "BackLog" in my opinion should be more close to "Intent", as you say, and a space where we can prioritize tasks e.g. by dragging them up and down the board. Anyway, I agree that this is a subject to be clarified in OCW first.

I won't implement dragging and dropping in the fake kanban. Leave that for Kamasi. But we might want to implement priorities. Sounds like priority means to you absolute sequence, like a position in a column, instead of high-medium-low or a priority number where several items could be Priority 1? If so, if we add that column, I could do up and down arrows to move items up and down on the list.

> Also the "Commited" board wouldn't make much sense for me, since we allow work to be added (means "Doing") regardless if people have assigned to it or not. Please correct me if I'm wrong.

No, you are correct. But it's a difference in process status if somebody has committed to work on it than if nobody has done anything.

> 2. I am not sure if these misunderstandings come from my luck of good english or ocp terminology ;-)
Anyway, I mean Task as a work event, planned or unplanned probably. For example, our monthly facilitation process may have 10+ tasks related to it. Some of them would be in "Doing", others in "Done" and so on.

Ok, by "Task" you mean work requirements? So yes, one Process can have many work requirements.

>> I added the "doing" note in the "Doing" column because not all of the processes in a plan would not necessarily have been started. A plan goes into the Doing column when any of its processes has been started.

> That confused me... since I see Planned Processes in the boards now. But anyway my point is to be able to include the smaller parts in there, such as work events or separate tasks.

Ok, I'll try that soon and we'll see how we like it or if it's just clutter. Take a look at the process logging page, too, and see how much of that you want to see on the kanban board.

>> We don't have any text labels or tags in OCP yet.

> So, that green Doing text that appears now is not a label?

No, that means somebody has logged some work (so it's started), but not yet Done.

> I agree we should work on labels though.

Discussion to come in a separate issue.

>> I thought about also using the process link for the plan link,, too, when the plan has only one process, which is usually the case now. And then maybe just show the process, ditch the plan from the display altogether unless it has more than one process.

> Better this way I think.

The way it is now? Or the way I suggested? Or some other way?

**Comment by bhaugen** [comment]
I'll create a separate Labels and Tags issue, too, unless somebody else beats me to it. It will have some sub-issues like the priority one.

**Comment by MichalisKas** [comment]
Priority can be either in a "point system" or more absolute in a "list". I think we need more opinions on that, but still you can implement what is easier for you if not too much pain.

> No, that means somebody has logged some work (so it's started), but not yet Done.

My point is why do we need to point that as a green text also, while the process is already in the "Doing" board.

> The way it is now? Or the way I suggested? Or some other way?

The way you suggested.

> Ok, I'll try that soon and we'll see how we like it or if it's just clutter. Take a look at the process logging page, too, and see how much of that you want to see on the kanban board.

I'll certainly do that... I feel I need it! ;-)

**Comment by bhaugen** [comment]
> My point is why do we need to point that as a green text also, while the process is already in the "Doing" board.

Some of my test data had more than one process in the same plan, some of them "doing" and some not. I put the plan in the Doing column if any of the processes had started, and thought was more clear to show which processes were and were not "doing" themselves. Make sense?

Although I suppose it only makes sense when you have more than one process in different states...

**Comment by bhaugen** [comment]
@MichalisKas - I implemented this change (but not pushed or deployed yet):
>  I thought about also using the process link for the plan link,, too, when the plan has only one process, which is usually the case now.

But did not implement this one yet, seemed like it would be confusingly different in visual pattern:
> And then maybe just show the process, ditch the plan from the display altogether unless it has more than one process. 

I have time now to add more details under the processes. Did you look at the process logging pages to see how much of that detail you thought should be included on the board? Like maybe this one?
https://ocp.freedomcoop.eu/work/process-logging/90/
Or this one?
https://ocp.freedomcoop.eu/accounting/process/45/

**Comment by bhaugen** [comment]
@MichalisKas I added a bunch more details to the fake kanban. When it gets deployed, let me know what you think. Other than bugs or something really important, I think I am about done with the appearance. Want to move on to priority:
https://github.com/FreedomCoop/valuenetwork/issues/386
