### ISSUE TITLE
Editing work contributions 

### ISSUE THREAD

**Issue by MichalisKas** [FreedomCoop/valuenetwork#401]
When I edit a work contribution logged

1. the contribution box
2. the list of agents

are not appearing any more. However we should be able to change these any time if a correction is needed, instead of deleting and logging again.

**Comment by bhaugen** [comment]
Seems like a bug. Please point me to the page where you are trying to change the contribution?

Also, if it is your contribution, you used to be able to change it from a link on your profile page, but that link seems to be broken. I'll see if I can fix that bug, too.

**Comment by MichalisKas** [comment]
This happen to every work contribution I've logged when I try to change/edit it.

![screenshot-2017-11-10 open collaborative platform process ce facilitator s work november 2017 starting 2017-11-01 ending](https://user-images.githubusercontent.com/20679274/32649545-1c331002-c603-11e7-8a3a-eeced2e26cc3.png)

That window that appears should also include the 'is contribution' box, as also the list of agents.

**Comment by bhaugen** [comment]
Ok, not a bug. MIssing features. We've never allowed anybody to change who did the work, because we assumed that the person who did the work also logged the work, and nobody else should change what they did.

Re the "is contribution" field, or whatever we rename that to. Let's say we rename that to "validated". I think we should set that whenever or wherever the validations happen. Like, right now, work events default to "is contribution". We could change the default to "validated==False".

Does that all make sense? And if we made that last change, is it worth adding that field to this work event change form?

Also, what is the use case for changing who did the work?

**Comment by fosterlynn** [comment]
About the "is contribution" flag, I think that has a different meaning from "validated", and OCW needs both.  "is contribution" is used for defining if the worker wants it to be paid or volunteer; "validated" is, well, validated.  But changing the name of "is contribution" is of course a good idea.  

Validation I think needs its own app, or at least a separate feature, when this last experience is summarized and people decide how they do want to validate.

I could definitely see including the "is contribution" on the edit modal, it is easy to mess up.  The person, I don't know,

**Comment by bhaugen** [comment]
Ok, @fosterlynn -you are correct.

**Comment by MichalisKas** [comment]
Agree, that contribution check box should be renamed to something like "Voluntary" and be un-checked by default. That would reverse the logic we use so far though (as checking means paid), so needs to be reversed in Kispagi also.

> MIssing features. We've never allowed anybody to change who did the work, because we assumed that the person who did the work also logged the work, and nobody else should change what they did.

Agree with that also, but

1. If you create a work commitment now you are free to choose whichever agent
2. Might be a useful feature if we decide to allow it for coordinators or admins.

**Comment by capiscuas** [comment]
>Agree, that contribution check box should be renamed to something like "Voluntary" and be un-checked by default. That would reverse the logic we use so far though (as checking means paid), so needs to be reversed in Kispagi also.

I agree with teh Voluntary rename proposal.
Also I would ask if OCP could show in the process view the value of this flag in the view, currently it's hidden.

**Comment by fosterlynn** [comment]
I would suggest we don't reverse the meaning.  (We'd have to leave it the same in the database anyhow, because of past work logged.  And there is a lot of code that looks at it.)

Just come up with something that works, like "Request payment" or something like that.

**Comment by capiscuas** [comment]
Request payment it's quite explicit. I agree with it. 
Is it feasable to show it also in the view?

**Comment by fosterlynn** [comment]
>Is it feasable to show it also in the view?

Yes, good idea.

Although, always a question of what to do now in OCP, with the new kamasi UI coming at some point.  And of course having an actual OCP dev would help a lot, Bob offered to fix emergency bugs temporarily, but he can't spend full time on this.

**Comment by fosterlynn** [comment]
Completed and in production.

**Comment by fosterlynn** [comment]
Re-opening to do the re-name of the is_contribution field in Log Unplanned Work

**Comment by fosterlynn** [comment]
Fixed (by Bob) and PR.
