### ISSUE TITLE
Redirects to make things easier for work users

### ISSUE THREAD

**Issue by skoria** [FreedomCoop/valuenetwork#403]
If a link is followed when not logged in, like the following https://ocp.freedomcoop.eu/work/process-logging/134/

once logged in you are redirected to the homepage. Is it possible to store this initial link and redirect there instead? Similarly when you are logged in but don't have permission to access a page, because you aren't in that project, could it give you the join link for that project?

**Comment by bhaugen** [comment]
This is possible. That is how NRP worked. Got broken somewhere in OCP development. Good job for a new programmer.
