### ISSUE TITLE
How to think about validations economically

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#411]
# What validations mean economically
See also https://github.com/FreedomCoop/valuenetwork/issues/390

When you log some work and the field now called Request Payment is checked, that means you are making a claim for payment.

The work event is from you to another agent, usually the same as the context agent for the process you logged the work into, which is usually a project,

**An invoice is another example of a claim for payment.**

Like an invoice, a claim for payment could cover more than one work event. However, logically, it can only cover events either to the same agent or a parent of the same agent.

Also like an invoice, the claim needs to be accepted by the agent who is being asked to pay. Procedurally, Fair Coop has decided to do this acceptance by means of two different people from the team validating the claim.

None of the above requires you to implement this validation according to what it means economically. But that's what it means.

It would be best for the claim to be separate from (but linked to) the work events, both so the claim can cover more than one event, but also because then the payments can also be connected to the claim. One payment might not cover the whole claim, or one payment might cover many claims (like all the claims from one person for November), or the claim might never be accepted or paid, but the person who made the claim might still want to keep track of it. But also the claim needs to be connected to the work events so it can be validated.

## Ideas for implementation

You could actually implement the claims as invoices.

The invoices could be automatically generated from the work events.

You would still need to decide on what level of granularity you want to validate:

- All claims from a person for a month.
- All claims from a person to a particular context (for example, a project).
- All claims from a person for a particular process.
- All claims from a person for a particular work requirement (commitment).
- All claims from a person for a particular type of work and any of those other filters.
- Or, you could do it so that the granularity is flexible, and can be chosen by the person making the claim.  For example, a person on "salary" could claim all their work for the month on one claim.  Or if there are particular people who should validate some work because they know about it specifically, you could generate a claim for that work only.  There could be some notifications for people to validate claims, either specific people or in general.

Lots of options in terms of a procedure and user interface.

**Comment by MichalisKas** [comment]
Validations in Open Coop Work (OCW) space is not so economically oriented, as they are introduced to improve our efficiency, outcome and collective work, but are of course connected to the final payment of the work done. I like the above idea of invoices, but I suspect that a whole new structure has to be created in OCP and not sure how feasible is that in the near future.

Regarding the granularity I believe that some of the levels already listed has to be available, so we should probably think of a -new- field where the user should set that level when the process is created.
Some examples:
1) Monthly (repeated) processes used for fixed salaries/persons --> All claims from a person for a particular process.
2) Task based salaries priced per hour of work --> All claims from a person for a particular work requirement (commitment)
3) Fixed salary based on the completion of a specific project e.g. making a web site --> All claims from a person to a particular context (for example, a project).

**Comment by MichalisKas** [comment]
> There could be some notifications for people to validate claims, either specific people or in general.

This gave me the idea to implement a 'smart' e-mail notification system (I know that the one we now have is very annoying for most og the people so probably need to think in conjunction to that) where, for example, people that participated in the same process or people that are active in the same area during that specific month or any other option we can think of, would be notified to validate a colleague's commitment.

**Comment by bhaugen** [comment]
@MichalisKas 
> Validations in Open Coop Work (OCW) space is not so economically oriented, as they are introduced to improve our efficiency, outcome and collective work, but are of course connected to the final payment of the work done. 

That's all economic. 
> The English words "economy" and "economics" can be traced back to the Greek word οἰκονόμος (i.e. "household management") - https://en.wikipedia.org/wiki/Economy

I find it useful before designing stuff like this to conceptualize it means essentially, so I don't get confused by accidental phenomena.

> I like the above idea of invoices, but I suspect that a whole new structure has to be created in OCP and not sure how feasible is that in the near future.

I think we will want something that groups the various contributions that are seeking to be validated and paid. It will be something like all the contributions of one person for some scope (project, plan, process) for some timespan. And it might want to be connected to some pre-assigned validators.

Whether that happens in OCP as-is, or in Kispagi, or in the new work that Bernini is doing, is to be decided.

**Comment by fosterlynn** [comment]
Closing, validations is written.  Good info is here if we ever decide to do them this way.
