### ISSUE TITLE
Get email addresses for members

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#412]
This would be a way to retrieve email addresses for members of one context agent.  Requested by Christina for Bank of the Commons.  For users with admin credentials only.

Could be a page that returns a csv.  Or could just add the email address to the django admin list page for agents and teach people how to use that to get a csv.  (You can already filter that list by context agent.)

**Comment by bhaugen** [comment]
It would be fairly simple to create an announcement mailing function to OCP.  Good new programmer job. If a new programmer wants to do this, I can walk them through the steps.

**Comment by fosterlynn** [comment]
Let's keep this one to adding the email address to the django admin list page for agents.

**Comment by bhaugen** [comment]
That shd be really easy.  If anybody who wants to do that wants tips, let me know here. Or just do it. It's in https://github.com/FreedomCoop/valuenetwork/blob/master/valuenetwork/valueaccounting/admin.py 
The CSV export has already been done.
