### ISSUE TITLE
Wrong event dates

### ISSUE THREAD

**Issue by MichalisKas** [FreedomCoop/valuenetwork#420]
I've noticed that when I try to log a work event in my monthly facilitation process, which is created by a recipe, the predefined date is set to some days prior to the current one.
![screenshot-2018-1-8 open collaborative platform process ce area facilitation to january 2018 michalis starting 2018-01-01 1](https://user-images.githubusercontent.com/20679274/34670165-d13fdfe0-f47d-11e7-961e-e576af206fbb.png)

The usual case, which happens in every other process, is that the predefined date should be the current one. So I am suspecting that this bug has to do with the fact that my recipe has been used for creating the process a few days after the actual starting of the month.
For example, I've used that recipe https://ocp.freedomcoop.eu/accounting/xbomfg/130/
to create my monthly facilitation process for January 2018 https://ocp.freedomcoop.eu/accounting/order-schedule/221/ not on the 1st of the month but on the 2nd.
Not sure if that has to do anything, but it is strange.

**Comment by MichalisKas** [comment]
UPDATE
Now that I've logged one work contribution, it seems that the issue is fixed. When I try to log new ones to any other requirements the event date is predefined right.

**Comment by bhaugen** [comment]
@MichalisKas I'm not clear if this issue should be closed or left open?

**Comment by MichalisKas** [comment]
I think I've figured out what is happening after all...
I have the OCP tabs always open in my browser and my account logged in. From day to day, when I reopen my browser to work the tabs are there but when I try to log any work event the date is stuck to the last time I used that OCP tab. Only after I refresh the browser's tab it synchs with the current date.

Usually, when you re-open your browser any tabs that are there are refreshed to the current content, but that not seem the case with OCP.
So, do you think it is a problem?

**Comment by bhaugen** [comment]
@MichalisKas thanks for investigating. 
* Do you mean re-starting your browser after it has been shut down, 
* or that your browser has been open and you have not been looking at that tab for awhile and now you do,
* or that your browser has been open but your computer was suspended and you now wake it up?

That happens with a lot of sites for me in the 2nd and 3rd cases, but not the first case. Github, for example. I don't know how the sites that do auto-update do so.

**Comment by MichalisKas** [comment]
Mine is the 1st case, as I've set the browser (latest Firefox on Ubuntu) to start-up with the last tabs.
I've checked several times and when I open the OCP tab is needs a refresh before the date can synch to the current one.
Not sure if it is something you can fix though or needed too anyway.

**Comment by bhaugen** [comment]
> Not sure if it is something you can fix though or needed too anyway.

Not something I know how to fix. If it matters, somebody could do some research on how to solve the problem.
