### ISSUE TITLE
Processes without plans don't appear in kanban views

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#421]
See https://ocp.freedomcoop.eu/work/fake-kanban/713/
vs https://ocp.freedomcoop.eu/work/agent/713/ which shows 3 active processes.

I think this is because they do not have plans. The fake-kanban at east gathers plans, and so processes without plans will not appear. I assume that will be true of the new kanban UI at this stage, too.

We should do something. Either make sure all processes have plans, which is not the case now, or gather the processes without plans too, which will slow down and complicate the code, but maybe not too badly.

**Comment by ivanminutillo** [comment]
I think that as we did for commitments we should do also for processes.
No more simple task - no more process without plans...

**Comment by bhaugen** [comment]
We'd need to add plans to the existing processes that lack them, and then make sure whatever function that is creating the processes automatically adds a plan.

**Comment by ivanminutillo** [comment]
Do we have an approximation of the total amount of processes without plans?
Maybe we can reorganize inside any area to create proper plan with processes inside...

**Comment by bhaugen** [comment]
> Do we have an approximation of the total amount of processes without plans?

No. Somebody with access to the server could find out from the django shell, or we could add something to the process django admin page to find them. That last method might be the best. Then we could fix them at the same time without needing server access.

**Comment by fosterlynn** [comment]
This is fixed going forward.  It is possible someone could create a plan in OCP that would not show up in Agent, but if so that will be fixed by hand.  Closing.
