### ISSUE TITLE
Cannot init electrum network

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#43]
https://testocp.freedomcoop.eu/accounting/resource/14/
AssertionError
Exception Value:	
Can not init Electrum Network. Exiting.
Exception Location:	/home/ocp/app/valuenetwork/valuenetwork/valueaccounting/faircoin_utils.py in init_electrum_fair, line 14

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
