### ISSUE TITLE
Should I change notification emails from opt-out to opt-in?

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#433]
I think I can make notification emails opt-in instead of opt-out as they are now. (They are now opt-in because that's how they were for Sensorica, and FreedomCoop inherited those settings.)

Opt-out means you get the email if you do not change your settings to deselect that notice type.

Opt-in means you will not get the email unless you change your settings to select that notice type.

Here's what the settings look like:
![screenshot from 2018-02-22 08-42-38](https://user-images.githubusercontent.com/117439/36599685-d138880a-1875-11e8-970b-3ef8fce25bc5.png)

The default in the notification system now is to send the email. I think I can change the default to not send the email unless the user selected to get it.

I think I can also change all the existing settings for all the existing users to deselect (turn off) all notice types.

Please think about this and let me know either here or in telegram if you think I should do it.

Note that in #432 we are adding those settings to the new UI, so everybody will be able to change them there.

**Comment by MichalisKas** [comment]
For the current set-up I think opt-in method is better, as almost all members all complaining about too many notification e-mails, usually with no useful data.

A next step would be to set up a default notification scheme according to the profile of the user (admin, coordinator, participant etc). But only after we fulfil some other tasks, like:
- Concrete and meaningful set of skills.
- Define user roles and permissions.
- Re-write the notification e-mail's template.

**Comment by bhaugen** [comment]
@MichalisKas I agree with all that. I also assume that means I should change the current setup to opt-in, which I would do at the same time as the new UI is ready for people to change their notice settings.

**Comment by fosterlynn** [comment]
I think (lacking any opposing views) we can say it should be changed to opt-in.  Will be done in conjunction with deploying the new notification setting feature.
