### ISSUE TITLE
Comments list

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#446]
Here is a view in django admin of the comments: https://ocp.freedomcoop.eu/admin/django_comments/comment/ - filterable by date.

From Christina: Would be lovely to have this option as coordinator of a project!

We would need to work with Christina and other admins to get more detailed requirements for this.

**Comment by bum2** [comment]
that's from the time the notifications were not working and so to have the whole list was useful, but the notifications were solved and the coordinators receive an email for every request or comment, so imho there's no need to make nothing about this. I close the issue but please reopen if needed.
