### ISSUE TITLE
Security issues on freedomcoop agents (Collectives)

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#473]
When a agent have an open project to the ecosystem (Showed in "Projects you can join"
![image](https://user-images.githubusercontent.com/19220653/44804462-a92aea80-abc1-11e8-917c-27b7353d0179.png)

 and you want to join, before to be a member you can edit (and crash!!) important information of the project as showed here (edit info and membership relations):
![image](https://user-images.githubusercontent.com/19220653/44804525-da0b1f80-abc1-11e8-9a1a-ac1a15ece4dd.png)

you can edit their info as well as change the members relations!!
They only have to see the joining form button:
![image](https://user-images.githubusercontent.com/19220653/44804596-0b83eb00-abc2-11e8-97dc-770042121ba3.png)

**Comment by bum2** [comment]
That is only possible because you are an admin and you can see and do much more things that a normal user. Please try to do that with a normal user and reopen the issue if you see a security issue!
