### ISSUE TITLE
Can't change work profile

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#475]
In the Coop Admin app, profiles are changeable. In https://ocp.freedomcoop.eu/work/profile/ they are mostly not changeable. They should be changeable by the profiled person.

I'm labeling this as a bug.

**Comment by bum2** [comment]
That was solved long ago, let me find the commits and close the issue...
Yes, the commit https://github.com/FreedomCoop/valuenetwork/commit/d4c39049db784bb23119333fc9a06395f9c9a11f was solving that issue, if it happens such an issue please reopen and warn me via telegram
