### ISSUE TITLE
fix staging postgresql encoding

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#493]
The encoding-collation of the postgresql db at staging is ascii and should be utf-8.
The error comes on migrate: `value too long for type character varying` refering the symbol field of the Unit model, with just one char, but needs to be a unicode single char.
Probably is needed to create again the db...

**Comment by Xicnet** [comment]
This should be fixed. Please, check and close if applies or bounce back to me.

Just for the record, these were the steps:

sudo -u postgres psql postgres

then in psql console execute sequence of commands:

update pg_database set datallowconn = TRUE where datname = 'template0';
\c template0
update pg_database set datistemplate = FALSE where datname = 'template1';
drop database template1;
create database template1 with template = template0 encoding = 'UTF8';
update pg_database set datistemplate = TRUE where datname = 'template1';
\c template1
update pg_database set datallowconn = FALSE where datname = 'template0';

(press Ctrl-D to quit from psql)

on the shell, still as postgres user, did:

postgres pg_dump --encoding utf8 ocpdb -f ocpdb.sql
dropdb ocpdb
createdb -E utf8 ocpdb
psql -f main.sql -d ocpdb

**Comment by bum2** [comment]
Thanks! the issue is solved...
