### ISSUE TITLE
Account History (Faircoin wallet module) show a error message. test enviroment

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#495]
Defect ID DF_FCM_07.
Test case: Check the Account History link works properly. Result: It shows an error when click on the link:
https://testocp.freedomcoop.eu/faircoin/faircoin-history/170/

TypeError at /faircoin/faircoin-history/170/
'FaircoinAddress' object is not callable
Request Method:	GET
Request URL:	https://testocp.freedomcoop.eu/faircoin/faircoin-history/170/
Django Version:	1.11.16
Exception Type:	TypeError
Exception Value:	
'FaircoinAddress' object is not callable
Exception Location:	/home/ocp/app/valuenetwork/valuenetwork/valueaccounting/service.py in include_blockchain_tx_as_event, line 333
Python Executable:	/usr/bin/python
Python Version:	2.7.9
Python Path:	
['/home/ocp/app/valuenetwork',
 '/home/ocp/app/env/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/dist-packages/django_mptt-0.8.6-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/home/ocp/webapp/env/lib/python2.7/site-packages',
 '/home/ocp/webapp/valuenetwork/']
Server time:	Sun, 5 May 2019 17:15:50 +0000

Traceback
Environment:

Request Method: GET
Request URL: https://testocp.freedomcoop.eu/faircoin/faircoin-history/170/

Django Version: 1.11.16
Python Version: 2.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_comments',
 'pinax_theme_bootstrap_account',
 'pinax_theme_bootstrap',
 'forms_bootstrap2',
 'django_extensions',
 'easy_thumbnails',
 'pinax.notifications',
 'corsheaders',
 'rest_framework',
 'graphene_django',
 'captcha',
 'fobi',
 'fobi.contrib.themes.bootstrap3',
 'fobi.contrib.themes.foundation5',
 'fobi.contrib.themes.simple',
 'fobi.contrib.plugins.form_elements.fields.boolean',
 'fobi.contrib.plugins.form_elements.fields.checkbox_select_multiple',
 'fobi.contrib.plugins.form_elements.fields.date',
 'fobi.contrib.plugins.form_elements.fields.date_drop_down',
 'fobi.contrib.plugins.form_elements.fields.datetime',
 'fobi.contrib.plugins.form_elements.fields.decimal',
 'fobi.contrib.plugins.form_elements.fields.email',
 'fobi.contrib.plugins.form_elements.fields.file',
 'fobi.contrib.plugins.form_elements.fields.float',
 'fobi.contrib.plugins.form_elements.fields.hidden',
 'fobi.contrib.plugins.form_elements.fields.input',
 'fobi.contrib.plugins.form_elements.fields.integer',
 'fobi.contrib.plugins.form_elements.fields.ip_address',
 'fobi.contrib.plugins.form_elements.fields.null_boolean',
 'fobi.contrib.plugins.form_elements.fields.password',
 'fobi.contrib.plugins.form_elements.fields.radio',
 'fobi.contrib.plugins.form_elements.fields.select',
 'fobi.contrib.plugins.form_elements.fields.select_model_object',
 'fobi.contrib.plugins.form_elements.fields.select_multiple',
 'fobi.contrib.plugins.form_elements.fields.select_multiple_model_objects',
 'fobi.contrib.plugins.form_elements.fields.slug',
 'fobi.contrib.plugins.form_elements.fields.text',
 'fobi.contrib.plugins.form_elements.fields.textarea',
 'fobi.contrib.plugins.form_elements.fields.time',
 'fobi.contrib.plugins.form_elements.fields.url',
 'fobi.contrib.plugins.form_elements.test.dummy',
 'fobi.contrib.plugins.form_elements.content.content_image',
 'fobi.contrib.plugins.form_elements.content.content_text',
 'fobi.contrib.plugins.form_elements.content.content_video',
 'fobi.contrib.plugins.form_handlers.db_store',
 'fobi.contrib.plugins.form_handlers.http_repost',
 'fobi.contrib.plugins.form_handlers.mail',
 'valuenetwork.valueaccounting.apps.ValueAccountingAppConfig',
 'valuenetwork.equipment',
 'valuenetwork.board',
 'validation',
 'account',
 'work.apps.WorkAppConfig',
 'multicurrency',
 'valuenetwork.api',
 'valuenetwork.api.types.apps.ApiTypesAppConfig',
 'faircoin',
 'general',
 'mptt']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'valuenetwork.login_required_middleware.LoginRequiredMiddleware',
 'account.middleware.LocaleMiddleware']

Traceback:

File "/home/ocp/app/env/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/ocp/app/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/ocp/app/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/ocp/app/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/ocp/app/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/ocp/app/valuenetwork/faircoin/views.py" in faircoin_history
  202.             exchange_service.include_blockchain_tx_as_event(owner, resource)

File "/home/ocp/app/valuenetwork/valuenetwork/valueaccounting/service.py" in include_blockchain_tx_as_event
  333.                                         if ev.faircoin_transaction.to_address == resource.faircoin_address():

Exception Type: TypeError at /faircoin/faircoin-history/170/
Exception Value: 'FaircoinAddress' object is not callable

It was reproduced whith user Marotest maybe bcause there was some issues with this user when testing the payment of shares

**Comment by bum2** [comment]
finnaly solved with #bc11fa8, deployed in testing
