### ISSUE TITLE
Check sending faircoin when the quantity is negative. Faircoin wallet Module. Testocp enviroment

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#496]
Defect ID: DF_FCM_06
Test Case: Check sending fc when the quantity is negative

Steps to reproduce:
1. Successful login into Testocp.freedomcoop.eu 
2. Succesfully enter in Faircoin account from profile module 
3. Enter negative value in quantity field     
4. Click on send button

**Result**: Message **Must be at least 0.01 FairCoin is shown** but still allow to click on send button and the confirmation window appear allowing accept the sending but when click doesnt allow to send it.
Function works but improvement is needed

**Comment by bum2** [comment]
hopefully solved with commit 1a5c97db ... reopen if needed

**Comment by Holofractographic** [comment]
Retested and an error ocurred: (there is no pop up window to check before sending and allow to send a negative quantity so the sending get stucked)

KeyError at /faircoin/transfer­faircoins/174/ 'quantity'
Request Method:
POST
Request URL: https://testocp.freedomcoop.eu/faircoin/transfer­faircoins/174/ Django Version:
1.11.16
Exception Type:
KeyError
Exception Value:
'quantity'
Exception Location:
/home/ocp/app/valuenetwork/faircoin/forms.py in clean, line 51 Python Executable:
/usr/bin/python
Python Version:
2.7.9
Python Path:
['/home/ocp/app/valuenetwork', '/home/ocp/app/env/lib/python2.7/site­packages', '/usr/local/lib/python2.7/dist­packages/django_mptt­0.8.6­py2.7.egg', '/usr/lib/python2.7',
'/usr/lib/python2.7/plat­x86_64­linux­gnu',
'/usr/lib/python2.7/lib­tk',
'/usr/lib/python2.7/lib­old',
'/usr/lib/python2.7/lib­dynload', '/usr/local/lib/python2.7/dist­packages', '/usr/lib/python2.7/dist­packages', '/usr/lib/python2.7/dist­packages/PILcompat', '/usr/lib/pymodules/python2.7', '/home/ocp/webapp/env/lib/python2.7/site­packages', '/home/ocp/webapp/valuenetwork/']
Server time:
Thu, 20 Jun 2019 16:02:48 +0000
