### ISSUE TITLE
Improve frontend

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#5]
This issue is about discussing how can be improved the frontend in OCP.

Preliminar questions:
- Is there any template system implemented yet?
- Do we need a graphic dessign coherent with faircoop/getfaircoin/fair-coin sites?
- Which group in faircoop can help us with graphic dessign?

**Comment by bhaugen** [comment]
OCP has an API that could be used now for new UI work. @fosterlynn and I will add API endpoints and features on request. So you should be able to build anything you want on top of the OCP API.
http://nrp.webfactional.com/api/

(What you see there is actually behind the stage of development. Some new stuff has not been deployed yet, because electrum-fair has not been deployed on that temporary server.)

**Comment by fosterlynn** [comment]
>Is there any template system implemented yet?

Django has its own template system, which we use.  But that is the cause of all of our performance problems that we have checked into.  Thus Bob's comment about putting something on top of the API. 
(Not sure if that is what you mean by template system though.)

>Do we need a graphic dessign coherent with faircoop/getfaircoin/fair-coin sites?

Current state: OCP is only partially skinnable.  Could easily do the nav and the buttons.  The rest would need some work to centralize the css.  (This is if you wanted to keep the current view and template Django structure.)  We use Bootstrap, but are still on 2.3.

So a lot depends on if you want to upgrade the UX (user experience) in addition to just sprucing up the looks of the UI.

**Comment by XaviP** [comment]
> OCP has an API that could be used now for new UI work.

This could be good to make an app for mobile, or for connecting with other applications, but I was proposing to style the site. Sorry if I don't use the proper words.

> Django has its own template system, which we use.

> The rest would need some work to centralize the css. (This is if you wanted to keep the current view and template Django structure.)

Yes, this is what I mean when asking for a template system. So, we can work only with css/js for a new styling on the site. What do you thing? No problems of performance this way, isn't it? I'll be with this in mind when we make the admin trainning, planning how to do it.

**Comment by fosterlynn** [comment]
Yes only css, and maybe js.  Sure that would be fine.  And won't make any difference to performance.

If you decide what you would like to change, I will help you figure out where to do it.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
