### ISSUE TITLE
Check Send button works as expected entering quantity and address. Faircoin wallet Module. Testocp enviroment

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#501]
Defect ID: DF_FCM_01
Test Case: Check Send button works as expected entering quantity and address

Steps to reproduce:
1. Successful login into Testocp.freedomcoop.eu 
2. Succesfully enter in Faircoin account from profile module 
3. Enter appropiate values quantity and address  
4. Click on send button

Expected result:
A window show a message to confirm the sending Showing Info about amount and address 
accept or cancel action is required. Once accepted the faircoin is sent

Actual Result: 
When click on send redirects to error message
But faircoins are sent when reload the page

Error Message:
https://testocp.freedomcoop.eu/faircoin/faircoin-history/28/

AttributeError at /faircoin/faircoin-history/28/

'NoneType' object has no attribute 'exchange'

Request Method: 	GET
Request URL: 	https://testocp.freedomcoop.eu/faircoin/faircoin-history/28/
Django Version: 	1.11.16
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'exchange'

Exception Location: 	/home/ocp/app/valuenetwork/valuenetwork/valueaccounting/models.py in show_name, line 12975
Python Executable: 	/usr/bin/python
Python Version: 	2.7.9
Python Path:

**Comment by bum2** [comment]
hopefully fixed with the commit f5e0842 ... reopen if needed
