### ISSUE TITLE
Check the Request Faircoin Address Button works. Payment of shares Functionality. Testocp enviroment

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#502]
Defect ID: DF_PAY_01
Test Case: Check the Request Faircoin Address Button works

Steps to reproduce:
1. Log in testocp.freedomcoop.eu
2. Click on Joining Process 
3. Click on Request Faircoin Address Button 

Expected result:
A unique Faircoin Address is generated

Actual Result:
It creates an address but it show a message:  The agent faircoin address is not from the same wallet!
*When refresh it works

**Comment by bum2** [comment]
That's weird.. it should warn that the fair address is being created and some kind of 'please refresh' text, but this message when the address in not one of the wallet addresses only should appear when that's the case... we try to reproduce the issue and see what can be done.. the code looks ok

**Comment by Holofractographic** [comment]
Retested and message about refresh appear now making it more clear :)
