### ISSUE TITLE
Check if the new user is able to enter the OCP system with new passw for 1st time. Login Module. Testocp enviroment

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#505]
Defect ID: DF_LOG_01
Test Case: Check if the new user is able to enter the OCP system with new passw for 1st time. (New freedomcoop member)

Steps to reproduce:
1. Go to testocp.freedomcoop.eu 
2. Enter valid username 
3. Enter new password created 
4. Click on Log in Button 

Expected result:
The user go to Home page

Actual Result:
Redirects to home page but dont see they have to request the faircoin address to see the payment info box. *It passes de test but improvements are requested

**Comment by bum2** [comment]
solved with commits like 45ffdd725 ....

**Comment by Xicnet** [comment]
Please, check how it looks now. It might be possible to improve it still more, but if it's fair enough feel free to approve or bounce back to us.

**Comment by Holofractographic** [comment]
Retested and is much more clear an easy now :)
