### ISSUE TITLE
Check if form is sent if put a different number of shares than minimum required (Collective). Registration Module. Testocp enviroment 

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#506]
Defect ID: DF_REG_01
Test Case: Check if form is sent if put a different number of shares than minimum required (Collective Accounts) 

Steps to reproduce:
1. Go to testocp.freedomcoop.eu 
2. Click on JoinFreedomcoop Button 
3. Fullfil the form adding less shares than required (collective accounts)
4. Click on Submit Button

Expected Result: 
A message requering fulfill fields appear
The form is not sent

Actual Result:
It allow to send the form with 1 share (less than minimum required)

Screenshot (admin module)
![DF_REG_05](https://user-images.githubusercontent.com/19220653/58012203-3ddccc00-7af4-11e9-80ca-41893b00d0d2.png)

**Comment by bum2** [comment]
needs to be solved via JavaScript in the custom script for the project, because is a custom behavior for FdC... no commits will solve this, just needs to include this js behavior in the PROJECTS_LOGIN object at local_settings.py

**Comment by bum2** [comment]
i did a change in the custom js for FdC membership form at testocp, and now this minimum shares should be forced... please retest and reopen if needed

**Comment by Xicnet** [comment]
This is ready to do the final test and close if applies.

**Comment by encosianima** [comment]
I did follow instruction as Holofractografic commented on May 20 and, when selecting collective account, the number of shares is forced to be 2 (or more).

**Comment by Holofractographic** [comment]
Retested and works fine. Close the issue
