### ISSUE TITLE
Renew ssl cert of staging server

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#510]
Just this sysadmin task of renewing the cert... It exired some days ago but it allows to put an exception, so it didn't block us, but will be good anyway to facilitate the testing.

**Comment by Xicnet** [comment]
It's done. Please, test and close this to confirm.

**Comment by encosianima** [comment]
Apparently there's still an issue with certificate when opening staging:
 http://staging.freedomcoop.eu/cgi-sys/suspendedpage.cgi

**Comment by Xicnet** [comment]
That domain is pointing to an older server I think:

rama@xin ~> host staging.freedomcoop.eu
staging.freedomcoop.eu has address 159.100.184.115

Let's talk in pm to arrange this setup.

**Comment by bum2** [comment]
> Apparently there's still an issue with certificate when opening staging:
> http://staging.freedomcoop.eu/cgi-sys/suspendedpage.cgi

There's no such a subdomain like this... there's ocpstaging.freedomcoop.eu which works fine.

**Comment by bum2** [comment]
Anyway, just to write it somewhere, I also like the staging.freedomcoop.eu subdomain, but it can refer to the testing of the wordpress associated to the main freedomcoop domain (we haven't) and i accepted the proposal of ocpstaging (or stagingocp) as subdomains... it really doesn't matter!

**Comment by bum2** [comment]
What will be good is to setup a staging.bankofthecommons.coop (or ocpstaging or stagingocp) but with the botc domain, just pointing to the same staging server. This way we can also test that the multiple domain feature works good and also to test other stuff related botc.

**Comment by encosianima** [comment]
Well, yes a staging freedomcoop. eu would be good, is the issue to be addressed to our FC sysadmins?

**Comment by bum2** [comment]
> Well, yes a staging freedomcoop. eu would be good, is the issue to be addressed to our FC sysadmins?

imo, is not needed, because we already have ocpstaging.freedomcoop.eu and it works (so properly setup by the sysadmins). 

To really have the same 'double domain' setup in staging, what is missing is the botc part, so a ocpstaging.bankofthecommons.coop will fit (keeping the same nomenclature).

That's the easy solution, the other approach is to change everything into staging.domain subdomains (all popinting to the same ip), and i can help, but is more work.

**Comment by encosianima** [comment]
of course we have already ocpstaging.freedomcoop.eu, but as you said, I'm quoting from above message " I also like the staging.freedomcoop.eu subdomain, but it can refer to the testing of the wordpress associated to the main freedomcoop domain (we haven't)" I understood you suggested to point (or fix the point of ) staging.freedomcoop.eu to a dev version of WP freedomcoop.eu, which I reckon we don't have.

**Comment by bum2** [comment]
Oh yes, that's wonderful! but i'm not sure about if there's a dev version of the wordpress already or not... we can setup a dev.freedomcoop.eu (or use this staging.freedomcoop) for this purpose: to test wp updates and try experiments before doing so in the wp at production...

**Comment by bum2** [comment]
the ocpstaging cert is solved, so i close the issue... let's open the wp dev version issue elsewhere
