### ISSUE TITLE
Check the quantity if more than in balance. Payment Module. Testocp

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#512]
RETESTING THE FAIRCOIN MODULE
Defect ID: TC OCP-60
Test Case: Check the quantity if more than in balance

Steps to reproduce:

1. Successful login into Testocp.freedomcoop.eu
2. Succesfully enter in Faircoin account from profile module
3. Enter a value higher than on balance
4. Click on send button

Expected result:
In the module show a message: Cant be more than balance:
A window show the message: Insufficient funds confirmed Your request: 100 Confirmed funds: 2. and Accept button

Actual Result:
As pop up window doesnt appear it allow to send it and transaction get stucked: https://testocp.freedomcoop.eu/faircoin/manage­faircoin­account/170/

**Comment by bum2** [comment]
Yes, sorry it was a mistake in the javascript of that page... now solved and deployed in testocp... can you check it again and close the issue if solved? i'm trying to unstuck the failed txs meanwhile..

**Comment by Holofractographic** [comment]
Retested and now works fine again
