### ISSUE TITLE
TemplateSyntaxError at /accounting/edit-stream-recipe/29/

### ISSUE THREAD

**Issue by MichalisKas** [FreedomCoop/valuenetwork#58]
Invalid block tag: ''url', expected 'endblock'

When trying to create a Workflow Recipe for the Resource Type 'Courses'. Manufacturing Recipe seems to work fine though.
![error](https://cloud.githubusercontent.com/assets/20679274/17171497/9e1c3378-53f9-11e6-993a-0988261d08cd.png)

**Comment by bhaugen** [comment]
Fixed, but you might need to wait until @XaviP updates the server code
