### ISSUE TITLE
ValidationError at /accounting/change-resource/28/

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#62]
https://testocp.freedomcoop.eu/accounting/change-resource/28/

In coop work app/ My profile when try to "Manage account" of faircoin and click on change i try to put my current location and save send me this error:

ValidationError at /accounting/change-resource/28/
[u'ManagementForm data is missing or has been tampered with']
Request Method:	POST
Request URL:	https://testocp.freedomcoop.eu/accounting/change-resource/28/
Django Version:	1.8.13
Exception Type:	ValidationError
Exception Value:	
[u'ManagementForm data is missing or has been tampered with']
Exception Location:	/home/ocp/app/env/lib/python2.7/site-packages/django/forms/formsets.py in management_form, line 97
Python Executable:	/usr/bin/python
Python Version:	2.7.9
Python Path:	
['/home/ocp/app/valuenetwork',
 '/home/ocp/app/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/ocp/app/valuenetwork/']
Server time:	Sat, 30 Jul 2016 10:23:23 +0000

**Comment by bhaugen** [comment]
@Holofractographic it looks like it saved the location and then got the error. 
Is this this correct location?
https://testocp.freedomcoop.eu/accounting/resource/28/

Regardless, it's a bug. But if I know the answer to that question, it will help me figure out where the problem is.

**Comment by Holofractographic** [comment]
yes I saved my c urrent location and is the same as in my profile

**Comment by Holofractographic** [comment]
This is what you are asking for?? :)

**Comment by bhaugen** [comment]
Yes, thank you.

I will probably not get this bug fixed today, but soon. Thanks for reporting it.

**Comment by bhaugen** [comment]
@Holofractographic - I have not been able to reproduce this bug. What version of which browser are you using? If you try changing this resource again, do you get the same error?
https://testocp.freedomcoop.eu/accounting/resource/28/

**Comment by bhaugen** [comment]
@Holofractographic never mind, I reproduced the problem. Will fix tomorrow.
