### ISSUE TITLE
error when send some faircoin to an address

### ISSUE THREAD

**Issue by Holofractographic** [FreedomCoop/valuenetwork#63]
Mario tryed to send some faircoin to his address and get an error:

https://testocp.freedomcoop.eu/work/manage-faircoin-account/16/

ProtocolError at /work/manage-faircoin-account/16/
(-32603, u'Server error:   File "./daemon.py", line 59, in fee | NameError: global name \'Decimal\' is not defined')
Request Method:  GET
Request URL:  https://testocp.freedomcoop.eu/work/manage-faircoin-account/16/
Django Version:  1.8.13
Exception Type:  ProtocolError
Exception Value:  
(-32603, u'Server error:   File "./daemon.py", line 59, in fee | NameError: global name \'Decimal\' is not defined')
Exception Location:  /home/ocp/app/env/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py in check_for_errors, line 567
Python Executable:  /usr/bin/python
Python Version:  2.7.9
Python Path:  
['/home/ocp/app/valuenetwork',
 '/home/ocp/app/env/lib/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/ocp/app/valuenetwork/']
Server time:  Mon, 1 Aug 2016 12:45:00 +0000

but when he refresh the page the faircoin are in the address

**Comment by XaviP** [comment]
We are working on it. Thanks for reporting!!

**Comment by XaviP** [comment]
Solved. Closing. Please, reopen if needed.
