### ISSUE TITLE
Add comments inside OCP

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#66]
Either using an embeddable app or make our own comments app

**Comment by skoria** [comment]
I'll look into gnusocial and loomio for starters..

**Comment by bhaugen** [comment]
Loomio has had a feature request (started by me) that they have agreed to for at least 2 years without ever acting on it.

They have a business plan. Embedded Loomio does not fit. I love Loomio and their gang, but I would forget about them for embedded conversations, at least in the short-to-medium term.

You might want to look into https://www.discourse.org/ as well.

**Comment by skoria** [comment]
https://djangopackages.org/grids/g/commenting/

**Comment by bhaugen** [comment]
I have my own (old) fork of django threaded comments.  I wouldn't be afraid of it.

Disqus is actually a django app, but not open source as far as I know.

**Comment by skoria** [comment]
minimum browser/device requirements are high for discourse but apart from that it seems really awesome. 
https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963
https://meta.discourse.org/t/plugin-for-seamlessly-embedding-discourse-in-a-page-as-comments/28452/18
https://wordpress.org/plugins/wp-gnusocial/ there's very little online info on gnusocial but they have embedded their commenting system into wordpress. It's a lot more advanced..

Gnusocial is php, and discourse is js+ruby on rails + postgres. Both cases would need to be installed on a server so they could be connected to django. That said, if you have your own code, maybe it would be the fastest thing to do that works.

**Comment by skoria** [comment]
This task is post launch

**Comment by skoria** [comment]
Actually we talked about it and yes it's needed. Hope those links are enough to figure it out!

**Comment by bhaugen** [comment]
> yes it's needed

Now? Pre-launch? (I saw an earlier comment pass thru that said post-launch. Did that decision get changes?)

**Comment by bhaugen** [comment]
Re Discourse: that first link above says "One important thing to note with this setup is that users have to navigate to your forum to post replies. This is intentional, as we feel that the posting interface on a Discourse forum is currently much richer than what we could embed via Javascript."

E wants all the conversation to happen within OCP, so I think that rules out Discourse.

**Comment by bhaugen** [comment]
Looks like this is the plugin to use: https://github.com/django/django-contrib-comments

**Comment by XaviP** [comment]
I think django-threadedcomments is built on top of django-contrib-comments, so we can work with django-contrib-comments first (pre-launch) and add later django-threadedcomments if we need threaded comments later.
For implementing django-contrib-comments we need to know which model needs to be commented, and a priority list of these objects.

**Comment by bhaugen** [comment]
> For implementing django-contrib-comments we need to know which models need to be commented:
Necessity: a priority list of these models/objects to implement first (pre-launch).

Why don't we figure out where comments should go in the UI, and that will tell us which objects need comments?

**Comment by bum2** [comment]
The comments need for pre-launch is only at the 'Membership Requests' group, for every member (the candidates) is needed a comments thread, for them to self-present initially and receive feedbacks, publically in ocp. Maybe later (post-launch) we can put comments in other places.

**Comment by XaviP** [comment]
I agree @bhaugen 
I've been looking for a good place to insert comments in ocp work app, and I see that for a worker doesn't seems to be much place that other workers will see and can participate together (for ex: MyDashboard, Map, MyProfile are personal (other workers will visit their own ones)). The only place I see is when visiting _MyHistory > [name of the proccess]_ Maybe there some workers sharing the proccess can make comments.
Do you know where can be a good place for comments in work app?

Oh, I see bum2 comment now, crossposting.
Can you link the exact place of 'Membership Requests' group ??

**Comment by bhaugen** [comment]
When somebody new posts a membership request, they get taken to a thank you page. That page could show the request they posted and offer comments from them, and coop admins could ask questions there.
 We could echo all of those comments in email if we wanted.
 That would reduce the integration requirements for comments to one page to start with.
 It wouldn't be a like a forum, it would be like a private conversation between the applicant and the admins.
 If people like that idea for the start of comments, I can create that page today and you can add the comments.
 I'll restrict access to the applicant and coop admins.

**Comment by bhaugen** [comment]
> I've been looking for a good place to insert comments in ocp work app, and I see that for a worker doesn't seems to be much place that other workers will see and can participate together 

When we get planned processes going, those may be worked on by several people and would be a good place for comments.

Likewise simple tasks, which I am not implementing.

But I agree with what I think is now consensus that the MembershipRequest thankyou page is where to start.

**Comment by bum2** [comment]
The approach proposed by @XaviP is another one, and he seems willing to do it. Let's wait his feedback before going ahead with 'thankyou' page coments.

**Comment by bhaugen** [comment]
What's left to do on this issue?

**Comment by bum2** [comment]
Comments are working and styled in the membership-discussion page (see https://github.com/FreedomCoop/valuenetwork/commit/e85951cde393f3775dc9699a05b37cce2d1785fa).
Still we need to filter this page access for the related user only. If i simply change the number in the url then i see other peoples page and comments... we need a stronger condition there to give some privacy to the comments.

**Comment by bhaugen** [comment]
> we need a stronger condition there to give some privacy to the comments.

Restrict to the member and the admins?

**Comment by bum2** [comment]
Yes Bob, exactly.

**Comment by bhaugen** [comment]
Done.

**Comment by bhaugen** [comment]
Does that mean this issue is ready to close?

**Comment by XaviP** [comment]
Closing. Please, add a new issue if new features about comments needed. Now, comments are running ok and restricted as desired.
