### ISSUE TITLE
https

### ISSUE THREAD

**Issue by skoria** [FreedomCoop/valuenetwork#70]
Add HTTPS (do we need to get *.freedomcoop.eu cert for our hosting provider? this means dedicated ip) thus getting rid of the self signed cert and the related error message people get on their browsers.

**Comment by XaviP** [comment]
The self-signed cert is only for testocp. For the production site we are preparing it with letsencrypt, so no security exception will raise in the user's browser.
If you think this is necessary in testocp too, we will need the dedicated IP, but I'm not sure if it's really needed.

**Comment by skoria** [comment]
no we don't need it now - it's fine thanks!
