### ISSUE TITLE
Add submenus to the menu items

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#73]
How to do a Tree of submenus in the main menus, with 2 or 3 sub lists.

**Comment by skoria** [comment]
OCP Member App Frontpage: when user logs-in, now goes to 'my dashboard' (process logging) but will be better to show clearly all the member options: (MENU item tree)
- Order Tasks: (customer)
    · Create demand or tasks
    · Pay work
- Do tasks: (project participants)
    · My unfinished work
    · Take tasks for my skills
    · Log other done tasks
    · History of tasks contributions
- Self-employment or legal coverage:
    · Invoicing
    · contracts
    · titularity
- Trade through FreedomCoop to suport the common with lower taxes:
    · buy via FC
    · sell via FC
- Create and manage a project (project manager)
    · How to create a Project: tutorial guide step by step (ppt slideshow)
    · Create a new project
    · My projects: 
        + creating definition
        + active running
        + done history

**Comment by skoria** [comment]
If this reorganisation works out, we might not need issue #74

**Comment by bhaugen** [comment]
Is this issue ready to close, or at least declare that the pre-launch part is done?

**Comment by bum2** [comment]
Still pending to do the Member's menu and submenus... asap when we have the condition defined

**Comment by bum2** [comment]
Member's menu first version deployed with disabled buttons... when pages are ready i will activate buttons

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.

**Comment by bum2** [comment]
The first version of 'Your Projects' page is merged in master, but still with the submenus i will like to use a 2nd hierachy sub-sub-menu but i'm not able yet to achieve that. Now i can put nested lists in submenus but not real sub-sub-menus.
