### ISSUE TITLE
Add a 'back' button in many subpages

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#74]
Add a 'back' button in many subpages, to return to the initial page with the nav submenu.
Will be better to add tabbed subpages system, so we don't loose the nav options.

**Comment by bum2** [comment]
Any idea on how to keep the second navigation bar (page-nav) when changing subpage? the bad and fast solution is the 'back' button onscreen, but tabs system or a page-navigation bar will be optimal.

**Comment by bhaugen** [comment]
I agree, better nav would be best. Otherwise, breadcrumbs?

**Comment by bhaugen** [comment]
But it would also be good to have some examples of problems you run into where you wanted a back button...

**Comment by bum2** [comment]
I see in the actual app for participants and candidates, there are no subpages. When user became a FCMember, then will have also some of the admin features: my work, my projects, plan work, etc. 
The admins app is where you see the main navigation problems, this happens in many pages:
- Organization (if you go to any subpage you lose the page-navbar)
- Demand (idem)
- Supply (idem)
- My Work (idem)
In the distribution and inventory pages is the same, you'll lose the navigation context (the only way to recover submenus is push the browser back button).
I see the code: `{% if layout.work_panel_headline %}` or similar in the templates and i think is maybe the way you are showing page-navbar. Maybe is only needed to add the same conditition in the other subpages of the main page, so it appears the same nav options in all them.

**Comment by bhaugen** [comment]
Thanks. Good examples. Best thing would still be better nav, but a quick and dirty option would be to duplicate the subnav links from the main page under every topbar tab, like for Organization, 
All Agents Locations All contributions Network diagram Cash Flow Report Value Equations Membership requests

**Comment by bum2** [comment]
If we can't afford to do a page-navbar system, repeating this header will be enough for now.

**Comment by bhaugen** [comment]
Lynn and I are leaving the UI improvements to the Freedom Coop crew.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
