### ISSUE TITLE
Add profile fields

### ISSUE THREAD

**Issue by bum2** [FreedomCoop/valuenetwork#75]
Add profile fields (also in initial form): 
- UseFaircoin profile (url)
- FairMarket shop (url)
- FairNetwork username (string)

**Comment by bhaugen** [comment]
@bum2 -
> UseFaircoin profile (url)

This says it's an URL, but it also says to do something (UseFaircoin profile). What is a Faircoin profile and how should we use it?

**Comment by skoria** [comment]
Here is an example profile on use.fair-coin.org: https://use.fair-coin.org/company/revolt-be-standard/ It's a directory of places that accept faircoin.

**Comment by bhaugen** [comment]
Ok, got it. It means "uses faircoin". Would it apply only collectives? and the URL would be their page in that directory? (Because all the individuals in OCP will use faircoins in OCP.)

**Comment by bum2** [comment]
All this new fields are optional, just to easily track connections in the FC ecosystem. They apply to individuals also. The directory-map UseFaircoin (use.fair-coin.org) is for any producer or service provider accepting faircoin publicly (and physically), not required for ocp (only required for backwards operations, fair to euro support). The FairMarket shops are for the ones selling online.

**Comment by bhaugen** [comment]
I think I understand, and agree.

**Comment by bum2** [comment]
Added the fields in the MembershipRequest model (initial form). 
Pending to add some fields in the user profile.

**Comment by bhaugen** [comment]
Soon I intend to connect the membership request to the worker's profile. We will be able to take any fields from the membership request and show them on the profile page, so that's probably good enough for now.  

But  @bum2  I don't see the new fields in [the model in github](https://github.com/FreedomCoop/valuenetwork/blob/master/work/models.py#L12). Did you commit them to the github repository? And did anybody make a migration for the new fields?

**Comment by bum2** [comment]
Now that we have the new fields (and erased the old ones) in the membership-request model, you'll find the way to put them in the profile, but you know is a subset (not all are necessary to pass to the profile), i hope you already have the list.
There are a few changes today (hopfully tomorrow early are deployed) but only affecting some names, and the Blank=True of 'Languages'.

**Comment by bhaugen** [comment]
The selected fields from the membership request are now shown on the agent profile in the coop node admin app. Here's an example:
https://ocp.freedomcoop.eu/accounting/agent/43/

Should I add this to the member's work app profile, too? In issue https://github.com/FreedomCoop/valuenetwork/issues/86 I suggested that in the work app, the full membership request should be shown on a separate page with comments enabled befween the member and coop admins. What do you think?

And @bum2 - feel free to re-arrange, re-style, or whatever.

**Comment by bhaugen** [comment]
Is this issue ready to close?

**Comment by bum2** [comment]
thanks bob! now is good like this, and we'll see if we can let edit this fields in the membership process page or my profile... step by step

**Comment by bhaugen** [comment]
We probably should them editable by the member. It ain't nobody else's business.

**Comment by bum2** [comment]
Yes of course! in the 'my profile' page i think is the best

**Comment by bum2** [comment]
the other option is in the Membership process page, putting some fields editable, but once becoming a member the whole comments thread page can be nested in the right submenu like historical or resource commenting page. When we can reach internal comunication between members, all this will be managed with the new system, so now it's just to start with a simple feedback tool.

**Comment by bhaugen** [comment]
I think making these fields editable is a different issue with its own priority and we should close this one.

**Comment by XaviP** [comment]
Solved. Please, reopen if needed.
