### ISSUE TITLE
[Translations] Making django.po for spanish language

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#79]
Please, revise [this commit](https://github.com/FreedomCoop/valuenetwork/commit/241b795a02badd2e291984da98534fb5e103bfdc). Running *django-admin makemessages -l es*, django was complaining about a string in valuenetwork/valueaccounting/models.py, which I've changed for generating django.po

**Comment by bhaugen** [comment]
@XaviP I'm not sure what you want me to do.

**Comment by XaviP** [comment]
Just to review "%%" format in the string. If you don't see anything incorrect, that's ok then. Closing.

**Comment by bhaugen** [comment]
Should we replace "%" with "percentage"?

**Comment by XaviP** [comment]
Oh, that's another possibility. The problem was that with an unique "%" inside a string, python thinks that a variable is needed to replace it, and throws a warning when creating a .po file. So, I've been reading about it and they recommend double % to escape it. I think now it's ok, but if you run into problems because of it, we can substitute it for "percentage".
