### ISSUE TITLE
Tasks and work logging

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#81]
# Kinds of tasks in OCP

This is a little complicated, but I think these are necessary complications. But they might not all be necessary at launch time. I'll explain more below.

* **Planned tasks**
    * **Process tasks**, which are work that goes into processes that produce outputs. Those would be planned by a Freedom Coop administrator or a Project Manager. They require what is now called Recipes, and which I believe are being renamed to Task Templates. Planning processes takes a lot of OCP system knowledge.
    * **Simple tasks**, now called Todos, which I think are being renamed to just plain Task.
* **Logging:**
    * **Process tasks** are logged on a process logging page, where people who are working on the task should also log the outputs of the process and any other inputs (materials, equipment use, etc.).
        * Workers on a planned process can also add more tasks, more inputs, and more outputs, or log unplanned work that they did on the process.
    * **Simple tasks** are just logged right on the task itself. You can try them on the [All Work page](https://testocp.freedomcoop.eu/accounting/work/) where they are still called Todos.
    * **Unplanned work** can also be logged. In OCP right now it is called "Non-process logging", but I think it would be better to rename it to "Log unplanned work". 

## Why this complexity is necessary

* Process tasks are necessary if you want to make something that you want to track in OCP. They are also necessary if you want to make something out of some  components, or log the use of equipment or space, or have more than one person working on the same process.
* Simple tasks came up because process tasks take a lot of setup work and system knowledge, and sometimes all you want to do is plan something simple without other inputs and outputs.
* Logging unplanned work is necessary because things happen, and sometimes it is not necessary to plan them first.

# Question

* Should we start the work app with just the simple tasks and logging unplanned work, and save all the process planning for later when we have a project that needs it?

**Comment by bum2** [comment]
I think is good to count always with the process planning option (the hard one) at UI level, but if the simplyfied 'guide' and related ui parts for creating the process planning are not totally clear and ready at launch, perhaps we can show that as a 'coming soon' deactivated feature the first days.

The first needed task is the 'membership request', now testing via 'todo' task type. 
This task can be named 'review candidate proposal for user x'. An admin can take the task (at launch) but for post-launch we can think about a related 'skill' or whatever is best.

I'm not sure if this kind of task is better 'simple' or 'unplanned', which is best? (really fits as 'unplanned' isn't it?)

In that membership process is needed the comments thread (first comment being the 'what to do' field of this task). Perhaps is better to put the comments plugin at the task level (not agent), this affects issue #66

**Comment by bhaugen** [comment]
> I'm not sure if this kind of task is better 'simple' or 'unplanned', which is best? (really fits as 'unplanned' isn't it?)

I think should be a simple task. Unplanned work has no plan in OCP at all. Somebody logs it because they did it and want credit.

**Comment by bum2** [comment]
Ok, got it. Thanks a lot!

**Comment by bhaugen** [comment]
And I'll create this task automatically pretty soon. Maybe tomorrow.

**Comment by fosterlynn** [comment]
>Unplanned work can also be logged. In OCP right now it is called "Non-process logging", but I think it would be better to rename it to "Log unplanned work". 

I'm not sure I like that suggestion.  The real distinction is not planned vs unplanned, but rather is what you explained @bhaugen with Process Tasks above.  Whether work is planned or not, if you need to log outputs and non-work inputs, it must be logged against a process.  The "Non-process logging" is for work that doesn't create anything you need to keep track of, often spreads across projects, sometimes called "overhead" (lousy term).  Things like doing the accounting or cleaning the work space.  But maybe we can think of something better than "non-process logging".

**Comment by bum2** [comment]
i propose 'Log extra tasks' or 'Log other extra tasks' (if 'unplanned' is not the right word)... what you think?

**Comment by fosterlynn** [comment]
I like "Log extra tasks" better.  I'm also OK with "Log unplanned work" as long as we all understand the concepts and implications properly so that when we get process logging we can change it.  Or if everyone but me agrees, then I am happy to withdraw my objection. :)

**Comment by bhaugen** [comment]
I am trying to resist getting into naming arguments, so whatever you all want is ok with me

**Comment by bhaugen** [comment]
Is this issue ready to close?

**Comment by bum2** [comment]
here the commit https://github.com/FreedomCoop/valuenetwork/commit/dc569c7271772ea3563f1ccc9430069db087c174
