### ISSUE TITLE
Draft proposal for a new membership page in the work app

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#86]
1. Connect the member profile in the work app with the membership request. This can be done by the coop admin when they create the agent and user for a new member. I already have a field for this on the MembershipRequest model and can put it on https://testocp.freedomcoop.eu/accounting/membership-requests/

2. Add a "My Membership" page linked to the worker's profile where they can keep track of their membership status, fees, etc etc.

3. Comments could go on that page.

**Comment by bum2** [comment]
Sounds very good Bob! 
The 'my membership' page menu-button can be next to the profile (or as a submenu), and i think is a good place for the comments about the member's economic activity project... the comments anyway will be optimal as an option to add in simple tasks (but only by admins).

**Comment by bhaugen** [comment]
> Connect the member profile in the work app with the membership request. This can be done by the coop admin when they create the agent and user for a new member. I already have a field for this on the MembershipRequest model and can put it on https://testocp.freedomcoop.eu/accounting/membership-requests/

This is done. Next step is to automatically create a task for the coop admin group to handle a new memnbership request.

**Comment by bhaugen** [comment]
I'm working on this now. Creating the automatic task which will also link to a page with the new membership request on it and a form to create a new agent on the same page.
