### ISSUE TITLE
Project managers want to follow all the tasks in their project

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#88]
Project managers can now assign tasks to participants in their project on the My Task page.
part of #80 

But once they assign the task to somebody else, it disappears from My Tasks, because it is no longer their task. So it should go someplace else, maybe a version of the All Work page for the work app that shows only projects that the viewer is associated with.

**Comment by fosterlynn** [comment]
Created a new page for this.  Not yet on the menu.  Needs ajax call to allow only assignment of people who are involved in the project chosen.

We should also refactor this and use the same logic for the node app, I think.

Leaving open for those additions.

**Comment by bum2** [comment]
How is called the page you've done? where i can find? i can try to put it in the menu if we all want...

**Comment by fosterlynn** [comment]
https://testocp.freedomcoop.eu/work/project-work/

**Comment by bum2** [comment]
done! is called 'Your project tasks' in the member's menu...
