### ISSUE TITLE
How to have a user for a group?

### ISSUE THREAD

**Issue by fosterlynn** [FreedomCoop/valuenetwork#90]
From a discussion in telegram, which is reproduced below.  The main question is how to enable a user for a collective.  A couple possibilities suggested: 
1. Change OCP so it allows creation of users for an agent who is not a person.  Figure out how to do the new permissions in this case.
2. Create a person agent who acts as user for the collective and has a name like the group, associate the person agent to the collective.  The person agent can have a user.

We will need to look at the implications of these possibilities, and if there are other possible solutions too.  Possibly can set up both situations in testocp so we can see it more clearly.

**Bob**
The question is, does a collective agent have a user? Or should the users be the members or participants in the collective, the individuals?
A collective can also have a manager, who would also be an indiviual user.
Can have more than one manager.
Everybody can be a manager.
But if a collective has a user itself, what does it mean?
**E**
we already said that some moment
collective member have an user as a member
then this account can create a project
and also can add projects participants
**Bob**
but a collective would not have a user itself, only the indivudals
right?
**E**
the collective also have an user
**Bob**
what does tha tuser mean?
**E**
not matter for the system if is individual or collective
is just the same, is a member of freedom coop
**Bob**
OCP can handle that, but if a collective logs in as a user, who is it?
We would not know.
**E**
wathever the collective give permissions to do
that is not our problem
is an internal question of the collective
**C**
the "collective admin" could be a "role" rather than a user
ie a property of a user
**E**
is both
can do that role in the project of course
**Bob**
collective admin would be an association between an individual agent and the collective.
**C**
and then there could be more than one admin per collective
**Bob**
yes
**E**
yes, anyway
**Bob**
that's how OCP is meant to work
**E**
the point is that all the members of freedom coop should have an user in OCP as members
**Bob**
it is possible for a collective to have a user in OCP, but it would not be necessary
**E**
it is necessary
**C**
the reason why a collective might also need to be a user is because it might need a wallet
**E**
of course, it is necessary, for the relation with freedom coop
wathever they have projects or not inside the system
**Bob**
it can have a faicoin address without having its own user
**C**
hmm, ok
**Bob**
I don't personally care how OCP admins and collectives handle this, I'm just asking questions so people understand how things work and what is possible.

**E**
in CIC collectives have CES accounts, they have gestioCI accounts, they have all what users have
so, in our experience that answer is very clear. Collective which is member have an user
**Lynn**
suggestion: if a collective needs a user (and doesn't have any people who want to register in OCP and be a user), they can create a user called XYZ Project User, and make that an Individual, associate to the project, and everyone can use that user
i mean everyone who logs on as the project
**E**
Sure they can do it. In fact this is how it begins when the register comes from a collective
as first step we create the collective user they require in the form
after they can create a project, and then can add as many projects participants as they need for individual users
then that projects participants can distribute the tasks themselves without involving the collective user in the internal tasks...
if they not want to use the project creation for internal tasks, they can handle the relation with freedom coop, just from that collective user
**Lynn**
does this mean you are agreeing with the suggestion or disagreeing?  don't understand "collective user"
**A**
group user?
**E**
Each user who have fill the collective option in the form is a collective user
**Lynn**
actually i see I wasn't totally clear - i was suggesting creating an extra agent who is an Individual who would have the user credentials
**E**
like now Decentrale
**Lynn**
the system will not now allow you to create users for agents who are not individuals (people) -- if we change that, we would need to see where it matters and make some other changes, and test very well
can we create a Decentrale User agent who is a "person"?
and then create the Decentrale project agent?
otherwise let's create an issue in github
or we can sleep on it too, tomorrow is a new day
**B**
the project as you say is both a user in ocp and then duplicated as a project in ocp (perhaps with the same name) but one is a user and another thing will be called similar is their 'project' in ocp, but this is another kind of object in the system.
**Lynn**
yes, so there are agents - which can be a person or a group (like a project)
every user in OCP has its own agent
which as of now must be a person
**B**
in this case the user (collective) has name similar to the project they will set up for including more people...
at the system level it doesn't matter, no changes needed
**Lynn**
yes, as long as when you say "user (collective)", the agent associated with that user can be flagged as a person.... is this OK?
**B**
the point i need to understand more is:
when the collective user is created, we can assign 'context agent' to the group agent at creation time? so then other members and also participants can be part of it without creating another agent?
**Lynn**
yes, as long as when you say "user (collective)", the agent asso
no, they will be flagged as collective, orgnization, group, etc not a s individual
**Lynn**
in talking about it, let's make sure we are using the words "user" and "agent" in the same way  -- in OCP, there are mainly agents who match people or groups in the real world; users are just credentials, they are not people or groups
agents can do things in OCP
(ok that wasn't clear)
**B**
yes it was
**Lynn**
things that happen in OCP record their agents for all kinds of reasons - they never record their user, users are just so someone can log in, not at all part of the real data
**B**
in any case, a 'user' of this kind (collective type) will be linked to the main group 'agent', created normally with the same name (or similar). Later when a project is created, this user will be the first 'project manager'... its just that the username is not a personal name in this case, but is a regular member and user of ocp.

**Comment by fosterlynn** [comment]
Question: Is part of this requirement a need for privacy for people inside a collective from people outside the collective?

**Comment by bhaugen** [comment]
The only reason collectives cannot have users now is that we put that restriction into the system. I will remove that restriction tomorrow, and then collectives will be able to have users.

But then we will need to figure out what are the permissions for such users....

**Comment by bhaugen** [comment]
This commit https://github.com/FreedomCoop/valuenetwork/commit/153346b7d2ec74221357386d5c7c0b915f5c68dc allows collective agents to have a user.

**Comment by bhaugen** [comment]
What are the permissions for a collective user? 

* Because they are a FC user, they also automatically get a FairCoin adddress. (This is an advantage of having collective users: we don't need to figure out who can manage the FairCoins for a collective, the collective user can.) 
    * But should they have the same limitation as individual users, if they are not a full member, they cannot see their faircoin address or send faircoins to addresses outside OCP?
    * _(note: this rule is not enforced in the OCP code yet.)_
* Do they have Manager permissions for their collective? That is, can they assign tasks to collective members?
* Can managers of collectives where this collective is a member, assign tasks to the collective user?
* Etc. I am sure other permission questions will arise...

**Comment by bhaugen** [comment]
Is this issue ready to close?

**Comment by bum2** [comment]
will try to respond:

- All candidates (individual or collective) have only the hided fair-address, but they are able to send faircoins out (if that makes sense). Lets elaborate on this subject to define how it can be done.
- Yes. Once accepted as member they can create and manage projects, becaming a project manager and able to add participants, candidates or other members to do tasks, and also able to put any user as a project manager, together with the collective user (the first default project manager-creator). All them only see their related projects and agents.
- Yes they can.

**Comment by bhaugen** [comment]
> Once accepted as member they can create and manage projects, becaming a project manager and able to add participants, candidates or other members to do tasks, and also able to put any user as a project manager, together with the collective user (the first default project manager-creator). All them only see their related projects and agents.

This would mean either:
* we let them into the coop admin app, where you can do all that stuff (you cannot do so now in the work app), or
* we add some of those features to the work app.

**Comment by bum2** [comment]
Yes, i want to add this features in work app, but when realising the method of getting a boolean agent.is_FCmember() to filter the menu for this two roles. 
Can you help me doing the 'def' query to see if user is owner of any 'membership share' resource? or point me to how i get the condition in a template? (perhaps not needed a new 'def' function) ...i'm still a bit lost in this.

**Comment by bhaugen** [comment]
The membership share resource has not been implemented yet. Still in talk stages.

But any function you want on agent, I can create, as soon as the logic is clear and the required information is in the system. Whether that be ownership of a membership share, or an association with Freedom Coop or some other organization in OCP, or something else.

**Comment by bum2** [comment]
It's good to be able to query things and add functions, we are urgently needing the one for membership. Can anyone help at creating this resource type in testocp? so we can create the filters in the code... if we get the type, the task or the resource by id we must have the same id in prod ocp...
How we do it?

**Comment by bhaugen** [comment]
There's more to it than creating the resource type and resource. It's a change to whole new membership creation and payment workflow. Needs a full design and implementation. That's why I wrote this as a thought experiment for discussion.

If the current workflow, with the task to pay, which @maro suggested, is good enough for now, maybe we should let this sit and wait. In that workflow, the member would end up with an association with (I think) the FC MembershipRequest group, starting in a candidate status, and graduating to active status when they pay up. All of those association creation and change actions would be manual, done by the coop admin who was handling the request. The promotion to active status would need to wait until they see the faircoin transaction in whatever faircoin address the new member is supposed to send a transaction to.

Does that make sense?

**Comment by bum2** [comment]
Yes Bob, all good for now, then: how to know if the user has payed or not in the actual scheme? perhaps: "see if a task of x type has been done by this user"...

**Comment by bhaugen** [comment]
> how to know if the user has payed or not in the actual scheme? perhaps: "see if a task of x type has been done by this user"...

Somebody would need to look at the transaction history for the account they were supposed to pay into, for example: https://testocp.freedomcoop.eu/accounting/event-history/50/

If all you can see is the address it came from but not the person it came from, then it's a lot harder.

An explicit exchange of membership for payment would make it easy, but would require what I explained a little bit above,  the design and at least configuration of the membership resource, the exchange type, and probably also some code changes. 

So my question remains, is what we got good enough for now, or should we start working on an improved version now. All about priorities.

**Comment by Holofractographic** [comment]
I think is good enough for now, as we say to the members in the guide once they pay the contribution they must click on done in the task, so I can see in the todo that the taks is completed by the new member and check in the faircoin address of Freedom coop to verify they really did it and is well done so with this we complete the proccess

**Comment by Holofractographic** [comment]
For me is more important to work on have ready the comments in order that we can have the interview with new members that are going to have a project or be self employed and other things pending

**Comment by bhaugen** [comment]
Ok, thanks very much for answering my question.

**Comment by bum2** [comment]
the comments are ready in the github last commit, soon in testocp and in prod.
we are a bit off topic, but my main concern is that we need perhaps a checkbox to manually set member or not, but it means a new field, isn't it? 
is needed the property to filter the menu items and pages acording to membership status, how about something like: 
'get the fairaddress of agent and search history of coop account, match and return true'

**Comment by Holofractographic** [comment]
to tech for me!!! hahaaha

**Comment by bhaugen** [comment]
> my main concern is that we need perhaps a checkbox to manually set member or not, but it means a new field, isn't it? 

We already have an association called Member which can be in a "candidate" or "active" state. Will that work? I can give you a method that will tell you whether an agent is a member of a particular group or not, and what the status of their membership is. If that will work, let me know, and I can do it tomorrow.

**Comment by bum2** [comment]
Yes! this will work: only the full members will have the association 'is member of' FreedomCoop group, so other users will be 'participant' of FC_MembershipRequest group but not members of FC. If we use this association type to diferentiate participants or candidates from the members, then it looks easy to finish the condition function and keep on developing the menu and the features for members. Thanks Bob, that's the best way. If you help me defining the function query we'll reach it faster.
Perhaps also we can setup a filter in the 'maintain associations' for FreedomCoop main group, that allows the 'is member of' association type only for admins, so no-one can self register as member. The 'is member of' option can be used for other agents and associations except for FreedomCoop main group (option reserved for admins, only in this case). Does that make sense? is it easy to do?

**Comment by Holofractographic** [comment]
yes Im using it and in membership request they appear as potential so this let us know who is registered but pending to complete the payment of the contribution proccess

**Comment by bhaugen** [comment]
>  in membership request they appear as potential 

@Holofractographic - thanks for the news, but where did you see the word "potential"? I tried to change it to "candidate" everywhere, that's the old internal label, I'd like to change where you saw it, too,

**Comment by bhaugen** [comment]
> If you help me defining the function query we'll reach it faster.

Will the members be active members of Freedom Coop? or just active members of the FC Membership Request group? Or just active members of some group, and we don't use the word "Member" for any other associations?

**Comment by bum2** [comment]
Active members of FreedomCoop. Then we assign 'is member of' FreedomCoop with the 'candidate' status, then when accepted and payed the share we change them to 'active'. That's enough to make the method. Looks good this way! The 'member of' association can be used in many other relations, using the 3 status already set up in the system.

**Comment by bhaugen** [comment]
> Active members of FreedomCoop.

Got it, will do it now.

**Comment by bhaugen** [comment]
It's done, and I think deployed to testocp at least. Be aware that I hard-coded the name "Freedom Coop". If that name changes in the slightest, it won't work anymore.

And the agents need to have a membership association with Freedom Coop. I think they are being connected to that Membership Request group. Not good enough.

Clear?

**Comment by bum2** [comment]
Thanks, is working good. They will be both connected in MembershipRequests group, and also members of FreedomCoop. Once they are active in FreedomCoop they can get out of MembershipRequests. Some day we can automate the process, but now we can do it manually.

**Comment by bum2** [comment]
About the real topic of this issue: if the user is collective and the agent is created as such (organization or whatever plural), then it can't pick any tasks because is not individual?
The point then is to create two agents, one for the user (individual) and one for the 'project'. They will be named very similar, but we can do like: "ProjectName manager" (the user) and "ProjectName" (the project agent, where this user is manager of). This way we don't need to change nothing in the code about 'group users'.
In the new 'Your projects' page will be good to have a precreated context agent (the project), and let managers create sub agents nested to it, so they can selfmanage the sub contexts of his project but not allowed to see or change nothing outside his main project agent.

**Comment by bhaugen** [comment]
I already enabled collective users, so that ship has sailed, although we could call it back.

I am about to respond to @Holofractographic 's request to be able to assign tasks to collective users, right after lunch. So if there are disagreements in the team about this, I'll check back in Telegram for a decision when I am ready to do it. In other words, @bum2 and others, speak now.

**Comment by bum2** [comment]
If you already have such a thing that collective agents can have a user, being a context agent, and assign and take tasks, manage the collective wallet, became project manager, etc. Then we can change again the instructions for admins and the explanations to users. 
Which is then the procedure? create only one agent and one user (and two associations) when is collective? 
Now we can do 2 agents: the project manager with a user, and the project agent without a user.

**Comment by Holofractographic** [comment]
Hi! Im a little bit confused...for collectives must be created a context agent in the case of decentrale I didnt because I treat it as a normal agent, but I think that when is a collective must be a context agent in order that the manager can create new users, tasks, pay the members of this collective, whatever... so this is one important thing related to collectives.

In the other hand we created now two agents, one has a user and we call it decentrale mannager or user as an individual( in order to assign it the task of send the faircoin of the contribution as we couldnt do it as a collective) and a context agent that is decentrale, the collective. The collective is associated as a member of freedom coop as candidate, and the user is associated to the context agent of course and the membership request group also as a candidate. The idea is to create the task for the payment for the user and send the email and the wlecome guide, but there is a doubt: if the faircoin address we are going to use in this case is the address of the user, the manager we are using the "personal address of the manager but not the faircoin address of the project and this has no sense for me because this address is managed by a person not by the collective and the user can need it for other purposes for example to be paid for his work...

So at that point what make sense for me is to create the context agent, the collective, to create the user who is going to manage it but the faircoin address to pay the contribution must be the address of the collective, no the user address, so the mess comes here...because the user as a candidate cant see the faircoin address of the collective and because I dont know if i can create a task for the context agent if not how to do it?

**Comment by zumbrunn** [comment]
@Holofractographic I don't think this problem necessarily needs to exist. The collective user you are talking about is *not* an individual, it is the user of the collective. So it can use the collective user faircoin address and doesn't need access to one of the collective agent. The individual logged in as the collective user will create an individual account for him/herself as individual, if that makes any sense.

**Comment by bhaugen** [comment]
A lot of confusion!

> collective must be a context agent

True.
> we created now two agents, one has a user and we call it decentrale mannager or user as an individual( in order to assign it the task of send the faircoin of the contribution as we couldnt do it as a collective) and a context agent that is decentrale, the collective. 

You requested that I allow you to assign tasks to a collective with a user. I planned to do that, but got disagreement from @bum2 in telegram, so I waited until you both agree. 

The big advantage of a collective user is that settles the question of who can manage the collective faircoin account: it is the collective user.
 
@zumbrunn wrote:

* The individual logged in as the collective user will create an individual account for him/herself as individual, if that makes any sense.

The collective user does not have permission to do that, or not yet. (We are still working out the permissions for the collective user, which was just implemented yesterday.) 

But it looks like @Holofractographic created a separate individual agent id named Cooperative Décentrale_U,  username dezentrale, as  as a member of the collective agent Cooperative Décentrale.

The description of Cooperative Décentrale_U says "This is the user created to manage the Decentrale project into OCP", but this agent is just a member of the Cooperative, not a manager. @Holofractographic - do you know how to fix that? If not, ask me in Telegram and I'll explain.

As of now, the collective agent Cooperative Décentrale  does not have a user, but could have one. If the collective had a user, that user, as @zumbrunn wrote above, would be able to manage the collective's faircoin account.

One odd part of this setup is that the individual agent Cooperative Décentrale_U has another automatically-created faircoin account. I don't know if that is a problem or not.

I hope that is all clear, but I suspect not yet. Please ask questions.

**Comment by Holofractographic** [comment]
So the way to do it is to delete the decentrale collective (as this agent dont have created a faircoin address and was not the first one created) and rename the decentrale_u as how it was at the begining and give it the role of context agent and go to the first procedure it is to treat it as the rest of individuals, I mean putting it on the membership request group as candidate and having the option to assign the task for the payment as we said this morning...

**Comment by Holofractographic** [comment]
so later in decentrale they decide to create or not other individual agents

**Comment by bhaugen** [comment]
> So the way to do it is to delete the decentrale collective (as this agent dont have created a faircoin address and was not the first one created) and rename the decentrale_u as how it was at the begining and give it the role of context agent and collective and go to the first procedure it is to treat it as the rest of individuals, I mean putting it on the membership request group as candidate and having the option to assign the task for the payment as we said this morning...

@Holofractographic - I think that would work, but let's wait until we get some consensus at least between you, me, @zumbrunn  and @bum2 ?

I know this is taking awhile to sort out, but this is our first collective member, and it is bringing up a lot of issues. This will not be the last of those isssues. And this was also totally predictable, and I think I did predict it. Once we get it sorted out, then the next collective member will have an easier time, and they will thank @zumbrunn for his patience.

**Comment by bhaugen** [comment]
And @Holofractographic they will thank you for your patience, and I do too right now! :heart:

**Comment by zumbrunn** [comment]
It sounds fine to me.

**Comment by bhaugen** [comment]
@zumbrunn thanks for the quick response.

**Comment by zumbrunn** [comment]
I thought you had thought that wouldn't work, but if you think that would work and I only thought you thought that wouldn't work, then that sounds fine to me. That's the less quick response ;-)

**Comment by bum2** [comment]
Ok, if we have this new collective user functionality, let's use it and see if we can do all the things needed... i'm confident on @bhaugen proposed changes will be good and enough to resolve the collective members... go ahead, and we can always switch to the 'double agent' old system if needed.

**Comment by Holofractographic** [comment]
Ok so lets go to revert it...

**Comment by bhaugen** [comment]
Good work, gang! :heart_eyes:

**Comment by bhaugen** [comment]
> I thought you had thought that wouldn't work,

If that was me, I knew it would work for handling the faircoin account. I still have a lot of questions about what the collective user can and cannot do, but we can deal with them as we go along.

But as I said a few times in a few places, it is great to have our first live collective member and work out all of those issue. So @zumbrunn you get to the be the guinea pig. Hope you like it.

Here are some of those other issues: https://github.com/FreedomCoop/valuenetwork/issues/108#issuecomment-239486008

I do have an opinion about one issue: I think we need to treat the collective user as the manager of the collective: that is, the collective user gets group manager permissions for their group. That is not true now, but I can make it so, and think I should do so. Does anybody disagree?

**Comment by bum2** [comment]
Yes, collective user is the first manager. He also can add other participants as project managers, but they will not be able to create other projects (only manage the one assigned)...

**Comment by bhaugen** [comment]
I see disagreement from E in Telegram.

**Comment by bhaugen** [comment]
I conclude from the telegram conversation that the collective user will have manager permissions.
