### ISSUE TITLE
Ability to send faircoins depends on permissions

### ISSUE THREAD

**Issue by XaviP** [FreedomCoop/valuenetwork#94]

**Comment by bhaugen** [comment]
@XaviP I don't see why this should be. You have successfully sent faircoins before. Do you have enough time and coins to test this? You are now a superuser. I could demote you to a staff user (the status of all coop admins) and you could try it from the coop admin app, and then I could demote you again to coop worker status, and try from the coop worker app, and we could see if this is true or if there's some other problem. Then of course I would promote you to staff and superuser again.

**Comment by XaviP** [comment]
It was because the new middlewares from django 1.8. Soved by @bhaugen Closing
