### ISSUE TITLE
A thought experiment about Freedom Coop memberships and organizational relationships

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#95]
This is a thought experiment. Its purpose is to stimulate discussion about how to organize Freedom Coop and OCP. Any or all parts of it might be wrong.

# What does a Freedom Coop membership mean economically? 

Why do you need to pay for it? And why do you need to pay ongoing “taxes” to continue to use it?

## It’s about reciprocity.

Reciprocity will still be necessary in a post-capitalist economic system. 

A great deal of effort and other resources have gone into creating Freedom Coop as a form for refugees and others to be able work using an alternative currency, FairCoins. And that effort has created an economic operating system for many people to be able to work in.

If you use that economic operating system, you have a reciprocal responsibility to help keep it going. Otherwise it won’t

That reciprocal responsibility could be fulfilled by money or work or other resources. If the money comes in the form of FairCoins, that helps to grow the economic operating system.

_(P.S. I know we are not enabling work-for-membership yet, but I think it is a good idea.)_

# What is a Freedom Coop membership?

It is something - but maybe not exactly - like a ticket or a share. You need to pay for it with FairCoins or work. You need to pay ongoing “taxes” to keep on using it.

It also is something like a contract or a lease, which spells out reciprocal rights and responsibilities.

In OCP, it might be an Economic Resource, that could progress through a Workflow Template, a series of Processes and Exchanges.

The input that starts the first process is the Membership Request.

Then the Freedom Coop Administrators create the Membership, along with the credentials you need to use OCP: an Agent, a login User, and a FairCoin Account.

They also associate you as a member with an organizational context in OCP where you will have some access and action permissions. 

At first you will be a candidate member, and the Membership resource is still “owned” by Freedom Coop until you pay the membership fee. When that happens, a set of reciprocal transfers take place: Freedom Coop gives you the Membership, which you now “own”, and you give Freedom Coop some FairCoins or the equivalent hours of work. And your access and action permissions will be increased. Some examples that have mentioned, not to say these are accurate, but just to explain the idea of increased permissions:
* A candidate member may not be able to send FairCoins from their OCP account to external addresses. A full member can do so.
* A candidate member may not be able to create new projects. A full member may be able to do so, possibly with some other conditions.

**Comment by bum2** [comment]
First of all, the initial contribution is a share (or many shares) but is only once in life. Once you are member, you can use some common services offered only to members. For that services it can be payed a quarterly fee to the common, depending on use and volume of each service. If only using the platform to manage projects and don't need other services, then no fee is payed.
If a member leaves the cooperative, the shares are available to new members, so they can be returned.

Before making the membership contribution user is 'candidate' (similar to the future 'project particiapant' role), can participate in projects and tasks and can send his faircoins out of the system. Only is not seeing the address to fill in external faircoins, but i don't know if that can be really avoided.

Once contributed the share, the new FreedomCoop member will see other menu items for other options and services. I'm trying to define this members menu, but we need a def property to see if user.agent (or user.agent.agent) is FCmember or not in the templates...

Let's think on a way to define this boolean when candidate pays the faircoins of the share, so became full member. Maybe is just a boolean for admins in the agent profile to put manually...
 
Now there's .is_coop_worker (for all ocp users) and .is_staff (for admins), but let's do a .is_member to achieve all this. Don't want to add a field in the model, so maybe a def like: "search a done task of x kind and a exchange of x type, to see if the agent payed the initial contribution or not..." ...mm, help

**Comment by bhaugen** [comment]
If the membership is a thing, like a faircoin address, we can see if they got one, and if it is paid up. So is_member can be a fairly simple method. And does not fit a field on the model, it is a result of getting and paying for a membership.

That's part of why I like a membership as a thing (in OCP terms, an Economic Resource). But other models are possible.

**Comment by bum2** [comment]
Yes, as i see it, the membership is a bunch of shares in the cooperative, but is not a resource that can be traded. Is a personal intransferible 'participation' (an inmaterial good), only able to go from the coop to user and from user to the coop.

**Comment by bhaugen** [comment]
I agree. Cannot be traded. It's something that only belongs to the member (once paid off) and cannot belong to anybody else.

**Comment by fosterlynn** [comment]
Question: Can a membership be revoked?  Say for example if people don't pay their quarterly taxes/fees?

**Comment by bum2** [comment]
I think not. The quarterly taxes-fees are not related the membership, only about the services they use, so if someone don't pay a regilar fee, we stop doing the service for him. The membership remains as long as the parties want. There are no fees to become a Member, only a initial share, once and forever.
If someone wants to go out, the coop should be able to return the shares, and offer to new members.
