### ISSUE TITLE
Old and new methods of creating agents for membership requests

### ISSUE THREAD

**Issue by bhaugen** [FreedomCoop/valuenetwork#99]
# Old method: 

* Get an email about the membership request. It will contain a link to the membership request table.
* Go to the membership request table, https://ocp.freedomcoop.eu/accounting/membership-requests/
* Create an agent and user for the membership request using the Create Agent button on the Organization page. When you create the agent, you will land on the agent's page, where you can create a user.
    * Also, associate the new agent with a group or project.
* Go back to the membership request table and select the agent you just created using the selection widget in the Created Agent column for that membership request.

# New method:

* Get an email about the membership request. It will contain links to 
    * a Todo (simple task) to create the agent, with a link go a new page where you can create an agent with a lot of the info prefilled from the request and connect to the request automatically. 
    * it will also include a direct link to the page to create the agent, and
    *  It will also contain a link to the membership request table.
    * Like the Create Agent button on the Orgnization page, when you create the agent on this new page, you will land on the agent's page, where you can create a user.
* Go to the Todo task  and click the "Mine!" button, which means you are taking this task, so nobody else will do it in the meantime
.   * Go to the new page from the link in the Todo. It says "Open" on the Todo.
    * Create the agent for the membership request, which will be automatically connected to the request.
    * Create a user for the agent.
    *  Also, associate the new agent with a group or project.
* Go to the Todo and click "Done". You may put in some hours if you want.

In the future, we could also create the user at the same time we create the agent, in the same form.

**Comment by fosterlynn** [comment]
Here is a suggestion to simplify this more:

1. The email that admins receive should only have one link, and OCP should then tell them what to do from there.

2. The one link should go to the new page where you see the membership request.  The simple task (todo) will be added to that page, and you can say Mine! right there.  If someone else already took the simple task, it will just say that someone else is already working on it, and the Create Agent button would be disabled.  This page should also include the following instructions.

3. So, when you get to that page, you say Mine!.  Then you click Create Agent button, create the agent, using the already filled in membership request data.

4. That takes you to the agent page (it does that now), and you create a user and associate the new agent with a group or project, as above.

**Comment by bum2** [comment]
Marvelous! And now from the candidate point of view:

1- fill the form
2- wait for the admins manual email with ocp credentials and the guide
3a- user logs-in and don't see any task, but using the 'membership' menu button goes to the comments page.
3a- user logs-in and see a task in the 'my tasks' page, assigned to him/her. This task can be clicked on it to open and read about the whole process and see or link the comments page. 

Another option is to set 2 tasks preasigned to the member (fill the wallet, make the contribution) when user first logs-in (not grouped into a process task). And keep the comments in the 'membership process' page. Maybe it's the easiest now?

**Comment by bhaugen** [comment]
See also https://github.com/FreedomCoop/valuenetwork/issues/90#issuecomment-238923625

**Comment by Holofractographic** [comment]
Hi! now what we are doing is to create the agent and the user and create a task in wich give to the new member info about the freedom coop address to send the contribution to become a member, so the first thing they see in their porfile is a task with this info (the instructions on how to do it is also in the welcome guide) Santi did it in that way and he find easy to understand and follow. With this they have their first approach to OCP and to taks and have the info about the freedom coop address

**Comment by bhaugen** [comment]
@Holofractographic are you doing it the old way described above, or the new way?

And do you think that procedure you used with Santi is good enough for now for new member payments? Could you tell if Santi had actually made the payment? Was he doing it from his faircoin address in OCP, or from an external address that he already had?

**Comment by bum2** [comment]
The payment must be done from the ocp account, so we can track it. The instructions are to fill the wallet first with external faircoins, then pay the 'share' from user ocp wallet to coop ocp wallet.

**Comment by bhaugen** [comment]
Ok, that should work and also show the admins who paid. @XaviP put the internal address names on the history.

**Comment by bum2** [comment]
The missing thing is to create a button like "contribute your shares" to click on it when is candidate and there are enough fairs in the account. Once clicked, disappears forever. This way we don't need to publish or say the 'membership-request' faircoin address, and we can keep the transactions only attached to members.

**Comment by bhaugen** [comment]
Good idea.
